Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-12, with the labels that each got.

#929 Fix typo
  articles/azure-databricks/quickstart-create-databricks-workspace-portal.md
Labels: Accepted, Technical Issue

#930 Fix typo
  articles/azure-databricks/quickstart-create-databricks-workspace-resource-manager-template.md
Labels: Accepted, Technical Issue

#931 Fix typo
  articles/storage/data-lake-storage/handle-data-using-databricks.md
Labels: Accepted, Technical Issue

#932 Fix typo
  articles/azure-databricks/databricks-stream-from-eventhubs.md
Labels: Accepted, Technical Issue

#933 Fix typo
  articles/azure-databricks/databricks-extract-load-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#935 Fix typo
  articles/service-fabric-mesh/includes/include-preview-note.md
Labels: Accepted, Linguistic Suggestion

#936 Fix typo
  articles/service-fabric-mesh/service-fabric-mesh-overview.md
Labels: Accepted, Linguistic Suggestion

#939 Fix typo
  articles/service-fabric-mesh/service-fabric-mesh-tutorial-create-dotnetcore.md
Labels: Accepted, Linguistic Suggestion

#941 Fix typo
  includes/load-balancer-comparison-table.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#942 Fix typo
  includes/cognitive-services-qnamaker-quickstart-csharp-required-dependencies.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#943 Fix typo
  articles/virtual-machines/windows/tutorial-backup-vms.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#944 Fix typo
  articles/virtual-machines/windows/classic/mysql-2008r2.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#945 Fix typo
  articles/virtual-machines/windows/classic/capture-image-classic.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#946 Fix typo
  articles/virtual-machines/troubleshooting/serial-console-grub-single-user-mode.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#947 Fix typo
  articles/virtual-machines/linux/update-infrastructure-redhat.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#948 Fix typo
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#949 Fix typo
  articles/time-series-insights/time-series-insights-diagnose-and-solve-problems.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#950 Fix typo
  articles/storsimple/storsimple-8000-manage-volumes-u2.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#951 Fix typo
  articles/storsimple/storsimple-8000-device-failover-disaster-recovery.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#952 Fix typo
  articles/storsimple/storsimple-8000-create-manage-support-package.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#953 Fix typo
  articles/storsimple/storsimple-8000-configure-web-proxy.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#954 Fix typo
  articles/sql-database/saas-tenancy-cross-tenant-reporting.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#955 Fix typo
  articles/sql-database/saas-dbpertenant-restore-single-tenant.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#957 Fix typo
  articles/service-fabric/service-fabric-cluster-resource-manager-balancing.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#958 Fix typo
  articles/service-fabric/service-fabric-cluster-resource-manager-cluster-description.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#970 Fix typo
  articles/machine-learning/desktop-workbench/known-issues-and-troubleshooting-guide.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#971 Fix typo
  articles/machine-learning/desktop-workbench/how-to-use-gpu.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#972 Fix typo
  articles/machine-learning/desktop-workbench/how-to-build-deploy-forecast-models.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#973 update description
  articles/log-analytics/log-analytics-tutorial-viewdata.md
Labels: Accepted, Linguistic Suggestion

#974 Update log-analytics-tutorial-viewdata.md
  articles/log-analytics/log-analytics-tutorial-viewdata.md
Labels: Accepted, Linguistic Suggestion

#1002 Update assign-access-acm-data.md
  articles/cost-management/assign-access-acm-data.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#997 typo
  articles/application-insights/app-insights-tutorial-performance.md
Labels: Accepted, Linguistic Suggestion

#975 Fix typo
  articles/active-directory-b2c/json-transformations.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#996 fix 'in'
  includes/data-box-edge-gateway-port-config.md
Labels: Accepted, Linguistic Suggestion

#985 Fix typo
  articles/storage/common/storage-redundancy-zrs.md
Labels: Accepted, Source Issue

#976 Fix typo
  articles/active-directory/develop/quickstart-v1-nodejs-webapi.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#977 Fix typo
  articles/active-directory/hybrid/how-to-connect-pta-current-limitations.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#978 Fix typo
  articles/active-directory/hybrid/how-to-connect-pta-faq.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#979 Fix typo
  articles/active-directory/hybrid/how-to-connect-pta-security-deep-dive.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#980 Fix typo
  articles/active-directory/hybrid/how-to-connect-pta-quick-start.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#981 Fix typo
  articles/active-directory/hybrid/how-to-connect-sso-quick-start.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#983 Fix typo
  articles/active-directory/hybrid/tshoot-connect-pass-through-authentication.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#984 Fix typo
  articles/active-directory/hybrid/tshoot-connect-sso.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#987 Fix typo
  articles/app-service/app-service-ip-addresses.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#988 Fix typo
  articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#989 Fix typo
  articles/app-service/app-service-web-tutorial-nodejs-mongodb-app.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#990 Fix typo
  articles/app-service/app-service-web-tutorial-php-mysql.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#991 Fix typo
  articles/app-service/containers/tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1006 Fix typo
  articles/azure-functions/app-service-export-api-to-powerapps-and-flow.md
Labels: In Progress, Linguistic Suggestion

#995 Correction of Japanese translation
  articles/expressroute/expressroute-faqs.md
Labels: Accepted, Linguistic Suggestion

#1000 Update log-analytics-tutorial-response.md
  articles/log-analytics/log-analytics-tutorial-response.md
Labels: Accepted, Linguistic Suggestion

#1089 Fix typo
  articles/iot-dps/tutorial-group-enrollments.md
Labels: Accepted

#1088 Fix typo
  articles/iot-dps/quick-enroll-device-x509-python.md
Labels: Accepted

#1087 Fix typo
  articles/iot-dps/quick-enroll-device-x509-java.md
Labels: Accepted

#1085 Fix typo
  articles/iot-central/howto-manage-devices.md
Labels: Accepted

#1084 Fix typo
  articles/governance/blueprints/overview.md
Labels: Accepted

#1083 Fix typo
  articles/cost-management/use-reports.md
Labels: Accepted

#1082 Fix typo
  articles/azure-portal/azure-portal-dashboards-structure.md
Labels: Accepted

#1080 Fix typo
  articles/hdinsight/hadoop/apache-hadoop-dotnet-csharp-mapreduce-streaming.md
Labels: Accepted

#1079 Fix typo
  articles/hdinsight/hdinsight-extend-hadoop-virtual-network.md
Labels: Accepted

#1078 Fix typo
  articles/hdinsight/hdinsight-hadoop-linux-use-ssh-unix.md
Labels: Accepted

#1077 Fix typo
  articles/iot-accelerators/iot-accelerators-remote-monitoring-deploy-cli.md
Labels: Accepted

#1076 Fix typo
  articles/hdinsight/storm/apache-storm-develop-java-topology.md
Labels: Accepted

#1075 Fix typo
  articles/hdinsight/storm/apache-storm-deploy-monitor-topology-linux.md
Labels: Accepted

#1073 Fix typo
  articles/hdinsight/kafka/apache-kafka-mirroring.md
Labels: Accepted

#1072 Fix typo
  articles/hdinsight/kafka/apache-kafka-azure-container-services.md
Labels: Accepted

#1071 Fix typo
  articles/hdinsight/kafka/apache-kafka-connect-vpn-gateway.md
Labels: Accepted

#1070 Fix typo
  articles/hdinsight/kafka/apache-kafka-auto-create-topics.md
Labels: Accepted

#1069 Fix typo
  articles/hdinsight/hdinsight-hadoop-script-actions-linux.md
Labels: Accepted

#1068 Fix typo
  articles/hdinsight/hdinsight-hadoop-install-mono.md
Labels: Accepted

#1067 Fix typo
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-curl-rest.md
Labels: Accepted

#1066 Fix typo
  articles/hdinsight/hdinsight-hadoop-add-storage.md
Labels: Accepted

#1064 Fix typo
  articles/hdinsight/hdinsight-debug-ambari-tez-view.md
Labels: Accepted

#1063 Fix typo
  articles/hdinsight/hdinsight-component-versioning.md
Labels: Accepted

#1062 Fix typo
  articles/hdinsight/hdinsight-apache-storm-with-kafka.md
Labels: Accepted

#1060 Fix typo
  articles/hdinsight/hadoop/apache-hadoop-hive-pig-udf-dotnet-csharp.md
Labels: Accepted

#1058 Fix typo
  articles/hdinsight/apache-kafka-spark-structured-streaming-cosmosdb.md
Labels: Accepted

#1057 Fix typo
  articles/governance/resource-graph/samples/advanced.md
Labels: Accepted

#1056 Fix typo
  articles/governance/policy/tutorials/create-and-manage.md
Labels: Accepted

#1055 Fix typo
  articles/governance/policy/how-to/getting-compliance-data.md
Labels: Accepted

#1054 Fix typo
  articles/frontdoor/front-door-troubleshoot-routing.md
Labels: In Progress, Linguistic Suggestion

#1048 Update quick-backup-vm-portal.md
  articles/backup/quick-backup-vm-portal.md
Labels: Accepted, Linguistic Suggestion

#1051 Update tutorial-backup-vm-at-scale.md
  articles/backup/tutorial-backup-vm-at-scale.md
Labels: In Progress, Linguistic Suggestion

#1053 Update tutorial-restore-disk.md
  articles/backup/tutorial-restore-disk.md
Labels: Accepted, Linguistic Suggestion

#1106 Fix typo
  articles/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance.md
Labels: Accepted, Linguistic Suggestion

#1107 Fix typo
  articles/postgresql/concepts-query-store-best-practices.md
Labels: Accepted, Linguistic Suggestion

#1108 Fix typo
  articles/service-fabric/service-fabric-backuprestoreservice-configure-periodic-backup.md
Labels: Accepted, Technical Issue

#1096 Fix typo
  articles/iot-hub/tutorial-firmware-update.md
Labels: Accepted, Linguistic Suggestion

#1097 Fix typo
  articles/key-vault/key-vault-key-rotation-log-monitoring.md
Labels: Accepted, Linguistic Suggestion

#1112 fix 'Action' and fit to the localized Azure Portal
  articles/virtual-network/manage-network-security-group.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1098 Fix typo
  articles/load-balancer/load-balancer-outbound-connections.md
Labels: In Progress, Linguistic Suggestion

#1099 Fix typo
  articles/machine-learning/data-science-virtual-machine/overview.md
Labels: Accepted, Linguistic Suggestion

#1100 Fix typo
  articles/machine-learning/desktop-workbench/experimentation-service-configuration-reference.md
Labels: Accepted, Linguistic Suggestion

#1101 Fix typo
  articles/machine-learning/desktop-workbench/experimentation-service-configuration.md
Labels: Accepted, Linguistic Suggestion

#1102 Fix typo
  articles/machine-learning/service/azure-machine-learning-release-notes.md
Labels: Accepted, Linguistic Suggestion

#1103 Fix typo
  articles/machine-learning/service/concept-azure-machine-learning-architecture.md
Labels: Accepted, Linguistic Suggestion

#1105 Fix typo
  articles/machine-learning/service/how-to-set-up-training-targets.md
Labels: Accepted, Linguistic Suggestion

#1109 Improve translation
  articles/application-insights/app-insights-sampling.md
Labels: In Progress, Linguistic Suggestion

#1110 Update api-management-caching-policies.md
  articles/api-management/api-management-caching-policies.md
Labels: Accepted, Linguistic Suggestion

#1118 Fix unnecessary translation
  articles/aks/index.yml
Labels: Accepted, Linguistic Suggestion

#1117 Fix unnecessary translation
  articles/aks/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1170 Fix unnecessary translation
  articles/data-factory/index.yml
Labels: Accepted, Linguistic Suggestion

#1167 Fix unnecessary translation
  articles/cosmos-db/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1164 Fix unnecessary translation
  articles/cosmos-db/sql-api-sdk-dotnet.md
Labels: Accepted, Linguistic Suggestion

#1251 Fix unnecessary translation
  articles/virtual-machines/linux/toc.yml
Labels: Accepted, Linguistic Suggestion

#1162 Fix unnecessary translation
  articles/cosmos-db/sql-api-sdk-dotnet-changefeed.md
Labels: Accepted, Linguistic Suggestion

#1161 Fix unnecessary translation
  articles/cosmos-db/sql-api-sdk-bulk-executor-java.md
Labels: Accepted, Linguistic Suggestion

#1154 Fix unnecessary translation
  articles/container-registry/index.yml
Labels: Accepted, Linguistic Suggestion

#1203 Fix unnecessary translation
  articles/media-services/latest/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1214 Fix unnecessary translation
  articles/media-services/previous/media-services-rest-encode-asset.md
Labels: Accepted, Linguistic Suggestion

#1151 Fix unnecessary translation
  articles/cognitive-services/text-analytics/index.yml
Labels: Accepted, Linguistic Suggestion

#1215 Fix unnecessary translation
  articles/media-services/previous/media-services-rest-get-media-processor.md
Labels: Accepted, Linguistic Suggestion

#1216 Fix unnecessary translation
  articles/media-services/previous/TOC.md
Labels: Accepted, Linguistic Suggestion

#1217 Fix unnecessary translation
  articles/network-watcher/index.yml
Labels: Accepted, Linguistic Suggestion

#1147 Fix unnecessary translation
  articles/cognitive-services/Speech-Service/speech-to-text.md
Labels: Accepted, Linguistic Suggestion

#1146 Fix unnecessary translation
  articles/cognitive-services/Bing-Web-Search/index.yml
Labels: Accepted, Linguistic Suggestion

#1143 Fix unnecessary translation
  articles/cloud-services/toc.yml
Labels: Accepted, Linguistic Suggestion

#1142 Fix unnecessary translation
  articles/cloud-services/index.md
Labels: Accepted, Linguistic Suggestion

#1141 Fix unnecessary translation
  articles/cdn/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1219 Fix unnecessary translation
  articles/networking/TOC.md
Labels: Accepted, Linguistic Suggestion

#1140 Fix unnecessary translation
  articles/cdn/index.yml
Labels: Accepted, Linguistic Suggestion

#1220 Fix unnecessary translation
  articles/notification-hubs/index.yml
Labels: Accepted, Linguistic Suggestion

#1221 Fix unnecessary translation
  articles/postgresql/index.yml
Labels: Accepted, Linguistic Suggestion

#1222 Fix unnecessary translation
  articles/power-bi-embedded/index.md
Labels: Accepted, Linguistic Suggestion

#1136 Fix unnecessary translation
  articles/batch-ai/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1225 Fix unnecessary translation
  articles/search/search-import-data-dotnet.md
Labels: Accepted, Linguistic Suggestion

#1226 Fix unnecessary translation
  articles/search/search-language-support.md
Labels: Accepted, Linguistic Suggestion

#1227 Fix unnecessary translation
  articles/search/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1228 Fix unnecessary translation
  articles/service-bus-messaging/index.yml
Labels: Accepted, Linguistic Suggestion

#1134 Fix unnecessary translation
  articles/backup/index.yml
Labels: Accepted, Linguistic Suggestion

#1229 Fix unnecessary translation
  articles/service-bus-messaging/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1126 Fix unnecessary translation
  articles/automation/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1125 Fix unnecessary translation
  articles/automation/index.yml
Labels: Accepted, Linguistic Suggestion

#1230 Fix unnecessary translation
  articles/service-bus-relay/index.yml
Labels: Accepted, Linguistic Suggestion

#1231 Fix unnecessary translation
  articles/service-fabric/index.yml
Labels: Accepted, Linguistic Suggestion

#1232 Fix unnecessary translation
  articles/service-fabric/service-fabric-containers-view-logs.md
Labels: Accepted, Linguistic Suggestion

#1233 Fix unnecessary translation
  articles/service-fabric/service-fabric-report-health.md
Labels: Accepted, Linguistic Suggestion

#1202 Fix unnecessary translation
  articles/managed-applications/toc.yml
Labels: Accepted, Linguistic Suggestion

#1236 Fix unnecessary translation
  articles/site-recovery/index.yml
Labels: Accepted, Linguistic Suggestion

#1191 Fix unnecessary translation
  articles/hdinsight/storm/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1190 Fix unnecessary translation
  articles/hdinsight/r-server/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1188 Fix unnecessary translation
  articles/hdinsight/interactive-query/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1113 fix 'Extension'
  articles/security/azure-log-audit.md
  articles/service-fabric/service-fabric-service-model-schema-complex-types.md
  articles/service-fabric/service-fabric-service-model-schema-elements.md
Labels: Accepted, Linguistic Suggestion

#1260 Update load-balancer-comparison-table.md
  includes/load-balancer-comparison-table.md
Labels: Accepted, Linguistic Suggestion

#1262 Fix unnecessary translation
  articles/azure-cache-for-redis/index.md
Labels: Accepted, Linguistic Suggestion

#1263 Fix unnecessary translation
  articles/azure-cache-for-redis/TOC.yml
Labels: Accepted, Linguistic Suggestion

#1270 Improve translation
  articles/container-registry/container-registry-tasks-overview.md
Labels: Accepted, Linguistic Suggestion

#1271 Improve translation & delete unnecessary spaces
  articles/cosmos-db/programming.md
Labels: Accepted, Linguistic Suggestion

#1273 Update tutorial-manage-vm.md
  articles/virtual-machines/windows/tutorial-manage-vm.md
Labels: Accepted, Linguistic Suggestion

#1275 Update tutorial-custom-images.md
  articles/virtual-machines/windows/tutorial-custom-images.md
Labels: Accepted, Linguistic Suggestion
