Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-11, with the labels that each got.

#859 承認 → 認可
  articles/active-directory-b2c/active-directory-b2c-reference-oidc.md
Labels: Accepted, Linguistic Suggestion

#869 restore 'Degree'
  articles/cognitive-services/Bing-Web-Search/search-responses.md
Labels: Accepted, Linguistic Suggestion

#870 Fix nonunified
  articles/virtual-machines/windows/toc.yml
Labels: Accepted, Linguistic Suggestion

#873 fix 'applications'
  articles/api-management/api-management-user-profile-templates.md
Labels: Accepted, Linguistic Suggestion

#871 Fix: Typo
  articles/machine-learning/service/concept-model-management-and-deployment.md
Labels: Accepted, Linguistic Suggestion

#875 Fix typo
  articles/virtual-network/toc.yml
Labels: Accepted, Linguistic Suggestion

#876 Fix typo
  articles/stream-analytics/TOC.yml
Labels: Accepted, Linguistic Suggestion

#877 Fix typo
  articles/virtual-machine-scale-sets/TOC.yml
Labels: Accepted, Linguistic Suggestion

#878 Fix typo
  articles/databox-online/TOC.yml
Labels: Accepted, Linguistic Suggestion

#879 Fix typo
  articles/container-instances/TOC.yml
Labels: Accepted, Linguistic Suggestion

#881 Update how-to-configure-auto-train.md
  articles/machine-learning/service/how-to-configure-auto-train.md
Labels: Accepted, Linguistic Suggestion

#868 Fix nonunified
  includes/virtual-machines-managed-disks-overview.md
Labels: Accepted, Linguistic Suggestion

#882 Fix typo
  articles/app-service-mobile/TOC.md
Labels: Accepted, Linguistic Suggestion

#883 Improve translation
  articles/marketplace/cloud-partner-portal-orig/cloud-partner-portal-create-iot-edge-module-offer.md
Labels: Accepted, Linguistic Suggestion

#874 improve translations for `term`
  articles/api-management/api-management-template-data-model-reference.md
  articles/cosmos-db/cosmos-db-reserved-capacity.md
  articles/sql-database/sql-database-reserved-capacity.md
  articles/virtual-machines/linux/prepay-suse-software-charges.md
  includes/virtual-machines-common-prepay-reserved-vm-instances.md
Labels: Accepted, Linguistic Suggestion

#884 fix 'machine learning'
  articles/hdinsight/hdinsight-apps-install-h2o.md
  articles/index.md
Labels: Accepted, Linguistic Suggestion

#887 Update iaas-antimalware-windows.md
  articles/virtual-machines/extensions/iaas-antimalware-windows.md
Labels: Accepted, Linguistic Suggestion

#889 Fix typo
  articles/service-fabric-mesh/index.yml
Labels: Accepted, Linguistic Suggestion

#890 Fix typo
  articles/service-fabric-mesh/service-fabric-mesh-quickstart-deploy-container.md
Labels: Accepted, Linguistic Suggestion

#892 Fix typo
  articles/service-fabric-mesh/service-fabric-mesh-tutorial-debug-service-fabric-mesh-app.md
Labels: Accepted, Linguistic Suggestion

#895 Improve translation
  articles/security-center/security-center-os-coverage.md
Labels: Accepted, Linguistic Suggestion

#891 a very little change to be more natural Japanese
  articles/azure-stack/user/azure-stack-create-vm-template.md
Labels: Accepted, Linguistic Suggestion

#907 Fix typo
  articles/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#910 Update overview.md
  articles/cognitive-services/Speech-Service/overview.md
Labels: Accepted, Linguistic Suggestion

#905 fix 'NA'
  articles/frontdoor/front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion

#906 Fix typo
  articles/machine-learning/service/overview-what-happened-to-workbench.md
Labels: Accepted

#908 Update azure-stack-servicing-policy.md
  articles/azure-stack/azure-stack-servicing-policy.md
Labels: Accepted, Linguistic Suggestion

#915 Update TOC.yml
  articles/azure-stack/TOC.yml
Labels: Accepted, Linguistic Suggestion

#902 fix 'messages'
  articles/marketplace/cloud-partner-portal-orig/cloud-partner-portal-api-retrieve-offer-status.md
  articles/service-bus-messaging/service-bus-amqp-request-response.md
Labels: Accepted, Linguistic Suggestion

#911 Update capacity-planning-compute.md
  articles/azure-stack/capacity-planning-compute.md
Labels: In Progress, Linguistic Suggestion

#914 Update capacity-planning.md
  articles/azure-stack/capacity-planning.md
Labels: Accepted, Linguistic Suggestion

#917 restore 'source'
  articles/active-directory/manage-apps/functions-for-customizing-application-data.md
Labels: Accepted, Linguistic Suggestion

#922 Japanese word is wrong.
  articles/virtual-network/manage-network-security-group.md
Labels: Accepted, Linguistic Suggestion

#925 Remove unnecessary bracket
  articles/machine-learning/service/how-to-access-data.md
Labels: Accepted, Linguistic Suggestion
