Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-06, with the labels that each got.

#534 field names
  includes/virtual-machines-common-prepay-reserved-vm-instances.md
Labels: In Progress, Linguistic Suggestion

#528 property names should not be translated.
  articles/data-factory/concepts-pipelines-activities.md
  articles/data-factory/connector-azure-data-lake-store.md
  articles/data-factory/connector-ftp.md
  articles/data-factory/connector-sftp.md
Labels: Accepted, Linguistic Suggestion

#530 Update about-disks-and-vhds.md
  articles/virtual-machines/windows/about-disks-and-vhds.md
Labels: Accepted, Linguistic Suggestion

#542 names should not be translated
  articles/media-services/media-services-specifications-live-timed-metadata.md
Labels: Accepted, Linguistic Suggestion

#541 Update active-directory-aadconnect-sso.md
  articles/active-directory/connect/active-directory-aadconnect-sso.md
Labels: Accepted, Linguistic Suggestion

#546 Updatecreate-url-route-portal.md
  articles/application-gateway/create-url-route-portal.md
Labels: Accepted, Source Issue

#548 remove link generated by mistake
  articles/aks/kubernetes-dashboard.md
Labels: Accepted, Linguistic Suggestion

#553 fix date comparison query
  articles/log-analytics/log-analytics-log-search-transition.md
Labels: In Progress, Linguistic Suggestion
