Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-09, with the labels that each got.

#682 delete sentences that don't exist in the original text
  articles/data-factory/connector-azure-sql-data-warehouse.md
  articles/data-factory/connector-azure-sql-database.md
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted, Source Issue

#683 fix the translations for 'valid names'
  articles/sql-database/sql-database-managed-instance-create-tutorial-portal.md
  articles/sql-database/sql-database-managed-instance-get-started.md
  articles/sql-database/sql-database-managed-instance-restore-from-backup-tutorial.md
Labels: Accepted, Linguistic Suggestion

#680 restore 'update'
  articles/active-directory/connect/active-directory-aadconnectsync-feature-preferreddatalocation.md
Labels: Accepted, Linguistic Suggestion

#681 restore headings
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted, Linguistic Suggestion

#688 Fix typo
  articles/data-factory/connector-salesforce.md
Labels: Accepted, Linguistic Suggestion

#686 fix translations for 'users and groups'
  articles/active-directory/conditional-access/app-based-mfa.md
  articles/active-directory/conditional-access/app-sign-in-risk.md
  articles/active-directory/conditional-access/conditions.md
  articles/active-directory/conditional-access/require-tou.md
Labels: Accepted, Linguistic Suggestion

#684 Update virtual-network-ip-addresses-overview-arm.md
  articles/virtual-network/virtual-network-ip-addresses-overview-arm.md
Labels: Accepted, Linguistic Suggestion

#687 Fix mistranslation
  articles/media-services/latest/assets-concept.md
Labels: Accepted, Linguistic Suggestion

#689 [ask]配布という訳について
  articles/security/azure-infrastructure-network.md
Labels: Accepted, Linguistic Suggestion

#694 suggest not to translate SLES 'Priority'
  articles/security/azure-security-disk-encryption-faq.md
Labels: Accepted, Linguistic Suggestion

#698 Fix mistranslation
  articles/media-services/previous/media-services-portal-vod-get-started.md
Labels: Accepted, Linguistic Suggestion

#691 Update the explanation of Forward request
  articles/api-management/api-management-advanced-policies.md
Labels: Accepted, Linguistic Suggestion

#692 Update import-and-publish.md
  articles/api-management/import-and-publish.md
Labels: Accepted, Linguistic Suggestion

#696 fix a heading
  articles/active-directory/active-directory-hybrid-identity-design-considerations-lifecycle-adoption-strategy.md
Labels: Accepted, Linguistic Suggestion

#699 Japanese translation is difficult to understand.
  includes/load-balancer-comparison-table.md
Labels: Accepted, Linguistic Suggestion

#705 fix headings and names of parameters
  articles/active-directory/manage-apps/functions-for-customizing-application-data.md
Labels: Accepted, Linguistic Suggestion

#712 fix package name and link
  articles/azure-functions/functions-bindings-storage-queue.md
Labels: In Progress, Linguistic Suggestion

#706 Fix mistranslation
  articles/media-services/previous/media-services-portal-upload-files.md
Labels: Accepted, Linguistic Suggestion

#674 Add enabling tls
  includes/vpn-gateway-tls-updates.md
Labels: In Progress, Source Issue

#714 improve translation for 'knowledge base'
  articles/cognitive-services/QnAMaker/Quickstarts/create-new-kb-go.md
  articles/cognitive-services/QnAMaker/Quickstarts/create-new-kb-java.md
  articles/cognitive-services/QnAMaker/Quickstarts/create-new-kb-nodejs.md
  articles/cognitive-services/QnAMaker/Quickstarts/create-new-kb-python.md
  articles/cognitive-services/QnAMaker/Quickstarts/update-kb-go.md
Labels: Accepted, Linguistic Suggestion

#715 suggest not to translate API names of Face API
  articles/cognitive-services/Face/Overview.md
  articles/cognitive-services/Face/QuickStarts/PHP.md
  articles/cognitive-services/Face/QuickStarts/Ruby.md
  articles/cognitive-services/Face/QuickStarts/go.md
  articles/cognitive-services/Face/QuickStarts/node.md
Labels: Accepted, Linguistic Suggestion

#708 Fix mistranslation
  articles/azure-functions/functions-compare-logic-apps-ms-flow-webjobs.md
Labels: Accepted, Linguistic Suggestion

#711 Add one word to Japanese translation.
  includes/load-balancer-comparison-table.md
Labels: Accepted, Linguistic Suggestion

#713 Japanese translation is difficult to understand
  articles/application-gateway/application-gateway-create-multisite-portal.md
Labels: Accepted, Linguistic Suggestion

#718 restore 'Update'
  articles/active-directory/connect/active-directory-aadconnectsync-change-the-configuration.md
Labels: Accepted, Linguistic Suggestion

#720 Fix mistranslation
  articles/media-services/latest/stream-files-tutorial-with-rest.md
Labels: Accepted, Linguistic Suggestion

#717 Update active-directory-ds-networking.md
  articles/active-directory-domain-services/active-directory-ds-networking.md
Labels: In Progress, Linguistic Suggestion

#724 Improve translations
  articles/storage/blobs/storage-blob-static-website.md
Labels: Accepted, Linguistic Suggestion

#723 Improve translations
  articles/app-service/app-service-web-get-started-html.md
Labels: Accepted, Linguistic Suggestion

#729 TimeSpan example 24: 00: 00 was every 24 days so fix every day
  articles/azure-functions/functions-bindings-timer.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#731 Improve translation
  articles/data-lake-analytics/data-lake-analytics-u-sql-get-started.md
Labels: Accepted, Linguistic Suggestion

#730 fix a check mark
  articles/active-directory-domain-services/active-directory-ds-getting-started-password-sync-synced-tenant.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#735 fix method names
  articles/active-directory/hybrid/reference-connect-sync-functions-reference.md
Labels: Accepted, Linguistic Suggestion

#736 suggest to fix 'source'
  articles/active-directory/manage-apps/functions-for-customizing-application-data.md
Labels: Accepted, Linguistic Suggestion

#732 Fix nonunified
  articles/app-service/app-service-ip-addresses.md
  articles/azure-stack/asdk/asdk-prepare-host.md
  articles/virtual-machines/linux/tutorial-manage-vm.md
  articles/virtual-machines/workloads/sap/hana-vm-operations.md
  articles/virtual-machines/workloads/sap/sap-high-availability-infrastructure-wsfc-shared-disk.md
  articles/virtual-network/virtual-network-ip-addresses-overview-classic.md
Labels: Accepted, Linguistic Suggestion

#727 Improve translations
  articles/azure-functions/functions-develop-vs.md
Labels: In Progress, Linguistic Suggestion

#737 Optimize content
  articles/active-directory/hybrid/how-to-connect-install-automatic-upgrade.md
Labels: Accepted, Linguistic Suggestion
