Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-03, with the labels that each got.

#459 Update identity-fundamentals.md
  articles/active-directory/identity-fundamentals.md
Labels: Accepted, Linguistic Suggestion

#458 Update log-analytics-data-sources-custom-logs.md
  articles/log-analytics/log-analytics-data-sources-custom-logs.md
Labels: In Progress, Linguistic Suggestion

#464 Typo in Japanese.
  articles/cdn/cdn-custom-ssl.md
Labels: In Progress, Linguistic Suggestion

#467 Update backup-introduction-to-azure-backup.md
  articles/backup/backup-introduction-to-azure-backup.md
Labels: Accepted, Linguistic Suggestion

#466 Update toc.yml
  articles/backup/toc.yml
Labels: Accepted, Linguistic Suggestion

#463 Fix translation bug
  articles/application-gateway/application-gateway-faq.md
Labels: Accepted, Linguistic Suggestion

#474 fix indent in the sample code
  articles/azure-functions/functions-dotnet-class-library.md
Labels: Accepted, Source Issue

#473 Update virtual-network-ip-addresses-overview-arm.md
  articles/virtual-network/virtual-network-ip-addresses-overview-arm.md
Labels: Accepted, Linguistic Suggestion

#468 Update backup-azure-dpm-introduction.md
  articles/backup/backup-azure-dpm-introduction.md
Labels: Accepted, Linguistic Suggestion

#480 Fixed inappropriate headers
  articles/security/blueprints/payment-processing-blueprint.md
Labels: Accepted, Linguistic Suggestion
