Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-08, with the labels that each got.

#614 restore
  articles/data-factory/compute-linked-services.md
Labels: Accepted, Linguistic Suggestion

#616 restore
  articles/monitoring-and-diagnostics/monitoring-archive-diagnostic-logs.md
Labels: Linguistic Suggestion

#617 fix a translation for 'in'
  articles/active-directory/users-groups-roles/groups-dynamic-membership.md
Labels: Accepted, Linguistic Suggestion

#618 Update automation-first-runbook-graphical.md
  articles/automation/automation-first-runbook-graphical.md
Labels: Accepted, Linguistic Suggestion

#588 Fix typo
  articles/app-service/web-sites-php-configure.md
Labels: Accepted, Source Issue

#620 restore 'ナレッジ ベース'
  articles/cognitive-services/QnAMaker/How-To/collaborate-knowledge-base.md
  articles/cognitive-services/QnAMaker/Quickstarts/csharp.md
  articles/cognitive-services/QnAMaker/Quickstarts/go.md
  articles/cognitive-services/QnAMaker/Quickstarts/java.md
  articles/cognitive-services/QnAMaker/Quickstarts/nodejs.md
  articles/cognitive-services/QnAMaker/Quickstarts/python.md
Labels: Accepted, Linguistic Suggestion

#615 remove an unnecessary sentence
  articles/azure-functions/durable-functions-webjobs-sdk.md
  articles/cosmos-db/odbc-driver.md
Labels: Accepted, Source Issue

#621 suggest to improve the translation for 'blue/green deployment'
  articles/jenkins/jenkins-aks-blue-green-deployment.md
Labels: In Progress, Linguistic Suggestion

#630 suggest to improve the translation for 'IN'
  articles/app-service/app-service-managed-service-identity.md
Labels: Accepted, Linguistic Suggestion

#633 restore changes
  articles/cognitive-services/QnAMaker/Quickstarts/python.md
Labels: Accepted, Linguistic Suggestion

#631 delete sentences that don't exist in the original text
  articles/active-directory-b2c/active-directory-b2c-user-migration.md
  articles/active-directory/application-proxy-back-end-kerberos-constrained-delegation-how-to.md
  articles/active-directory/saas-apps/metanetworksconnector-tutorial.md
  articles/virtual-machines/workloads/sap/hana-overview-high-availability-disaster-recovery.md
Labels: Accepted, Source Issue

#632 fix translation of dots
  articles/logic-apps/logic-apps-workflow-definition-language.md
  articles/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance.md
  articles/service-bus-messaging/service-bus-amqp-protocol-guide.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#638 Fix mistranslation
  articles/cdn/cdn-purge-endpoint.md
Labels: Accepted, Linguistic Suggestion

#637 Fix mistranslation
  articles/cdn/cdn-features.md
Labels: Accepted, Linguistic Suggestion

#645 fixed typo
  articles/azure-functions/functions-develop-vs.md
Labels: Accepted, Linguistic Suggestion

#649 fix translations in 'prerequisites'
  articles/automation/automation-first-runbook-textual-python2.md
Labels: Accepted, Linguistic Suggestion

#648 fix around URL
  articles/active-directory/manage-apps/application-proxy-integrate-with-remote-desktop-services.md
Labels: Accepted, Linguistic Suggestion

#654 suggest to improve translation for 'capacity'
  articles/sql-database/sql-database-read-scale-out.md
Labels: Accepted, Linguistic Suggestion

#663 restore 'ブルー/グリーン'
  articles/jenkins/jenkins-aks-blue-green-deployment.md
Labels: Accepted, Linguistic Suggestion

#657 Fix mistranslation
  articles/media-services/previous/media-services-portal-live-passthrough-get-started.md
Labels: Accepted, Linguistic Suggestion

#652 delete 'が必要です。' that don't exist in the original text
  articles/active-directory/manage-apps/application-proxy-configure-hard-coded-link-translation.md
  articles/automation/automation-runbook-execution.md
  articles/azure-stack/azure-stack-backup-enable-backup-console.md
  articles/backup/tutorial-backup-vm-at-scale.md
  articles/iot-edge/how-to-develop-c-module.md
  articles/log-analytics/log-analytics-quick-collect-azurevm.md
  articles/machine-learning/team-data-science-process/cortana-analytics-technical-guide-predictive-maintenance.md
  articles/media-services/previous/media-services-rest-connect-with-aad.md
  articles/monitoring-and-diagnostics/monitor-quick-resource-metric-alert-portal.md
  articles/site-recovery/site-recovery-dynamicsax.md
Labels: Accepted, Technical Issue

#653 delete 'が必要です。' that don't exist in the original text, and …
  articles/api-management/get-started-create-service-instance.md
  articles/azure-functions/functions-powerapps-scenario.md
Labels: Accepted, Source Issue

#650 delete sentences that don't exist in the original text
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
  articles/storsimple/storsimple-disaster-recovery-using-azure-site-recovery.md
Labels: Accepted, Source Issue

#664 fix translation for 'Update'
  articles/active-directory/connect/active-directory-aadconnectsync-change-the-configuration.md
  articles/active-directory/connect/active-directory-aadconnectsync-feature-preferreddatalocation.md
Labels: Accepted, Linguistic Suggestion

#666 fix translation for 'Update'
  articles/storsimple/storsimple-update21-release-notes.md
  articles/storsimple/storsimple-update4-release-notes.md
Labels: Accepted, Linguistic Suggestion

#671 delete 'が必要です。' that doesn't exist in the original text
  articles/billing/billing-spending-limit.md
  articles/media-services/previous/media-services-portal-analyze.md
  articles/sql-database/saas-multitenantdb-schema-management.md
Labels: Accepted, Source Issue

#669 fix headings. not to translate. upper/lower-case.
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted, Linguistic Suggestion

#668 Update quick-create-portal.md
  articles/virtual-machines/linux/quick-create-portal.md
Labels: Accepted, Linguistic Suggestion

#675 Wrong Japanese translation.
  articles/virtual-network/manage-route-table.md
Labels: Accepted, Linguistic Suggestion

#673 Update sql-database-geo-replication-overview.md
  articles/sql-database/sql-database-geo-replication-overview.md
Labels: Accepted, Linguistic Suggestion

#678 Fix Punctuation
  articles/active-directory/authentication/concept-sspr-policy.md
Labels: Accepted, Source Issue
