Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-07, with the labels that each got.

#557 fix duplicate phrase
  articles/notification-hubs/notification-hubs-chrome-push-notifications-get-started.md
Labels: Accepted, Linguistic Suggestion

#556 fix sentences that are not translated
  articles/automation/automation-first-runbook-graphical.md
Labels: Accepted, Linguistic Suggestion

#562 remove bracket
  articles/storage/common/storage-decide-blobs-files-disks.md
Labels: Accepted, Linguistic Suggestion

#563 fix a typo
  articles/active-directory/develop/active-directory-v2-code-samples.md
Labels: Accepted, Linguistic Suggestion

#559 grammatical error
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#560 grammatical error
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#565 remove unnecessary sentences
  articles/active-directory/saas-apps/certainadminsso-tutorial.md
  articles/active-directory/saas-apps/elionboarding-tutorial.md
  articles/active-directory/saas-apps/insight4grc-tutorial.md
  articles/active-directory/saas-apps/pagerduty-tutorial.md
  articles/data-factory/quickstart-create-data-factory-copy-data-tool.md
  articles/data-factory/quickstart-create-data-factory-portal.md
  articles/data-factory/transform-data-using-databricks-notebook.md
  articles/data-factory/tutorial-bulk-copy-portal.md
  articles/data-factory/tutorial-copy-data-portal.md
  articles/data-factory/tutorial-copy-data-tool.md
  articles/data-factory/tutorial-deploy-ssis-packages-azure.md
  articles/data-factory/tutorial-hybrid-copy-data-tool.md
  articles/data-factory/tutorial-hybrid-copy-portal.md
  articles/data-factory/tutorial-hybrid-copy-powershell.md
  articles/data-factory/tutorial-incremental-copy-multiple-tables-portal.md
  articles/data-factory/tutorial-incremental-copy-multiple-tables-powershell.md
  articles/data-factory/tutorial-transform-data-spark-portal.md
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
  articles/log-analytics/log-analytics-tutorial-response.md
Labels: Accepted, Linguistic Suggestion

#571 remove unnecessary sentences
  articles/active-directory/saas-apps/amazon-web-service-tutorial.md
  articles/active-directory/saas-apps/ciscocloudlock-tutorial.md
  articles/active-directory/saas-apps/fluxxlabs-tutorial.md
  articles/active-directory/saas-apps/hightail-tutorial.md
  articles/active-directory/saas-apps/innovationhub-tutorial.md
  articles/active-directory/saas-apps/ipasssmartconnect-tutorial.md
  articles/active-directory/saas-apps/keeperpasswordmanager-tutorial.md
  articles/active-directory/saas-apps/leapsome-tutorial.md
  articles/active-directory/saas-apps/manabipocket-tutorial.md
  articles/active-directory/saas-apps/salesforce-provisioning-tutorial.md
  articles/active-directory/saas-apps/servicechannel-tutorial.md
  articles/app-service/webjobs-sdk-get-started.md
  articles/azure-stack/user/azure-stack-version-profiles-azurecli2.md
  articles/batch/batch-quota-limit.md
  articles/data-factory/connector-azure-sql-data-warehouse.md
  articles/data-factory/connector-azure-sql-database.md
  articles/data-factory/create-azure-ssis-integration-runtime.md
  articles/data-factory/how-to-configure-azure-ssis-ir-custom-setup.md
  articles/data-factory/join-azure-ssis-integration-runtime-virtual-network.md
  articles/data-factory/load-azure-sql-data-warehouse.md
  articles/data-factory/v1/data-factory-data-processing-using-batch.md
  articles/data-factory/v1/data-factory-spark.md
  articles/hdinsight/r-server/r-server-operationalize.md
  articles/machine-learning/data-science-virtual-machine/dsvm-common-identity.md
  articles/site-recovery/site-recovery-failover-to-azure-troubleshoot.md
  articles/storsimple/storsimple-configure-mpio-on-linux.md
  articles/virtual-machines/workloads/sap/hana-overview-high-availability-disaster-recovery.md
Labels: Accepted, Source Issue

#573 fix a translation for 'On'
  articles/iot-central/tutorial-configure-rules.md
Labels: Accepted, Linguistic Suggestion

#577 not to translate
  articles/api-management/api-management-howto-use-azure-monitor.md
  articles/automation/automation-dsc-diagnostics.md
  articles/automation/automation-manage-send-joblogs-log-analytics.md
  articles/automation/automation-solution-vm-management.md
  articles/data-lake-analytics/data-lake-analytics-diagnostic-logs.md
  articles/data-lake-store/data-lake-store-diagnostic-logs.md
  articles/event-hubs/event-hubs-diagnostic-logs.md
  articles/key-vault/key-vault-logging.md
  articles/machine-learning/studio/custom-r-modules.md
  articles/monitoring-and-diagnostics/monitoring-activity-log-alerts-webhook.md
  articles/monitoring-and-diagnostics/monitoring-archive-activity-log.md
  articles/monitoring-and-diagnostics/monitoring-archive-diagnostic-logs.md
  articles/monitoring-and-diagnostics/monitoring-service-notifications.md
  articles/monitoring-and-diagnostics/monitoring-stream-diagnostic-logs-to-event-hubs.md
  articles/monitoring/monitoring-solution-agenthealth.md
  articles/monitoring/monitoring-solutions-resources-searches-alerts.md
  articles/monitoring/monitoring-solutions-solution-file.md
  articles/network-watcher/network-watcher-nsg-flow-logging-overview.md
  articles/search/search-monitor-usage.md
  articles/service-bus-messaging/service-bus-diagnostic-logs.md
  articles/stream-analytics/stream-analytics-job-diagnostic-logs.md
Labels: Accepted, Linguistic Suggestion

#585 Fix typo
  articles/storage/common/storage-redundancy.md
Labels: Accepted, Linguistic Suggestion

#586 restore changes
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#578 improve translation for 'knowledge base'
  articles/cognitive-services/QnAMaker/Concepts/best-practices.md
  articles/cognitive-services/QnAMaker/How-To/create-knowledge-base.md
  articles/cognitive-services/QnAMaker/Quickstarts/csharp.md
  articles/cognitive-services/QnAMaker/Quickstarts/go.md
  articles/cognitive-services/QnAMaker/Quickstarts/java.md
  articles/cognitive-services/QnAMaker/Quickstarts/nodejs.md
  articles/cognitive-services/QnAMaker/Quickstarts/python.md
  articles/cognitive-services/QnAMaker/Tutorials/migrate-knowledge-base.md
Labels: In Progress, Linguistic Suggestion

#589 fix the Japanese translation
  articles/cosmos-db/TOC.experimental.yml
  articles/cosmos-db/TOC.yml
Labels: Accepted, Linguistic Suggestion

#592 Update sql-database-metrics-diag-logging.md
  articles/sql-database/sql-database-metrics-diag-logging.md
Labels: Accepted, Linguistic Suggestion

#597 remove unnecessary sentences
  includes/site-recovery-prepare-push-install-mob-svc-lin.md
  includes/site-recovery-prepare-push-install-mob-svc-win.md
Labels: Accepted, Linguistic Suggestion

#593 suggest to improve translation for 'in'
  articles/active-directory/users-groups-roles/directory-assign-admin-roles.md
Labels: Accepted, Linguistic Suggestion

#596 restore a change
  articles/sql-database/sql-database-metrics-diag-logging.md
Labels: Accepted, Linguistic Suggestion

#598 restore Rupee symbol
  articles/site-recovery/hyper-v-deployment-planner-cost-estimation.md
Labels: Accepted, Linguistic Suggestion

#603 not to translate parameter names
  articles/data-lake-analytics/data-lake-analytics-cicd-overview.md
Labels: Accepted, Linguistic Suggestion

#601 Fix typo
  articles/active-directory/develop/active-directory-devquickstarts-openidconnect-nodejs.md
Labels: Accepted, Source Issue

#602 Cosmetic change
  articles/active-directory/develop/active-directory-devquickstarts-openidconnect-nodejs.md
Labels: Accepted, Source Issue

#605 restore changes
  articles/data-factory/compute-linked-services.md
Labels: Accepted, Linguistic Suggestion

#606 fix property name
  articles/event-grid/event-schema.md
Labels: Accepted, Linguistic Suggestion

#607 restore a change
  articles/sql-database/sql-database-metrics-diag-logging.md
Labels: Accepted, Linguistic Suggestion

#608 restore changes
  articles/active-directory/active-directory-named-locations.md
Labels: Accepted, Source Issue

#611 Fix typo
  articles/cdn/cdn-create-new-endpoint.md
Labels: Accepted, Linguistic Suggestion

#612 revert a change
  articles/data-factory/compute-linked-services.md
Labels: Accepted, Linguistic Suggestion
