Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2018-10, with the labels that each got.

#746 Improve translation
  articles/media-services/previous/media-services-dotnet-get-started.md
Labels: Accepted, Linguistic Suggestion

#739 Updated Japanese Durable Functions overview to common Japanese expression.
  articles/azure-functions/durable-functions-overview.md
Labels: Accepted, Linguistic Suggestion

#740 Fix grammar
  articles/cognitive-services/Academic-Knowledge/Home.md
  articles/cognitive-services/Content-Moderator/moderation-reviews-quickstart-dotnet.md
  articles/cognitive-services/Content-Moderator/term-lists-quickstart-dotnet.md
  articles/cognitive-services/Content-Moderator/video-reviews-quickstart-dotnet.md
  articles/cognitive-services/Content-Moderator/video-transcript-moderation-review-tutorial-dotnet.md
  articles/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-subscribe.md
  articles/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-use-endpoint.md
  articles/cognitive-services/Custom-Speech-Service/cognitive-services-custom-speech-get-started.md
  articles/cognitive-services/Translator/tutorial-wpf-translation-csharp.md
  articles/iot-edge/quickstart-linux.md
  articles/iot-edge/quickstart.md
  articles/iot-hub/iot-hub-create-through-portal.md
  articles/iot-hub/iot-hub-devguide-quotas-throttling.md
  articles/security-center/security-center-identity-access.md
Labels: Accepted, Linguistic Suggestion

#743 Fix Punctuation
  articles/app-service/azure-sdk-dotnet-release-notes-3-0.md
Labels: Accepted, Linguistic Suggestion

#742 suggest to improve translations for 'Column'
  articles/active-directory/authentication/howto-sspr-reporting.md
  articles/analysis-services/tutorials/aas-lesson-2-Get-data.md
  articles/analysis-services/tutorials/aas-lesson-6-create-measures.md
  articles/analysis-services/tutorials/aas-supplemental-lesson-ragged-hierarchies.md
  articles/azure-stack/partner/azure-stack-vaas-monitor-test.md
  articles/log-analytics/log-analytics-solution-alert-management.md
  articles/machine-learning/desktop-workbench/data-prep-combine-columns-by-example.md
  articles/machine-learning/desktop-workbench/data-prep-derive-column-by-example.md
  articles/machine-learning/team-data-science-process/cortana-analytics-playbook-vehicle-telemetry-deep-dive.md
  articles/monitoring-and-diagnostics/monitoring-overview-alerts.md
  articles/monitoring-and-diagnostics/monitoring-overview-unified-alerts.md
  articles/monitoring/monitoring-container-insights-analyze.md
  articles/monitoring/monitoring-solution-agenthealth.md
  articles/monitoring/monitoring-solution-office-365.md
  articles/monitoring/monitoring-vminsights-health.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-index.md
  articles/stream-analytics/stream-analytics-build-an-iot-solution-using-stream-analytics.md
Labels: Accepted, Linguistic Suggestion

#745 Fix typo
  articles/time-series-insights/tutorial-create-populate-tsi-environment.md
Labels: Accepted, Linguistic Suggestion

#747 Fix maximum number of KB for Basic tier (ja-JP)
  articles/cognitive-services/QnAMaker/Tutorials/choosing-capacity-qnamaker-deployment.md
Labels: Accepted, Linguistic Suggestion

#748 Fix mistranslation
  articles/cognitive-services/Custom-Vision-Service/home.md
Labels: Accepted, Linguistic Suggestion

#751 Fix grammar
  includes/azure-mediaservices-limits.md
Labels: Accepted, Linguistic Suggestion

#753 Fix some translation problems
  articles/cognitive-services/Custom-Vision-Service/glossary-of-terms.md
Labels: Accepted, Linguistic Suggestion

#755 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/toc.yml
Labels: Accepted, Linguistic Suggestion

#759 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/getting-started-improving-your-classifier.md
Labels: Accepted, Linguistic Suggestion

#758 fix 'JavaScript を選択した場合' -> 'JavaScript' …
  articles/active-directory/managed-identities-azure-resources/services-support-msi.md
  articles/api-management/api-management-api-templates.md
  articles/application-insights/app-insights-api-custom-events-metrics.md
  articles/application-insights/app-insights-release-notes.md
  articles/application-insights/distributed-tracing.md
  articles/azure-functions/durable-functions-diagnostics.md
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
  articles/azure-functions/functions-bindings-cosmosdb.md
  articles/azure-functions/functions-bindings-event-hubs.md
  articles/azure-functions/functions-bindings-microsoft-graph.md
  articles/azure-functions/functions-bindings-mobile-apps.md
  articles/azure-functions/functions-bindings-storage-queue.md
  articles/azure-functions/supported-languages.md
  articles/azure-signalr/index.yml
  articles/cognitive-services/Bing-Autosuggest/toc.yml
  articles/cognitive-services/Bing-Custom-Search/toc.yml
  articles/cognitive-services/Bing-News-Search/toc.yml
  articles/cognitive-services/Bing-Spell-Check/toc.yml
  articles/cognitive-services/Bing-Web-Search/toc.yml
  articles/cognitive-services/Computer-vision/toc.yml
  articles/cognitive-services/LUIS/luis-csharp-tutorial-build-bot-framework-sample.md
  articles/cognitive-services/LUIS/toc.yml
  articles/cognitive-services/QnAMaker/toc.yml
  articles/cognitive-services/Speech-Service/toc.yml
  articles/cognitive-services/Translator/toc.yml
  articles/cognitive-services/text-analytics/toc.yml
  articles/cosmos-db/index.yml
  articles/iot-dps/toc.yml
  articles/iot-edge/TOC.yml
  articles/service-bus-messaging/service-bus-amqp-overview.md
  articles/sql-database/sql-database-libraries.md
Labels: Accepted, Linguistic Suggestion

#763 Delete unnecessary space
  articles/azure-functions/durable-functions-overview.md
Labels: Accepted, Linguistic Suggestion

#764 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/test-your-model.md
Labels: Accepted, Linguistic Suggestion

#765 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/use-prediction-api.md
Labels: Accepted, Linguistic Suggestion

#766 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/rest-api-tutorial.md
Labels: Accepted, Linguistic Suggestion

#767 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial.md
Labels: Accepted, Linguistic Suggestion

#769 fix translations for 'Action'
  articles/role-based-access-control/resource-provider-operations.md
Labels: Accepted, Linguistic Suggestion

#770 suggest to improve translations
  articles/cognitive-services/Translator/language-support.md
Labels: Accepted, Linguistic Suggestion

#778 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/getting-started-build-a-classifier.md
Labels: Accepted, Linguistic Suggestion

#777 Fix nonunified
  articles/machine-learning/studio/text-analytics-module-tutorial.md
Labels: Accepted, Linguistic Suggestion

#786 Delete unnecessary characters
  articles/cdn/cdn-rules-engine-reference-features.md
Labels: Accepted, Linguistic Suggestion

#785 Fix nonunified
  articles/machine-learning/studio/azure-ml-customer-churn-scenario.md
Labels: Accepted, Linguistic Suggestion

#781 Fix nonunified
  articles/machine-learning/desktop-workbench/how-to-build-deploy-image-classification-models.md
Labels: Accepted, Linguistic Suggestion

#782 Fix nonunified
  articles/cognitive-services/Custom-Vision-Service/home.md
Labels: Accepted, Linguistic Suggestion

#791 Fix nonunified
  articles/machine-learning/desktop-workbench/how-to-build-deploy-image-similarity-models.md
Labels: Accepted, Linguistic Suggestion

#789 Fix table format
  includes/virtual-machines-common-premium-storage.md
Labels: Accepted, Source Issue

#805 Improve translation
  articles/redis-cache/cache-redis-samples.md
Labels: Accepted, Linguistic Suggestion

#804 Fix nonunified
  articles/cosmos-db/table-storage-how-to-use-ruby.md
Labels: Accepted, Linguistic Suggestion

#803 Fix nonunified
  articles/devops-project/toc.yml
Labels: Accepted, Linguistic Suggestion

#806 remove duplicate text
  articles/machine-learning/desktop-workbench/scenario-image-classification-using-cntk.md
Labels: Accepted, Linguistic Suggestion

#810 fix 'C# を選択した場合' -> 'C#'
  articles/azure-functions/functions-bindings-event-grid.md
  articles/azure-functions/functions-bindings-http-webhook.md
  articles/azure-functions/functions-bindings-storage-blob.md
  articles/azure-functions/functions-bindings-timer.md
  articles/azure-functions/functions-triggers-bindings.md
  articles/cognitive-services/Translator/ctf-reporting.md
  articles/cognitive-services/Translator/return-n-best-translations.md
  articles/virtual-machines/linux/instance-metadata-service.md
  articles/virtual-machines/windows/instance-metadata-service.md
  includes/functions-folder-structure.md
  includes/functions-supported-languages.md
Labels: Accepted, Linguistic Suggestion

#817 suggest to fix 'State'
  articles/databox/data-box-security.md
Labels: Accepted, Linguistic Suggestion

#815 Fix typo
  articles/virtual-network/virtual-network-service-endpoint-policies-overview.md
Labels: Accepted, Linguistic Suggestion

#827 Fix typo
  articles/storage/common/storage-redundancy.md
Labels: Accepted, Technical Issue

#825 Fix typo
  articles/hdinsight/storm/apache-storm-overview.md
Labels: Accepted, Technical Issue

#812 Fix nonunified
  articles/azure-functions/TOC.yml
Labels: Accepted, Linguistic Suggestion

#801 Fix nonunified
  articles/azure-stack/azure-stack-app-service-overview.md
Labels: Accepted, Linguistic Suggestion

#796 Improve translation
  articles/active-directory/b2b/b2b-tutorial-bulk-invite.md
Labels: Accepted, Linguistic Suggestion

#808 Delete unnecessary character
  articles/service-fabric/toc.yml
Labels: Accepted, Linguistic Suggestion

#824 Fix typo & translate
  articles/hdinsight/hadoop/apache-hadoop-develop-deploy-java-mapreduce-linux.md
Labels: Accepted, Linguistic Suggestion

#802 Improve translation
  articles/sql-database/sql-database-geo-replication-overview.md
Labels: In Progress, Linguistic Suggestion

#813 Fix: Typo
  articles/machine-learning/service/concept-azure-machine-learning-architecture.md
Labels: Accepted, Linguistic Suggestion

#830 Improve translate
  articles/redis-cache/cache-web-app-cache-aside-leaderboard.md
Labels: Accepted, Linguistic Suggestion

#840 Improve translation
  articles/terraform/toc.yml
Labels: Accepted, Linguistic Suggestion

#837 Improve translation
  articles/app-service/app-service-web-ssl-cert-load.md
  articles/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-migrate-tiers.md
  articles/expressroute/expressroute-howto-circuit-portal-resource-manager.md
  articles/hdinsight/hdinsight-use-external-metadata-stores.md
  articles/redis-cache/cache-configure.md
Labels: Accepted, Linguistic Suggestion

#844 Fix nonunified
  articles/service-fabric-mesh/TOC.yml
Labels: Accepted, Linguistic Suggestion

#846 Fix typo
  articles/redis-cache/TOC.yml
Labels: Accepted, Linguistic Suggestion

#839 Improve translation
  articles/terraform/index.yml
Labels: Accepted, Linguistic Suggestion

#848 Fix typo
  articles/service-fabric-mesh/index.yml
Labels: Accepted, Linguistic Suggestion

#845 Fix typo
  articles/machine-learning/service/how-to-secure-web-service.md
Labels: Accepted, Linguistic Suggestion

#854 restore 'Degree' and 'i'
  articles/cognitive-services/Bing-Web-Search/search-responses.md
Labels: Accepted, Linguistic Suggestion

#862 Fix typo
  articles/service-fabric-mesh/service-fabric-mesh-overview.md
Labels: Accepted, Linguistic Suggestion

#861 Fix typo
  articles/storage/index.yml
Labels: Accepted, Linguistic Suggestion
