Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-04, with the labels that each got.

#2241 Fix mistranslation
  articles/api-management/api-management-api-templates.md
Labels: Accepted, Linguistic Suggestion

#2280 Delete unnecessary brackets
  articles/analysis-services/analysis-services-async-refresh.md
Labels: Accepted, Linguistic Suggestion

#2281 Delete unnecessary brackets
  articles/api-management/api-management-page-controls.md
Labels: Accepted, Linguistic Suggestion

#2283 Delete unnecessary brackets
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, Linguistic Suggestion

#2284 Delete unnecessary brackets
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted, Linguistic Suggestion

#2285 Delete unnecessary brackets
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, Linguistic Suggestion

#2286 Delete unnecessary brackets
  articles/automation/automation-tutorial-troubleshoot-changes.md
Labels: Accepted, Linguistic Suggestion

#2282 Delete unnecessary brackets
  articles/automation/automation-change-tracking.md
Labels: Accepted, Linguistic Suggestion

#2287 Delete unnecessary brackets
  articles/automation/automation-update-management.md
Labels: Accepted, Linguistic Suggestion

#2288 Delete unnecessary brackets
  articles/automation/automation-vm-inventory.md
Labels: Accepted, Linguistic Suggestion

#2290 Delete unnecessary brackets
  articles/automation/migrate-oms-update-deployments.md
Labels: Accepted, Linguistic Suggestion

#2289 Delete unnecessary brackets
  articles/automation/automation-webhooks.md
Labels: Accepted, Linguistic Suggestion

#2291 Delete unnecessary brackets
  articles/azure-databricks/databricks-extract-load-sql-data-warehouse.md
Labels: Accepted, Linguistic Suggestion

#2293 Delete unnecessary brackets
  articles/azure-databricks/databricks-stream-from-eventhubs.md
Labels: Accepted, Linguistic Suggestion

#2294 Delete unnecessary brackets
  articles/azure-databricks/quickstart-create-databricks-workspace-portal.md
Labels: Accepted, Linguistic Suggestion

#2295 Delete unnecessary brackets
  articles/azure-monitor/app/opencensus-go.md
Labels: Accepted, Linguistic Suggestion

#2296 Delete unnecessary brackets
  articles/azure-monitor/app/opencensus-python.md
Labels: Accepted, Linguistic Suggestion

#2297 Delete unnecessary brackets
  articles/azure-monitor/app/website-monitoring.md
Labels: Accepted, Linguistic Suggestion

#2299 Delete unnecessary brackets
  articles/azure-monitor/learn/java-quick-start.md
Labels: Accepted, Linguistic Suggestion

#2298 Delete unnecessary brackets
  articles/azure-monitor/learn/dotnetcore-quick-start.md
Labels: Accepted, Linguistic Suggestion

#2300 Delete unnecessary brackets
  articles/azure-monitor/learn/mobile-center-quickstart.md
Labels: Accepted, Linguistic Suggestion

#2301 Delete unnecessary brackets
  articles/azure-monitor/learn/nodejs-quick-start.md
Labels: Accepted, Linguistic Suggestion

#2302 Delete unnecessary brackets
  articles/azure-monitor/platform/computer-groups.md
Labels: Accepted, Linguistic Suggestion

#2304 Delete unnecessary brackets
  articles/azure-stack/azure-stack-registration.md
Labels: Accepted, Linguistic Suggestion

#2303 Delete unnecessary brackets
  articles/azure-monitor/platform/data-sources-custom-logs.md
Labels: Accepted, Linguistic Suggestion

#2305 Delete unnecessary brackets
  articles/blockchain/workbench/database-views.md
Labels: Accepted, Linguistic Suggestion

#2306 Delete unnecessary brackets
  articles/cdn/cdn-http-debug-headers.md
Labels: Accepted, Linguistic Suggestion

#2307 Delete unnecessary brackets
  articles/cdn/cdn-rules-engine-reference.md
Labels: Accepted, Linguistic Suggestion

#2308 Delete unnecessary brackets
  articles/cdn/cdn-token-auth.md
Labels: Accepted, Linguistic Suggestion

#2332 Delete unnecessary brackets
  articles/security/azure-security.md
Labels: Accepted, Linguistic Suggestion

#2331 Delete unnecessary brackets
  articles/storage/blobs/storage-blob-soft-delete.md
Labels: Accepted, Linguistic Suggestion

#2330 Delete unnecessary brackets
  articles/storage/blobs/data-lake-storage-use-databricks-spark.md
Labels: Accepted, Linguistic Suggestion

#2329 Delete unnecessary brackets
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Linguistic Suggestion

#2328 Delete unnecessary brackets
  articles/service-fabric/service-fabric-reliable-serviceremoting-diagnostics.md
Labels: Accepted, Linguistic Suggestion

#2327 Delete unnecessary brackets
  articles/network-watcher/network-watcher-connectivity-overview.md
Labels: Accepted, Linguistic Suggestion

#2326 Delete unnecessary brackets
  articles/logic-apps/tutorial-process-mailing-list-subscriptions-workflow.md
Labels: Accepted, Linguistic Suggestion

#2325 Delete unnecessary brackets
  articles/logic-apps/tutorial-process-email-attachments-workflow.md
Labels: Accepted, Linguistic Suggestion

#2324 Delete unnecessary brackets
  articles/logic-apps/tutorial-build-schedule-recurring-logic-app-workflow.md
Labels: Accepted, Linguistic Suggestion

#2323 Delete unnecessary brackets
  articles/logic-apps/quickstart-create-first-logic-app-workflow.md
Labels: Accepted, Linguistic Suggestion

#2322 Delete unnecessary brackets
  articles/logic-apps/logic-apps-gateway-connection.md
Labels: Accepted, Linguistic Suggestion

#2321 Delete unnecessary brackets
  articles/logic-apps/logic-apps-enterprise-integration-x12.md
Labels: Accepted, Linguistic Suggestion

#2320 Delete unnecessary brackets
  articles/logic-apps/logic-apps-enterprise-integration-liquid-transform.md
Labels: Accepted, Linguistic Suggestion

#2319 Delete unnecessary brackets
  articles/logic-apps/logic-apps-enterprise-integration-edifact.md
Labels: Accepted, Linguistic Suggestion

#2317 Delete unnecessary brackets
  articles/logic-apps/logic-apps-enterprise-integration-certificates.md
Labels: Accepted, Linguistic Suggestion

#2316 Delete unnecessary brackets
  articles/logic-apps/logic-apps-enterprise-integration-as2.md
Labels: Accepted, Linguistic Suggestion

#2315 Delete unnecessary brackets
  articles/logic-apps/logic-apps-create-logic-apps-from-templates.md
Labels: Accepted, Linguistic Suggestion

#2314 Delete unnecessary brackets
  articles/logic-apps/logic-apps-control-flow-run-steps-group-scopes.md
Labels: Accepted, Linguistic Suggestion

#2313 Delete unnecessary brackets
  articles/logic-apps/logic-apps-control-flow-loops.md
Labels: Accepted, Linguistic Suggestion

#2312 Delete unnecessary brackets
  articles/iot-hub/iot-hub-devguide-messages-read-custom.md
Labels: Accepted, Linguistic Suggestion

#2311 Delete unnecessary brackets
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted, Linguistic Suggestion

#2310 Delete unnecessary brackets
  articles/connectors/connectors-native-query.md
Labels: Accepted, Linguistic Suggestion

#2309 Delete unnecessary brackets
  articles/connectors/connectors-native-delay.md
Labels: Accepted, Linguistic Suggestion

#2244 Fix mistranslation
  articles/api-management/api-management-application-templates.md
Labels: Accepted, Linguistic Suggestion

#2247 Delete unnecessary brackets
  articles/api-management/api-management-page-templates.md
Labels: Accepted, Linguistic Suggestion

#2335 found typo "ますも"
  articles/frontdoor/front-door-overview.md
Labels: Accepted, Linguistic Suggestion

#2337 Delete unnecessary brackets
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted, Linguistic Suggestion

#2338 Fix typo
  articles/site-recovery/azure-vm-disaster-recovery-with-expressroute.md
Labels: Accepted, Linguistic Suggestion

#2339 Remove unnecessary blankets
  articles/virtual-machines/extensions/agent-windows.md
Labels: Accepted, Linguistic Suggestion

#2336 Delete unnecessary brackets
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-autoscale-portal.md
Labels: In Progress

#2253 Fix mistranslation
  articles/api-management/api-management-user-profile-templates.md
Labels: Accepted, Linguistic Suggestion

#2256 Update quickstart.md
  articles/cloud-shell/quickstart.md
Labels: Accepted, Linguistic Suggestion

#2257 Update updated-for-az.md
  includes/updated-for-az.md
Labels: Linguistic Suggestion, Product Feedback

#2258 Update quickstart-powershell.md
  articles/cloud-shell/quickstart-powershell.md
Labels: In Progress, Linguistic Suggestion

#2334 table-import.mdのmarkdownの書き方が間違っている箇所を修正
  articles/cosmos-db/table-import.md
Labels: In Progress, Source Issue

#2261 Delete unnecessary brackets
  includes/active-directory-develop-guidedsetup-aspnetwebapp-test.md
Labels: Accepted, Linguistic Suggestion

#2263 Delete unnecessary brackets
  articles/virtual-machines/windows/sqlclassic/virtual-machines-windows-classic-sql-onprem-availability.md
Labels: Accepted, Linguistic Suggestion

#2268 Delete unnecessary brackets
  articles/storsimple/storsimple-8000-battery-replacement.md
Labels: In Progress, Linguistic Suggestion

#2269 Delete unnecessary brackets
  articles/storage/files/storage-sync-files-extend-servers.md
Labels: In Progress, Linguistic Suggestion

#2381 Fix typo
  articles/machine-learning/service/reference-azure-machine-learning-cli.md
Labels: Accepted, In Progress

#2364 Fix typo
  articles/cognitive-services/QnAMaker/How-To/improve-knowledge-base.md
Labels: Accepted, In Progress

#2362 Fix typo
  articles/cognitive-services/LUIS/luis-boundaries.md
Labels: Accepted, In Progress

#2371 Fix typo
  articles/governance/blueprints/tutorials/protect-new-resources.md
Labels: Accepted, In Progress

#2359 Fix typo
  articles/cognitive-services/Custom-Vision-Service/includes/get-keys.md
Labels: Accepted, In Progress

#2367 Fix typo
  articles/digital-twins/security-role-based-access-control.md
Labels: Accepted, In Progress

#2365 Fix typo
  articles/cosmos-db/logging.md
Labels: Accepted, In Progress

#2352 Fix typo
  articles/azure-monitor/log-query/get-started-portal.md
Labels: Accepted, In Progress

#2350 Fix typo
  articles/azure-monitor/app/proactive-arm-config.md
Labels: Accepted, In Progress

#2348 Fix typo
  articles/azure-monitor/app/alerts.md
Labels: Accepted, In Progress

#2380 Fix typo
  articles/machine-learning/service/how-to-set-up-training-targets.md
Labels: Accepted, In Progress

#2374 Fix typo
  articles/iot-dps/quick-enroll-device-x509-python.md
Labels: Accepted, In Progress

#2372 Fix typo
  articles/governance/policy/tutorials/create-and-manage.md
Labels: Accepted, In Progress

#2353 Fix typo
  articles/azure-monitor/log-query/log-search-transition.md
Labels: Accepted, In Progress

#2349 Fix typo
  articles/azure-monitor/app/monitor-web-app-availability.md
Labels: Accepted, In Progress

#2378 Fix display error
  articles/machine-learning/service/how-to-configure-environment.md
Labels: Accepted, In Progress

#2347 Fix typo
  articles/active-directory-b2c/json-transformations.md
Labels: Accepted, In Progress

#2375 Fix typo
  articles/iot-hub/iot-hub-devguide-glossary.md
Labels: Accepted, In Progress

#2360 Fix typo
  articles/cognitive-services/Custom-Vision-Service/use-prediction-api.md
Labels: Accepted, In Progress

#2357 Fix typo
  articles/cognitive-services/Custom-Vision-Service/export-your-model.md
Labels: Accepted, In Progress

#2351 Fix typo
  articles/azure-monitor/app/proactive-email-notification.md
Labels: Accepted, In Progress

#2376 Fix typo
  articles/iot-hub/iot-hub-device-streams-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2370 Fix typo
  articles/governance/blueprints/tutorials/create-from-sample.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2366 Fix typo
  articles/data-factory/control-flow-for-each-activity.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2361 Fix typo
  articles/cognitive-services/LUIS/get-started-portal-build-app.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2354 Fix typo
  articles/azure-monitor/log-query/smart-analytics.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2368 Fix typo
  articles/frontdoor/front-door-troubleshoot-routing.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2377 Fix typo
  articles/load-balancer/load-balancer-custom-probe-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2369 Fix typo
  articles/governance/blueprints/create-blueprint-portal.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2373 Fix typo
  articles/hdinsight/apache-kafka-spark-structured-streaming-cosmosdb.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2358 Fix typo
  articles/cognitive-services/Custom-Vision-Service/getting-started-build-a-classifier.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2355 Fix typo
  articles/azure-monitor/terminology.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2363 Fix typo
  articles/cognitive-services/LUIS/luis-how-to-azure-subscription.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2356 Fix typo
  articles/cognitive-services/Computer-vision/computer-vision-how-to-install-containers.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2346 Translation
  articles/cognitive-services/Bing-Image-Search/bing-image-search-resource-faq.md
Labels: Accepted, Linguistic Suggestion

#2344 Delete unnecessary brackets
  articles/connectors/connectors-native-query.md
Labels: Accepted, Linguistic Suggestion

#2343 Delete unnecessary brackets
  articles/connectors/connectors-native-delay.md
Labels: In Progress

#2272 Fix Republic of Korea
  articles/azure-maps/render-coverage.md
Labels: Accepted, Linguistic Suggestion

#2273 Update using-the-shell-window.md
  articles/cloud-shell/using-the-shell-window.md
Labels: Accepted, Linguistic Suggestion

#2274 Update cloud-shell-copy-paste.md
  includes/cloud-shell-copy-paste.md
Labels: Accepted, Linguistic Suggestion

#2275 Update msi-authorization.md
  articles/cloud-shell/msi-authorization.md
Labels: Accepted, Linguistic Suggestion

#2276 Update embed-cloud-shell.md
  articles/cloud-shell/embed-cloud-shell.md
Labels: Accepted, Linguistic Suggestion

#2277 Update azure-stack-considerations.md
  articles/azure-stack/user/azure-stack-considerations.md
Labels: Accepted, Linguistic Suggestion

#2399 Fix translation mistake
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, Linguistic Suggestion

#2401 Fix translation mistake
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, Linguistic Suggestion

#2398 Fix typo
  articles/virtual-machines/windows/tutorial-backup-vms.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2389 Fix typo
  articles/service-fabric/service-fabric-common-questions.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2387 Fix typo
  articles/search/cognitive-search-custom-skill-web-api.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2397 Fix typo
  articles/virtual-machines/windows/chef-automation.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2393 Fix typo
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2386 Fix typo
  articles/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2390 Fix typo
  articles/sql-database/saas-dbpertenant-restore-single-tenant.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2396 Fix typo
  articles/virtual-machines/troubleshooting/serial-console-grub-single-user-mode.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2395 Fix typo
  articles/virtual-machines/linux/update-infrastructure-redhat.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2394 Fix typo
  articles/virtual-machines/linux/serial-console-grub-single-user-mode.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2392 Fix typo
  articles/storsimple/storsimple-8000-manage-volumes-u2.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2391 Fix typo
  articles/sql-database/sql-database-metrics-diag-logging.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2388 Fix typo
  articles/service-fabric/service-fabric-cluster-resource-manager-cluster-description.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2385 Fix typo
  articles/machine-learning/studio/web-services-logging.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2384 Fix typo
  articles/machine-learning/studio/convert-training-experiment-to-scoring-experiment.md
Labels: Accepted, In Progress, Linguistic Suggestion

#2383 Delete unnecessary brackets
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted, In Progress

#2408 Delete unnecessary brackets
  articles/azure-monitor/insights/solution-office-365.md
Labels: In Progress

#2406 Delete unnecessary brackets
  articles/automation/automation-graphical-authoring-intro.md
Labels: In Progress

#2404 Fix mistake
  articles/storage/blobs/storage-lifecycle-management-concepts.md
Labels: Accepted, Linguistic Suggestion

#2405 Suggest to fix anchors section
  articles/cosmos-db/troubleshoot-dot-net-sdk.md
Labels: In Progress

#2249 Fix incorrect directory hierarchy
  articles/azure-signalr/signalr-quickstart-azure-functions-javascript.md
Labels: Accepted, Source Issue

#2430 Fix typo
  articles/data-factory/compute-linked-services.md
Labels: In Progress

#2422 Fix typo
  articles/azure-monitor/insights/solution-office-365.md
Labels: Accepted

#2425 Fix typo
  articles/cognitive-services/Computer-vision/Vision-API-How-to-Topics/HowToCallVisionAPI.md
Labels: In Progress

#2423 Delete unnecessary branckets
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: In Progress

#2424 Delete unnecessary branckets
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#2432 Delete unnecessary branckets
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted

#2433 Delete unnecessary branckets
  articles/azure-monitor/platform/alert-management-solution.md
Labels: Accepted

#2434 Delete unnecessary branckets
  articles/service-fabric/service-fabric-cloud-services-migration-worker-role-stateless-service.md
Labels: Accepted

#2426 Fix mistranslation
  articles/cognitive-services/LUIS/luis-reference-prebuilt-domains.md
Labels: In Progress

#2427 Fix mistranslation
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-entity-linking.md
Labels: Accepted

#2428 Fix mistranslation
  articles/cognitive-services/Translator/tutorial-wpf-translation-csharp.md
Labels: Accepted

#2429 Fix mistranslation
  articles/container-registry/container-registry-tasks-reference-yaml.md
Labels: Accepted

#2431 Fix mistranslation
  articles/data-factory/concepts-pipeline-execution-triggers.md
Labels: Accepted

#2435 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted

#2436 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted

#2437 Fix mistranslation
  articles/azure-monitor/insights/service-map.md
Labels: Accepted
