Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-12, with the labels that each got.

#2924 Fix a sentence in the restrictions section
  articles/app-service/app-service-web-app-cloning.md
Labels: Accepted, Linguistic Suggestion

#2927 Update service-fabric-reliable-services-reliable-collections-transact…
  articles/service-fabric/service-fabric-reliable-services-reliable-collections-transactions-locks.md
Labels: Accepted, Linguistic Suggestion

#2926 Fixed mistranslation
  includes/virtual-machines-oracle-applications-bastion.md
Labels: Accepted, Linguistic Suggestion

#2928 Update sql-database-managed-instance.md
  articles/sql-database/sql-database-managed-instance.md
Labels: Accepted, Linguistic Suggestion

#2925 Update security-overview.md
  articles/virtual-network/security-overview.md
Labels: In Progress, Linguistic Suggestion

#2930 Update traffic-manager-load-balancing-azure.md
  articles/traffic-manager/traffic-manager-load-balancing-azure.md
Labels: Accepted, Linguistic Suggestion

#2932 Improve translation
  articles/role-based-access-control/resource-provider-operations.md
Labels: Accepted, Linguistic Suggestion

#2931 Improve translation
  articles/bastion/bastion-overview.md
Labels: Accepted, Linguistic Suggestion

#2935 Improve translation
  articles/azure-monitor/platform/data-platform-logs.md
Labels: Accepted

#2937 Improve translation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted

#2939 Improve translation
  articles/machine-learning/data-science-virtual-machine/dsvm-tools-ingestion.md
Labels: Accepted

#2933 Improve translation
  includes/virtual-machines-oracle-applications-database.md
Labels: Accepted, Linguistic Suggestion

#2934 Improve translation
  articles/azure-functions/functions-infrastructure-as-code.md
Labels: Accepted, Linguistic Suggestion

#2938 Improve translation
  articles/hdinsight/hadoop/apache-hadoop-debug-jobs.md
Labels: Accepted, Linguistic Suggestion

#2942 Improve translation
  articles/security/develop/threat-modeling-tool-authorization.md
Labels: Accepted, Linguistic Suggestion

#2946 Improve translation
  articles/storage/queues/storage-dotnet-how-to-use-queues.md
Labels: Accepted

#2951 Fix emphasis
  articles/aks/support-policies.md
Labels: Accepted, Linguistic Suggestion

#2952 Fix emphasis
  articles/api-management/configure-custom-domain.md
Labels: Accepted, Linguistic Suggestion

#2949 Fix emphasis
  articles/active-directory/develop/msal-net-use-brokers-with-xamarin-apps.md
Labels: Accepted, Linguistic Suggestion

#2948 Fix emphasis
  articles/active-directory/develop/authorization-agents.md
Labels: Accepted, Linguistic Suggestion

#2950 Fix emphasis
  articles/active-directory/users-groups-roles/groups-troubleshooting.md
Labels: Accepted, Linguistic Suggestion

#2954 Update configuration-overview.md
  articles/application-gateway/configuration-overview.md
Labels: Accepted, Linguistic Suggestion

#2958 Improve translation
  articles/stream-analytics/stream-analytics-define-outputs.md
Labels: Accepted, Linguistic Suggestion

#2957 Improve translation
  articles/storage/tables/table-storage-design-modeling.md
Labels: Accepted, Linguistic Suggestion

#2956 Improve translation
  articles/storage/tables/table-storage-design-for-query.md
Labels: Accepted, Linguistic Suggestion

#2955 Improve translation
  articles/storage/tables/table-storage-design-for-modification.md
Labels: Accepted, Linguistic Suggestion

#2959 Improve translation
  articles/visual-studio/vs-storage-aspnet-getting-started-tables.md
Labels: Accepted, Linguistic Suggestion

#2970 Improve translation
  includes/iot-hub-get-started-extended.md
Labels: Accepted

#2962 '手順 3' > '3'
  articles/active-directory/authentication/howto-registration-mfa-sspr-combined-troubleshoot.md
  articles/active-directory/identity-protection/howto-identity-protection-risk-feedback.md
  articles/active-directory/manage-apps/application-proxy-troubleshoot.md
  articles/active-directory/saas-apps/workday-inbound-tutorial.md
  articles/aks/kubernetes-action.md
  articles/app-service/overview-authentication-authorization.md
  articles/asc-for-iot/concept-security-alerts.md
  articles/azure-monitor/platform/gateway.md
  articles/backup/backup-azure-alternate-dpm-server.md
  articles/backup/backup-azure-arm-vms-prepare.md
  articles/backup/backup-azure-delete-vault.md
  articles/backup/backup-azure-mabs-troubleshoot.md
  articles/batch/batch-technical-overview.md
  articles/cloudfoundry/how-cloud-foundry-integrates-with-azure.md
  articles/cognitive-services/QnAMaker/How-To/set-up-qnamaker-service-azure.md
  articles/cosmos-db/create-real-time-weather-dashboard-powerbi.md
  articles/databox-online/data-box-edge-deploy-prep.md
  articles/databox-online/data-box-gateway-deploy-prep.md
  articles/dms/known-issues-troubleshooting-dms.md
  articles/hdinsight/hdinsight-release-notes-archive.md
  articles/hdinsight/spark/apache-spark-zeppelin-notebook.md
  articles/machine-learning/team-data-science-process/move-sql-azure.md
  articles/machine-learning/team-data-science-process/move-sql-server-virtual-machine.md
  articles/marketplace/marketplace-criteria-content-validation.md
  articles/media-services/latest/migrate-from-v2-to-v3.md
  articles/migrate/tutorial-migrate-vmware.md
  articles/site-recovery/site-recovery-failover.md
  articles/site-recovery/vmware-physical-azure-troubleshoot-process-server.md
  articles/sql-data-warehouse/release-notes-10-0-10106-0.md
  articles/storsimple/storsimple-8000-aad-registration-key.md
  articles/storsimple/storsimple-8000-configure-web-proxy.md
  articles/storsimple/storsimple-8000-install-update-4.md
  articles/storsimple/storsimple-8000-install-update-5.md
  articles/storsimple/storsimple-8000-migrate-from-5000-7000.md
  articles/storsimple/storsimple-supported-hardware-for-10-gbe-network-interfaces.md
  articles/storsimple/storsimple-virtual-array-aad-registration-key.md
  articles/storsimple/storsimple-virtual-array-deploy1-portal-prep.md
  articles/virtual-machines/windows/sql/virtual-machines-windows-sql-high-availability-dr.md
  articles/virtual-network/public-ip-address-prefix.md
  articles/vpn-gateway/vpn-gateway-about-vpn-devices.md
Labels: Accepted

#2961 'name'
  articles/blockchain/service/data-manager-cli.md
  articles/blockchain/workbench/configuration.md
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#2960 update upgrade-and-scale.md
  articles/api-management/upgrade-and-scale.md
Labels: Accepted, Linguistic Suggestion

#2971 Improve translation
  includes/storage-table-cosmos-db-tip-include.md
Labels: Accepted, Linguistic Suggestion

#2953 Update expressroute-faqs.md
  articles/expressroute/expressroute-faqs.md
Labels: In Progress, Linguistic Suggestion

#2972 update api-management-sample-cache-by-key.md
  articles/api-management/api-management-sample-cache-by-key.md
Labels: In Progress

#2964 Fix emphasis
  articles/cognitive-services/LUIS/label-entity-example-utterance.md
Labels: Linguistic Suggestion, Partially Accepted

#2979 Update sentense 「Azure portal でサービス インスタンスをプロビジョニングする」
  articles/spring-cloud/spring-cloud-quickstart-launch-app-portal.md
Labels: Accepted, Linguistic Suggestion

#2980 Improve translation
  articles/azure-monitor/platform/metrics-supported.md
Labels: Accepted

#2982 Update private-endpoint-overview.md
  articles/private-link/private-endpoint-overview.md
Labels: Accepted, Linguistic Suggestion

#2984 Fix emphasis
  includes/vpn-gateway-cloud-shell-powershell-about.md
Labels: Accepted, Linguistic Suggestion

#2983 Fix emphasis
  includes/vpn-gateway-cloud-shell-powershell.md
Labels: Accepted, Linguistic Suggestion

#2986 Fix emphasis
  includes/aml-compute-target-deploy.md
Labels: Accepted, Linguistic Suggestion

#2985 Fix emphasis
  includes/iot-pnp-prepare-iot-hub-windows.md
Labels: Accepted, Linguistic Suggestion

#2987 Fix emphasis
  articles/virtual-machines/windows/sql/virtual-machines-windows-sql-server-iaas-faq.md
Labels: Accepted, Linguistic Suggestion

#2991 Update functions-develop-vs-code.md
  articles/azure-functions/functions-develop-vs-code.md
Labels: Accepted, Linguistic Suggestion

#2992 Azure Stream Analytics 詳細情報のリンク先が切れている (404 エラー)
  articles/storage/common/storage-network-security.md
Labels: Accepted

#2994 Fix emphasis
  articles/virtual-machines/linux/update-infrastructure-redhat.md
Labels: Accepted

#2988 'node'
  articles/app-service/app-service-best-practices.md
  articles/app-service/app-service-web-nodejs-best-practices-and-troubleshoot-guide.md
  articles/cognitive-services/Anomaly-Detector/quickstarts/detect-data-anomalies-nodejs-sdk.md
  articles/cognitive-services/Computer-vision/quickstarts-sdk/node-sdk.md
  articles/cognitive-services/Labs/Answer-Search/toc.yml
  articles/cognitive-services/Labs/URL-Preview/toc.yml
  articles/cognitive-services/QnAMaker/Quickstarts/create-publish-kb-nodejs-sdk.md
  articles/cognitive-services/text-analytics/includes/quickstarts/nodejs-sdk.md
  articles/iot-central/core/howto-administer.md
  articles/iot-central/preview/howto-administer.md
  articles/service-fabric/service-fabric-deploy-multiple-apps.md
Labels: In Progress, Linguistic Suggestion

#2989 fix emphasis, unify terms
  articles/iot-central/core/concepts-app-templates.md
Labels: Accepted, Linguistic Suggestion

#2990 fix emphasis
  articles/iot-pnp/overview-iot-plug-and-play.md
  articles/iot-pnp/quickstart-create-pnp-device-linux.md
Labels: Accepted, Linguistic Suggestion

#2997 Improve translation
  articles/search/search-howto-indexing-azure-tables.md
Labels: Accepted

#2996 Fix the command.
  articles/aks/ssh.md
Labels: Accepted
