Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-08, with the labels that each got.

#2714 不自然な文脈を修正
  articles/migrate/index.yml
Labels: Accepted, Linguistic Suggestion

#2716 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted

#2704 Suggest to improve translations for 'notice'
  articles/databox/data-box-heavy-safety.md
  articles/databox/data-box-safety.md
Labels: Accepted, Linguistic Suggestion

#2720 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted

#2721 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted

#2722 Fix mistranslation
  articles/application-gateway/overview.md
Labels: Accepted

#2723 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted

#2724 日本語の言い回しを修正
  articles/migrate/tutorial-assess-vmware.md
Labels: Accepted, Linguistic Suggestion

#2726 Update azure-to-azure-tutorial-enable-replication.md
  articles/site-recovery/azure-to-azure-tutorial-enable-replication.md
Labels: Accepted, Linguistic Suggestion

#2727 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted

#2730 Fix mistranslation
  articles/data-factory/connector-sybase.md
Labels: Accepted

#2732 Suggest to fix 'Name'
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted

#2731 Suggest to fix indicators
  articles/cognitive-services/cognitive-services-and-machine-learning.md
Labels: Accepted

#2738 Suggest to fix 'Name'
  articles/active-directory/saas-apps/academy-attendance-tutorial.md
  articles/active-directory/saas-apps/adpfederatedsso-tutorial.md
  articles/active-directory/saas-apps/airwatch-tutorial.md
  articles/active-directory/saas-apps/amazon-web-service-tutorial.md
  articles/active-directory/saas-apps/benchling-tutorial.md
  articles/active-directory/saas-apps/cisco-spark-tutorial.md
  articles/active-directory/saas-apps/cognidox-tutorial.md
  articles/active-directory/saas-apps/floqast-tutorial.md
  articles/active-directory/saas-apps/metanetworksconnector-tutorial.md
  articles/active-directory/saas-apps/nuclino-tutorial.md
  articles/active-directory/saas-apps/purecloud-by-genesys-tutorial.md
  articles/active-directory/saas-apps/robin-tutorial.md
  articles/active-directory/saas-apps/sd-elements-tutorial.md
  articles/active-directory/saas-apps/tableauserver-tutorial.md
  articles/active-directory/saas-apps/veracode-tutorial.md
  articles/active-directory/saas-apps/workpath-tutorial.md
  articles/active-directory/saas-apps/zscaler-one-tutorial.md
  articles/active-directory/saas-apps/zscaler-three-tutorial.md
  articles/active-directory/saas-apps/zscaler-tutorial.md
  articles/active-directory/saas-apps/zscaler-two-tutorial.md
  articles/active-directory/saas-apps/zscaler-zscloud-tutorial.md
Labels: Accepted

#2737 Suggest to fix 'Name'
  articles/application-gateway/application-gateway-ssl-policy-overview.md
  articles/azure-databricks/store-secrets-azure-key-vault.md
  articles/azure-monitor/app/data-model-metric-telemetry.md
  articles/billing/billing-understand-your-bill.md
  articles/media-services/latest/assets-concept.md
  articles/service-fabric/service-fabric-networking-modes.md
Labels: Accepted

#2735 Suggest to fix 'Name'
  articles/cognitive-services/Academic-Knowledge/AffiliationEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/AuthorEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/CalcHistogramMethod.md
  articles/cognitive-services/Academic-Knowledge/ConferenceInstanceEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/ConferenceSeriesEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/EntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/EvaluateMethod.md
  articles/cognitive-services/Academic-Knowledge/FieldsOfStudyEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/InterpretMethod.md
  articles/cognitive-services/Academic-Knowledge/JournalEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/PaperEntityAttributes.md
  articles/cognitive-services/Academic-Knowledge/SimilarityMethod.md
  articles/cognitive-services/Anomaly-Detector/anomaly-detector-container-configuration.md
  articles/cognitive-services/Anomaly-Detector/tutorials/anomaly-detection-streaming-databricks.md
  articles/cognitive-services/Computer-vision/computer-vision-resource-container-config.md
  articles/cognitive-services/Content-Moderator/java-sdk-quickstart.md
  articles/cognitive-services/Content-Moderator/python-sdk-quickstart.md
  articles/cognitive-services/Face/face-resource-container-config.md
  articles/cognitive-services/LUIS/get-started-portal-build-app.md
  articles/cognitive-services/LUIS/get-started-portal-deploy-app.md
  articles/cognitive-services/LUIS/luis-container-configuration.md
  articles/cognitive-services/Labs/Answer-Search/reference.md
  articles/cognitive-services/Labs/URL-Preview/endpoint.md
  articles/cognitive-services/Labs/URL-Preview/url-preview-reference.md
  articles/cognitive-services/Speech-Service/ship-application.md
  articles/cognitive-services/Speech-Service/speech-container-configuration.md
  articles/cognitive-services/Translator/ctf-reporting.md
  articles/cognitive-services/Translator/tutorial-wpf-translation-csharp.md
  articles/cognitive-services/bing-local-business-search/local-search-reference.md
  articles/cognitive-services/bing-visual-search/concepts/sending-queries.md
  articles/cognitive-services/form-recognizer/form-recognizer-container-configuration.md
  articles/cognitive-services/form-recognizer/quickstarts/dotnet-sdk.md
  articles/cognitive-services/immersive-reader/reference.md
  articles/cognitive-services/text-analytics/includes/create-text-analytics-resource.md
  articles/cognitive-services/text-analytics/text-analytics-resource-container-config.md
Labels: Accepted

#2734 Suggest to fix 'Name'
  articles/api-management/api-management-access-restriction-policies.md
  articles/api-management/api-management-authentication-policies.md
  articles/api-management/api-management-caching-policies.md
  articles/api-management/api-management-cross-domain-policies.md
  articles/api-management/api-management-howto-properties.md
  articles/api-management/api-management-policy-expressions.md
  articles/api-management/api-management-transformation-policies.md
Labels: Accepted

#2733 Suggest to fix 'Name'
  articles/active-directory-b2c/active-directory-b2c-reference-audit-logs.md
  articles/active-directory/conditional-access/technical-reference.md
  articles/active-directory/develop/active-directory-optional-claims.md
  articles/active-directory/develop/active-directory-saml-claims-customization.md
  articles/active-directory/develop/reference-saml-tokens.md
  articles/active-directory/develop/registration-config-specific-application-property-how-to.md
  articles/active-directory/governance/entitlement-management-access-package-first.md
  articles/active-directory/hybrid/concept-azure-ad-connect-sync-default-configuration.md
  articles/active-directory/hybrid/reference-connect-version-history.md
  articles/active-directory/identity-protection/howto-investigate-risky-users-signins.md
  articles/active-directory/manage-apps/functions-for-customizing-application-data.md
Labels: Accepted

#2728 minor updates
  articles/azure-monitor/insights/container-insights-overview.md
Labels: Accepted, Linguistic Suggestion

#2742 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted

#2745 Fix mistranslation
  articles/backup/tutorial-sql-backup.md
Labels: Accepted

#2741 Suggest to fix 'Name'
  articles/active-directory/saas-apps/betterworks-tutorial.md
  articles/active-directory/saas-apps/ciscocloud-tutorial.md
  articles/active-directory/saas-apps/dome9arc-tutorial.md
  articles/active-directory/saas-apps/ebsco-tutorial.md
  articles/active-directory/saas-apps/fulcrum-tutorial.md
  articles/active-directory/saas-apps/globalone-tutorial.md
  articles/active-directory/saas-apps/hightail-tutorial.md
  articles/active-directory/saas-apps/ilms-tutorial.md
  articles/active-directory/saas-apps/iqualify-tutorial.md
  articles/active-directory/saas-apps/learningpool-tutorial.md
  articles/active-directory/saas-apps/lessonly-tutorial.md
  articles/active-directory/saas-apps/linkedinelevate-tutorial.md
  articles/active-directory/saas-apps/mondaycom-tutorial.md
  articles/active-directory/saas-apps/moxtra-tutorial.md
  articles/active-directory/saas-apps/netsuite-tutorial.md
  articles/active-directory/saas-apps/onit-tutorial.md
  articles/active-directory/saas-apps/ontrack-tutorial.md
  articles/active-directory/saas-apps/opal-tutorial.md
  articles/active-directory/saas-apps/optimizely-tutorial.md
  articles/active-directory/saas-apps/policystat-tutorial.md
  articles/active-directory/saas-apps/timeoffmanager-tutorial.md
  articles/asc-for-iot/concept-recommendations.md
  articles/asc-for-iot/how-to-deploy-edge.md
  articles/azure-databricks/quickstart-create-databricks-workspace-vnet-injection.md
  articles/azure-resource-manager/resource-group-template-functions-array.md
  articles/azure-resource-manager/resource-group-template-functions-string.md
  articles/cognitive-services/QnAMaker/How-To/improve-knowledge-base.md
  articles/digital-twins/how-to-configure-postman.md
  articles/media-services/previous/media-services-build-smooth-streaming-apps.md
  articles/media-services/previous/media-services-castlabs-integration.md
  articles/media-services/previous/media-services-index-content.md
  articles/network-watcher/network-watcher-nsg-flow-logging-portal.md
  articles/search/index-add-custom-analyzers.md
  articles/service-fabric/service-fabric-service-model-schema-attribute-groups.md
  articles/service-fabric/service-fabric-service-model-schema-complex-types.md
  articles/service-fabric/service-fabric-service-model-schema-elements.md
  articles/storage/blobs/data-lake-storage-tutorial-extract-transform-load-hive.md
  articles/storage/common/storage-monitoring-diagnosing-troubleshooting.md
  includes/digital-twins-management-api.md
  includes/digital-twins-swagger.md
Labels: Accepted

#2743 typo fixed
  articles/active-directory/authentication/concept-mfa-howitworks.md
Labels: Accepted, Linguistic Suggestion

#2751 誤訳の修正
  articles/media-services/previous/media-services-portal-vod-get-started.md
Labels: Accepted, Linguistic Suggestion

#2750 誤訳の修正
  articles/media-services/latest/recommended-on-premises-live-encoders.md
Labels: Accepted, Linguistic Suggestion

#2753 誤訳の修正
  articles/media-services/previous/offline-playready-streaming-windows-10.md
Labels: Accepted, Linguistic Suggestion

#2752 誤訳の修正
  articles/media-services/latest/streaming-locators-concept.md
Labels: Accepted, Linguistic Suggestion

#2749 誤訳の修正
  articles/media-services/previous/media-services-recommended-encoders.md
Labels: Accepted, Linguistic Suggestion

#2748 誤訳の修正
  articles/media-services/latest/live-event-cloud-dvr.md
Labels: Accepted, Linguistic Suggestion

#2747 誤訳の修正
  articles/media-services/latest/upload-files-rest-how-to.md
Labels: Accepted, Linguistic Suggestion

#2746 誤訳の修正
  articles/media-services/latest/migrate-from-v2-to-v3.md
Labels: Accepted, Linguistic Suggestion

#2754 mistranslation fixed
  articles/virtual-machines/windows/dedicated-hosts.md
Labels: Accepted, Linguistic Suggestion

#2755 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#2756 誤訳の修正
  articles/media-services/latest/filters-dynamic-manifest-dotnet-howto.md
Labels: Accepted, Linguistic Suggestion

#2757 誤訳の修正
  articles/media-services/latest/stream-live-tutorial-with-api.md
Labels: Accepted, Linguistic Suggestion

#2758 誤訳の修正
  articles/active-directory/authentication/howto-mfa-userstates.md
Labels: Accepted, Linguistic Suggestion

#2759 Fix mistranslation
  articles/data-factory/monitor-integration-runtime.md
Labels: Accepted

#2740 日本語の言い回しを修正
  articles/media-services/latest/migrate-from-v2-to-v3.md
Labels: Accepted, Linguistic Suggestion

#2739 Suggets to fix emphasis
  articles/machine-learning/service/how-to-deploy-and-where.md
  articles/machine-learning/service/how-to-deploy-app-service.md
  articles/machine-learning/service/how-to-deploy-azure-container-instance.md
  articles/machine-learning/service/how-to-deploy-azure-kubernetes-service.md
  articles/machine-learning/service/how-to-deploy-custom-docker-image.md
  articles/machine-learning/service/how-to-enable-virtual-network.md
Labels: Accepted, Technical Issue

#2613 Update faq-configuration-and-management.md
  articles/app-service/faq-configuration-and-management.md
Labels: Accepted, Source Issue

#2648 Add the message "using English when customer post mepd@microsoft.com"
  articles/media-services/previous/media-services-workflow-designer.md
Labels: Accepted, Source Issue

#2764 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted

#2763 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, Linguistic Suggestion

#2765 名前があべこべ
  includes/cloud-shell-persisting-shell-storage-introblock.md
Labels: Accepted, Linguistic Suggestion

#2766 sysprepのパスがおかしかったのを修正
  articles/virtual-machines/windows/capture-image-resource.md
Labels: Accepted, Linguistic Suggestion

#2767 不要句読点削除
  includes/virtual-machines-common-states-lifecycle.md
Labels: Accepted, Linguistic Suggestion
