Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#2654 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#2655 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#2656 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#2657 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#2659 Fix mistransration
  articles/azure-functions/functions-twitter-email.md
Labels: Accepted, Linguistic Suggestion

#2663 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#2661 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#2660 [LOC]Showing "**/Source: <source>: **" (extra asterisks appears)
  articles/storage/common/storage-migration-to-premium-storage.md
Labels: Accepted

#2665 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-customize-cluster-linux.md
Labels: Accepted

#2664 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted, Linguistic Suggestion

#2668 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted

#2669 correct word inconsistency
  articles/expressroute/expressroute-faqs.md
Labels: Accepted, Linguistic Suggestion

#2667 Update load-balancer-ha-ports-overview.md
  articles/load-balancer/load-balancer-ha-ports-overview.md
Labels: Accepted, Linguistic Suggestion

#2675 Fix mistranslation
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted, Linguistic Suggestion

#2676 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#2674 Suggest to improve translations for 'created'
  articles/backup/backup-azure-arm-userestapi-createorupdatevault.md
  articles/media-services/previous/media-services-portal-creating-live-encoder-enabled-channel.md
  articles/media-services/previous/media-services-portal-live-passthrough-get-started.md
  articles/sql-database/elastic-jobs-powershell.md
  articles/virtual-machines/linux/create-vm-rest-api.md
Labels: Accepted, Linguistic Suggestion

#2678 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#2679 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#2680 Fix mistranslation
  articles/iot-hub/iot-hub-devguide-sdks.md
Labels: Accepted

#2677 modify the Japanese nuance
  includes/virtual-machines-common-ephemeral.md
Labels: Accepted, Linguistic Suggestion

#2681 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#2682 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#2683 Fix translation error
  articles/databox-online/data-box-edge-limits.md
Labels: Accepted

#2684 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#2685 [LOC] Back-Translation "タイトル"→"Title"
  articles/azure-functions/functions-flow-scenario.md
Labels: Accepted

#2688 Update tutorial-backup-vm-at-scale.md
  articles/backup/tutorial-backup-vm-at-scale.md
Labels: Accepted

#2690 過剰に日本語訳されている箇所を修正
  articles/backup/backup-azure-arm-userestapi-backupazurevms.md
Labels: Accepted, Linguistic Suggestion

#2692 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Linguistic Suggestion

#2694 change description to fit to English description.
  includes/resource-manager-governance-tags.md
Labels: Accepted, Linguistic Suggestion

#2693 change scale interval time to be as same as English page.
  articles/azure-functions/functions-scale.md
Labels: Accepted, Linguistic Suggestion

#2687 Update index.yml
  articles/backup/index.yml
Labels: Accepted, Linguistic Suggestion

#2695 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted

#2701 文言の修正
  articles/aks/tutorial-kubernetes-prepare-app.md
Labels: Accepted, Linguistic Suggestion

#2707 不自然なひらがなを修正
  articles/notebooks/access-data-resources-jupyter-notebooks.md
Labels: Accepted, Linguistic Suggestion

#2706 不自然な日本語を修正
  articles/notebooks/azure-notebooks-overview.md
Labels: Accepted, Linguistic Suggestion

#2705 Suggest to remove en-US text
  articles/cdn/cdn-verizon-premium-rules-engine-reference.md
Labels: In Progress
