Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-06, with the labels that each got.

#2565 Suggest to clear code block
  articles/dms/known-issues-troubleshooting-dms.md
Labels: In Progress

#2568 Fix typo
  articles/app-service/environment/app-service-environment-with-internal-load-balancer.md
Labels: Accepted, Linguistic Suggestion

#2569 Fix typo
  articles/azure-monitor/app/cloudservices.md
Labels: Accepted, Technical Issue

#2564 Fix mistranslation
  articles/container-registry/container-registry-skus.md
Labels: Accepted

#2563 Fix mistranslation
  articles/backup/backup-azure-vms-encryption.md
Labels: Accepted

#2566 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#2562 Fix mistranslation
  articles/active-directory/authentication/howto-mfa-mfasettings.md
Labels: Accepted

#2567 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#2570 Fix typo
  articles/cognitive-services/LUIS/luis-concept-keys.md
Labels: Accepted

#2571 Suggest to fix description
  articles/azure-maps/supported-languages.md
Labels: Accepted

#2572 Suggest to fix abbreviation
  articles/cdn/cdn-pop-abbreviations.md
Labels: Accepted

#2574 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#2575 Fix mistranslation
  articles/active-directory-b2c/configure-ropc.md
Labels: Accepted, Linguistic Suggestion

#2576 Fix mistranslation
  articles/active-directory-b2c/ropc-custom.md
Labels: Accepted, Linguistic Suggestion

#2577 Fix typo
  articles/sentinel/connect-azure-activity.md
Labels: Accepted, Linguistic Suggestion

#2578 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#2581 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#2580 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#2579 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, Linguistic Suggestion

#2560 Update index.yml
  articles/cosmos-db/index.yml
Labels: Accepted, Linguistic Suggestion

#2582 Update howto-password-ban-bad-on-premises-deploy.md
  articles/active-directory/authentication/howto-password-ban-bad-on-premises-deploy.md
Labels: Accepted, Linguistic Suggestion

#2586 Fix mistranslation
  articles/marketplace/cloud-partner-portal/azure-applications/cpp-handling-review-feedback.md
Labels: In Progress

#2587 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#2589 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: In Progress

#2591 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#2592 Fix mistranslation
  articles/security/azure-infrastructure-availability.md
Labels: In Progress

#2593 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#2594 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#2597 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#2595 Update cognitive-services-containers-configuration-shared-settings-ta…
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: In Progress, Linguistic Suggestion

#2598 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#2599 Update service-fabric-cluster-scaling.md
  articles/service-fabric/service-fabric-cluster-scaling.md
Labels: Accepted, Linguistic Suggestion

#2602 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#2604 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted

#2603 Update cognitive-services-speech-service-rest-auth.md
  includes/cognitive-services-speech-service-rest-auth.md
Labels: Accepted

#2600 Suggest to improve translation of 'authoring'
  articles/cognitive-services/LUIS/index.yml
  articles/cognitive-services/LUIS/toc.yml
Labels: Accepted, Linguistic Suggestion

#2608 Update service-fabric-diagnostics-how-to-report-and-check-service-hea…
  articles/service-fabric/service-fabric-diagnostics-how-to-report-and-check-service-health.md
Labels: Accepted, Linguistic Suggestion

#2614 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#2612 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#2615 Fix mistranslation
  articles/governance/blueprints/samples/index.md
Labels: In Progress

#2619 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#2609 Suggest to keep APIs alphabet
  articles/cognitive-services/Face/Face-API-How-to-Topics/specify-detection-model.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/specify-recognition-model.md
Labels: Accepted, Linguistic Suggestion

#2610 Suggest to fix Americas, Uberaba, Ísland and Cairo
  articles/azure-maps/geocoding-coverage.md
  articles/azure-maps/mobility-coverage.md
  articles/azure-maps/render-coverage.md
  articles/azure-maps/routing-coverage.md
  articles/azure-maps/traffic-coverage.md
Labels: Accepted, Linguistic Suggestion

#2617 Fixed unsuitabled term. "要塞" is not "Bastion"
  articles/bastion/TOC.yml
Labels: Accepted, Linguistic Suggestion

#2616 Suggest to improve translations
  articles/cognitive-services/Content-Moderator/index.yml
  articles/cognitive-services/Custom-Vision-Service/index.yml
  articles/cognitive-services/Speech-Service/index.yml
Labels: Accepted, Linguistic Suggestion

#2627 Fix mistranslation
  articles/security/blueprints/fedramp-iaaswa-overview.md
Labels: Accepted

#2626 Fix mistranslation
  articles/security/blueprints/fedramp-datawarehouse-overview.md
Labels: Accepted, Linguistic Suggestion

#2620 Fix mistranslation
  articles/aks/operator-best-practices-network.md
Labels: Accepted, Linguistic Suggestion

#2637 Fix mistranslation
  articles/security/blueprints/uknhs-datawarehouse-overview.md
Labels: Accepted, Linguistic Suggestion

#2646 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#2647 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted

#2645 Update how-to-model-partition-example.md
  articles/cosmos-db/how-to-model-partition-example.md
Labels: Accepted, Linguistic Suggestion

#2649 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted, Linguistic Suggestion

#2650 Fix mistranslation
  articles/app-service/deploy-staging-slots.md
Labels: Accepted, Linguistic Suggestion

#2652 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#2653 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#2651 Update stream-analytics-javascript-user-defined-functions.md
  articles/stream-analytics/stream-analytics-javascript-user-defined-functions.md
Labels: In Progress
