Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-03, with the labels that each got.

#2193 Delete unnecessary brackets
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted, Linguistic Suggestion

#2194 Delete unnecessary brackets
  articles/site-recovery/site-recovery-workload.md
Labels: Accepted, Linguistic Suggestion

#2195 Delete unnecessary brackets
  articles/storage/common/storage-solution-small-dataset-low-moderate-network.md
Labels: Accepted, Linguistic Suggestion

#2196 Delete unnecessary brackets
  includes/security-attributes-key-vault.md
Labels: Accepted, Linguistic Suggestion

#2197 Fix typo
  articles/sql-database/sql-database-elastic-scale-manage-credentials.md
Labels: Accepted, Linguistic Suggestion

#2198 Fix funny Japanese translation
  articles/active-directory/develop/developer-support-help-options.md
Labels: Accepted, Linguistic Suggestion

#2200 Delete unnecessary brackets
  articles/azure-maps/toc.yml
Labels: Accepted, Linguistic Suggestion

#2201 Delete unnecessary brackets
  articles/governance/policy/toc.yml
Labels: Accepted, Linguistic Suggestion

#2203 Suggest to fix typo
  articles/cognitive-services/Bing-Spell-Check/concepts/using-spell-check.md
Labels: Accepted, Linguistic Suggestion

#2202 Suggest to fix 'Azure Function'
  articles/azure-app-configuration/TOC.yml
  articles/azure-app-configuration/quickstart-azure-function-csharp.md
Labels: Accepted, Linguistic Suggestion

#2207 Update resource-manager-deployment-model.md
  articles/azure-resource-manager/resource-manager-deployment-model.md
Labels: Accepted

#2210 Delete unnecessary brackets
  articles/site-recovery/site-recovery-workload.md
Labels: Accepted

#2213 Fix typo
  articles/analysis-services/analysis-services-async-refresh.md
Labels: Accepted

#2211 Delete unnecessary brackets
  articles/storage/common/storage-solution-small-dataset-low-moderate-network.md
Labels: Accepted

#2209 Delete unnecessary brackets
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted

#2212 Fix typo
  articles/active-directory-b2c/active-directory-b2c-reference-language-customization.md
Labels: Accepted, Linguistic Suggestion

#2218 Delete unnecessary sentences
  articles/active-directory/saas-apps/amazon-web-service-tutorial.md
Labels: Accepted, Technical Issue

#2215 Update virtual-machines-common-constrained-vcpu.md
  includes/virtual-machines-common-constrained-vcpu.md
Labels: Accepted, Linguistic Suggestion

#2214 誤訳の修正
  articles/cosmos-db/table-storage-how-to-use-dotnet.md
Labels: Linguistic Suggestion

#2222 Delete unnecessary brackets
  articles/site-recovery/site-recovery-workload.md
Labels: Accepted

#2227 Fix typo
  articles/media-services/video-indexer/faq.md
Labels: Linguistic Suggestion

#2232 Fix mistranslation
  articles/active-directory-b2c/userjourneys.md
Labels: In Progress

#2233 Fix mistranslation
  articles/active-directory-b2c/validation-technical-profile.md
Labels: Accepted, Linguistic Suggestion

#2224 wrong translation
  articles/service-fabric/service-fabric-cloud-services-migration-worker-role-stateless-service.md
Labels: Accepted, Linguistic Suggestion

#2225 changed expressions about MD5
  articles/expressroute/expressroute-howto-routing-portal-resource-manager.md
Labels: Accepted, Linguistic Suggestion

#2226 Update faq.md
  articles/media-services/video-indexer/faq.md
Labels: Linguistic Suggestion, Partially Accepted

#2205 Update document-formats-naming-convention.md
  articles/cognitive-services/Translator/custom-translator/document-formats-naming-convention.md
Labels: Accepted, Source Issue

#1752 Fix indent misalignment
  articles/traffic-manager/traffic-manager-configure-subnet-routing-method.md
Labels: Accepted, Source Issue

#2234 Fix typo
  articles/automation/automation-source-control-integration-legacy.md
Labels: Accepted, Linguistic Suggestion

#2239 Fix typo
  articles/storage/blobs/storage-custom-domain-name.md
Labels: Accepted, In Progress

#2237 Fix mistranslation
  articles/mysql/concepts-server-logs.md
Labels: Accepted, In Progress

#2231 Fix mistranslation
  articles/active-directory-b2c/claimsschema.md
Labels: Linguistic Suggestion, Partially Accepted

#2248 Fix mistranslation
  articles/api-management/api-management-template-data-model-reference.md
Labels: Accepted

#1751 Fix indent misalignment
  articles/traffic-manager/tutorial-traffic-manager-improve-website-response.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#1750 Fix indent misalignment
  articles/traffic-manager/tutorial-traffic-manager-subnet-routing.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#2235 Fix mistranslation
  articles/azure-monitor/insights/azure-key-vault.md
Labels: Accepted, Linguistic Suggestion

#2236 Fix mistranslation
  articles/azure-monitor/insights/service-map.md
Labels: Accepted, Linguistic Suggestion

#2240 Update migrate-knowledge-base.md
  articles/cognitive-services/QnAMaker/Tutorials/migrate-knowledge-base.md
Labels: Linguistic Suggestion, Partially Accepted
