Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-01, with the labels that each got.

#1506 Delete unnecessary brackets
  articles/stream-analytics/stream-analytics-define-outputs.md
Labels: Accepted, Linguistic Suggestion

#1507 Delete unnecessary brackets
  articles/virtual-machines/windows/overview.md
Labels: Accepted, Linguistic Suggestion

#1502 Delete unnecessary brackets
  articles/virtual-network/manage-public-ip-address-prefix.md
Labels: Accepted, Linguistic Suggestion

#1504 Delete unnecessary brackets
  articles/storsimple/storsimple-update4-release-notes.md
Labels: Accepted, Linguistic Suggestion

#1508 Delete unnecessary brackets
  articles/virtual-machines/linux/classic/cassandra-nodejs.md
Labels: Accepted, Linguistic Suggestion

#1509 Delete unnecessary brackets
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-maintenance-notifications.md
Labels: Accepted, Linguistic Suggestion

#1517 Delete unnecessary brackets
  articles/storsimple/storsimple-8000-monitor-hardware-status.md
Labels: Accepted, Linguistic Suggestion

#1518 Delete unnecessary brackets
  articles/storsimple/storsimple-8000-migrate-classic-azure-portal.md
Labels: Accepted, Linguistic Suggestion

#1520 Delete unnecessary brackets
  articles/storage/files/storage-sync-files-troubleshoot.md
Labels: Accepted, Linguistic Suggestion

#1523 Delete unnecessary brackets
  articles/storage/common/storage-cors-support.md
Labels: Accepted, Linguistic Suggestion

#1524 Delete unnecessary brackets
  articles/storage/common/storage-concurrency.md
Labels: Accepted, Linguistic Suggestion

#1525 Delete unnecessary brackets
  articles/sql-database/sql-database-vcore-resource-limits-single-databases.md
Labels: Accepted, Linguistic Suggestion

#1526 Delete unnecessary brackets
  articles/api-management/api-management-cross-domain-policies.md
Labels: Accepted, Linguistic Suggestion

#1528 Delete unnecessary brackets
  articles/application-insights/app-insights-monitor-performance-live-website-now.md
Labels: Accepted, Linguistic Suggestion

#1593 Translation translation omission
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Technical Issue

#1592 Translation translation omission
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Technical Issue

#1591 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Technical Issue

#1589 Translation translation omission
  articles/data-factory/tutorial-copy-data-tool.md
Labels: Accepted, Technical Issue

#1587 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted

#1522 Delete unnecessary brackets
  articles/storage/common/storage-decide-blobs-files-disks.md
Labels: Accepted, Linguistic Suggestion

#1527 Delete unnecessary brackets
  articles/api-management/api-management-transformation-policies.md
Labels: Accepted, Linguistic Suggestion

#1597 Translation translation omission
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, Technical Issue

#1595 Translation translation omission and format the indentation
  articles/data-factory/concepts-datasets-linked-services.md
Labels: Accepted, Technical Issue

#1432 Improve translation
  articles/key-vault/key-vault-access-behind-firewall.md
Labels: Accepted, Linguistic Suggestion

#1601 Delete unnecessary brackets and translation translation omission
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1600 Delete unnecessary brackets and translation translation omission
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1602 Delete unnecessary brackets and translation translation omission
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1603 Delete unnecessary brackets and translation translation omission
  articles/data-factory/connector-azure-search.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1604 Translation translation omission and delete unnecessary brackets
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1606 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-portal.md
Labels: Accepted, Technical Issue

#1607 Translation translation omission
  articles/data-factory/copy-activity-fault-tolerance.md
Labels: Accepted, Technical Issue

#1608 Translation translation omission
  articles/data-factory/copy-activity-performance.md
Labels: Accepted, Technical Issue

#1609 Translation translation omission
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Technical Issue

#1610 Translation translation omission
  articles/data-factory/control-flow-expression-language-functions.md
Labels: Accepted, Technical Issue

#1611 Translation translation omission
  articles/data-factory/introduction.md
Labels: Accepted, Technical Issue

#1612 Translation translation omission
  articles/media-services/previous/media-services-media-encoder-standard-formats.md
Labels: Accepted, Technical Issue

#1613 Translation translation omission
  articles/media-services/previous/media-services-overview.md
Labels: Accepted, Technical Issue

#1598 fix translations
  articles/azure-functions/durable/durable-functions-create-first-csharp.md
Labels: Accepted, Linguistic Suggestion

#1619 Translation translation omission
  articles/data-factory/v1/data-factory-web-table-connector.md
Labels: Accepted, Technical Issue

#1618 Translation translation omission
  articles/data-factory/v1/data-factory-usql-activity.md
Labels: Accepted, Technical Issue

#1617 Translation translation omission
  articles/data-factory/v1/data-factory-use-custom-activities.md
Labels: Accepted, Technical Issue

#1616 Translation translation omission
  articles/data-factory/v1/data-factory-sap-hana-connector.md
Labels: Accepted, Technical Issue

#1615 Translation translation omission
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Technical Issue

#1632 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, Technical Issue

#1630 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-db2-connector.md
Labels: Accepted, Technical Issue

#1629 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-cassandra-connector.md
Labels: Accepted, Technical Issue

#1640 Translation translation omission
  articles/data-factory/transform-data-using-hadoop-hive.md
Labels: Accepted, Technical Issue

#1648 Update collaborate-knowledge-base.md
  articles/cognitive-services/QnAMaker/How-To/collaborate-knowledge-base.md
Labels: Accepted, Linguistic Suggestion

#1626 Fix translations
  articles/azure-functions/durable/quickstart-js-vscode.md
Labels: Accepted, Linguistic Suggestion

#1625 Fix translations
  articles/azure-functions/durable/durable-functions-types-features-overview.md
Labels: Accepted, Linguistic Suggestion

#1623 Fix translations
  articles/azure-functions/durable/durable-functions-http-api.md
Labels: Accepted, Linguistic Suggestion

#1650 Translation translation omission
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#1651 Translation translation omission
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, Technical Issue

#1679 Translation translation omission
  articles/data-factory/v1/data-factory-amazon-simple-storage-service-connector.md
Labels: Accepted, Technical Issue

#1678 Translation translation omission
  articles/data-factory/v1/data-factory-amazon-redshift-connector.md
Labels: Accepted, Technical Issue

#1677 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-rest-api.md
Labels: Accepted, Technical Issue

#1676 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-resource-manager-template.md
Labels: Accepted, Technical Issue

#1675 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-python.md
Labels: Accepted, Technical Issue

#1674 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-powershell.md
Labels: Accepted, Technical Issue

#1673 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-dot-net.md
Labels: Accepted, Technical Issue

#1672 Translation translation omission
  articles/data-factory/data-movement-security-considerations.md
Labels: Accepted, Technical Issue

#1671 Translation translation omission
  articles/data-factory/connector-web-table.md
Labels: Accepted, Technical Issue

#1670 Translation translation omission
  articles/data-factory/connector-teradata.md
Labels: Accepted, Technical Issue

#1669 Translation translation omission
  articles/data-factory/connector-sybase.md
Labels: Accepted, Technical Issue

#1668 Translation translation omission
  articles/data-factory/connector-sql-server.md
Labels: Accepted, Technical Issue

#1667 Translation translation omission
  articles/data-factory/connector-sftp.md
Labels: Accepted, Technical Issue

#1666 Translation translation omission
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, Technical Issue

#1665 Translation translation omission
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, Technical Issue

#1664 Translation translation omission
  articles/data-factory/connector-salesforce.md
Labels: Accepted, Technical Issue

#1663 Translation translation omission
  articles/data-factory/connector-postgresql.md
Labels: Accepted, Technical Issue

#1662 Translation translation omission
  articles/data-factory/connector-oracle.md
Labels: Accepted, Technical Issue

#1661 Translation translation omission
  articles/data-factory/connector-odbc.md
Labels: Accepted, Technical Issue

#1658 Translation translation omission
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, Technical Issue

#1656 Translation translation omission
  articles/data-factory/connector-hdfs.md
Labels: Accepted, Technical Issue

#1655 Translation translation omission
  articles/data-factory/connector-ftp.md
Labels: Accepted, Technical Issue

#1654 Translation translation omission
  articles/data-factory/connector-file-system.md
Labels: Accepted, Technical Issue

#1653 Translation translation omission
  articles/data-factory/connector-db2.md
Labels: Accepted, Technical Issue

#1680 properties should be kept in alphabet
  articles/media-services/latest/filters-dynamic-manifest-overview.md
Labels: Accepted, Linguistic Suggestion

#1621 Fix translations
  articles/azure-functions/durable/durable-functions-create-portal.md
Labels: In Progress, Linguistic Suggestion

#1637 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#1686 Translation translation omission
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, Technical Issue

#1685 Translation translation omission
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, Technical Issue

#1684 Translation translation omission
  articles/data-factory/v1/data-factory-azure-search-connector.md
Labels: Accepted, Technical Issue

#1683 Translation translation omission
  articles/data-factory/v1/data-factory-azure-documentdb-connector.md
Labels: Accepted, Technical Issue

#1682 Translation translation omission
  articles/data-factory/v1/data-factory-azure-datalake-connector.md
Labels: Accepted, Technical Issue

#1692 Fix typo
  articles/azure-databricks/databricks-extract-load-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#1693 Fix typo
  articles/azure-databricks/databricks-sentiment-analysis-cognitive-services.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1694 Fix typo
  articles/azure-databricks/quickstart-create-databricks-workspace-portal.md
Labels: Accepted, Technical Issue

#1695 Fix typo
  articles/azure-databricks/quickstart-create-databricks-workspace-resource-manager-template.md
Labels: Accepted, Technical Issue

#1697 Fix typo
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Technical Issue

#1701 Too much translation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, Linguistic Suggestion

#1703 UI is different Japanese
  articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md
Labels: In Progress, Linguistic Suggestion

#1710 remove ghost text
  articles/event-hubs/event-hubs-resource-manager-namespace-event-hub.md
Labels: Accepted, Source Issue

#1705 Fix missing
  articles/azure-monitor/app/usage-cohorts.md
Labels: Accepted, Linguistic Suggestion

#1706 Fix missing
  articles/azure-monitor/platform/data-sources.md
Labels: Accepted, Linguistic Suggestion

#1707 Fix missing
  articles/azure-monitor/platform/personal-data-mgmt.md
Labels: Accepted, Linguistic Suggestion

#1493 Delete unnecessary brackets
  includes/data-factory-azure-storage-linked-services.md
Labels: Accepted, Technical Issue

#1492 Delete unnecessary brackets
  includes/data-factory-structure-for-rectangualr-datasets.md
Labels: Accepted, Technical Issue

#1491 Delete unnecessary brackets
  includes/virtual-machines-faq-for-disks.md
Labels: Accepted, Technical Issue

#1742 Fix missing
  articles/cognitive-services/Custom-Vision-Service/rest-api-tutorial.md
Labels: Accepted, Linguistic Suggestion

#1733 Fix missing
  articles/azure-functions/functions-bindings-microsoft-graph.md
Labels: Accepted, Linguistic Suggestion

#1732 Fix missing
  articles/azure-functions/app-service-export-api-to-powerapps-and-flow.md
Labels: Accepted, Linguistic Suggestion

#1731 Fix missing
  articles/app-service/overview-inbound-outbound-ips.md
Labels: Accepted, Linguistic Suggestion

#1714 Delete unnecessary brackets
  articles/active-directory/devices/azureadjoin-plan.md
Labels: Accepted, Linguistic Suggestion

#1729 Fix missing
  articles/app-service/containers/tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion

#1720 Delete unnecessary brackets
  articles/analysis-services/tutorials/aas-lesson-4-create-relationships.md
Labels: Accepted, Linguistic Suggestion

#1728 Fix missing
  articles/app-service/app-service-web-tutorial-php-mysql.md
Labels: Accepted, Linguistic Suggestion

#1719 Delete unnecessary brackets
  articles/analysis-services/analysis-services-datasource.md
Labels: Accepted, Linguistic Suggestion

#1718 Delete unnecessary brackets
  articles/aks/operator-best-practices-storage.md
Labels: Accepted, Linguistic Suggestion

#1717 Delete unnecessary brackets
  articles/active-directory/privileged-identity-management/pim-email-notifications.md
Labels: Accepted, Linguistic Suggestion

#1716 Delete unnecessary brackets
  articles/active-directory/manage-apps/application-provisioning-config-problem-scim-compatibility.md
Labels: Accepted, Linguistic Suggestion

#1727 Fix missing
  articles/app-service/app-service-web-tutorial-nodejs-mongodb-app.md
Labels: Accepted, Linguistic Suggestion

#1715 Delete unnecessary brackets
  articles/active-directory/governance/active-directory-tou.md
Labels: Accepted, Linguistic Suggestion

#1726 Fix missing
  articles/active-directory/saas-apps/infinitecampus-tutorial.md
Labels: Accepted, Linguistic Suggestion

#1723 Delete unnecessary brackets
  articles/api-management/api-management-advanced-policies.md
Labels: Accepted, Linguistic Suggestion

#1725 Fix missing
  articles/active-directory/manage-apps/application-proxy-connectors.md
Labels: Accepted, Linguistic Suggestion

#1724 Fix missing
  articles/active-directory/hybrid/how-to-connect-pta-security-deep-dive.md
Labels: Accepted, Linguistic Suggestion

#1713 Fix missing
  articles/active-directory-b2c/validation-technical-profile.md
Labels: Accepted, Linguistic Suggestion

#1743 Delete unnecessary brackets
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: Accepted, Linguistic Suggestion

#1745 Delete unnecessary brackets
  articles/virtual-machines/windows/sqlclassic/virtual-machines-windows-classic-ps-sql-bi.md
Labels: Accepted, Linguistic Suggestion

#1746 Delete unnecessary brackets
  articles/virtual-machines/troubleshooting/how-to-use-perfInsights.md
Labels: Accepted, Linguistic Suggestion

#1754 Delete unnecessary brackets
  articles/storsimple/storsimple-update4-release-notes.md
Labels: Accepted, Linguistic Suggestion

#1758 Delete unnecessary brackets
  articles/storage/common/storage-solution-small-dataset-low-moderate-network.md
Labels: Accepted, Linguistic Suggestion

#1759 Delete unnecessary brackets
  articles/storage/common/storage-solution-periodic-data-transfer.md
Labels: Accepted, Linguistic Suggestion

#1760 Delete unnecessary brackets
  articles/storage/common/storage-solution-large-dataset-moderate-high-network.md
Labels: Accepted, Linguistic Suggestion

#1761 Delete unnecessary brackets
  articles/storage/common/storage-solution-large-dataset-low-network.md
Labels: Accepted, Linguistic Suggestion

#1762 Delete unnecessary brackets
  articles/storage/common/storage-decide-blobs-files-disks.md
Labels: Accepted, Linguistic Suggestion

#1764 Delete unnecessary brackets
  articles/storage/blobs/data-lake-storage-upgrade.md
Labels: In Progress, Linguistic Suggestion

#1753 Fix missing
  articles/storsimple/storsimple-virtual-array-manage-alerts.md
Labels: Accepted, Source Issue

#1794 Delete unnecessary brackets
  articles/cognitive-services/text-analytics/text-analytics-resource-container-config.md
Labels: Accepted, Linguistic Suggestion

#1748 Delete unnecessary brackets
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-faq.md
Labels: Accepted, Linguistic Suggestion

#1769 Delete unnecessary brackets
  articles/sql-database/sql-database-vcore-resource-limits-elastic-pools.md
Labels: Accepted, Linguistic Suggestion

#1771 Delete unnecessary brackets
  articles/service-bus-relay/relay-hybrid-connections-protocol.md
Labels: Accepted, Linguistic Suggestion

#1776 Delete unnecessary brackets
  articles/azure-monitor/insights/service-map-configure.md
Labels: Accepted, Linguistic Suggestion

#1778 Delete unnecessary brackets
  articles/automation/automation-update-management.md
Labels: Accepted, Linguistic Suggestion

#1781 Delete unnecessary brackets
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, Linguistic Suggestion

#1782 Delete unnecessary brackets
  articles/azure-monitor/platform/alerts-metric-near-real-time.md
Labels: Accepted, Linguistic Suggestion

#1783 Delete unnecessary brackets
  articles/azure-monitor/platform/om-agents.md
Labels: Accepted, Linguistic Suggestion

#1784 Delete unnecessary brackets
  articles/azure-resource-manager/tag-support.md
Labels: Accepted, Linguistic Suggestion

#1785 Delete unnecessary brackets
  articles/azure-stack/azure-stack-supported-os.md
Labels: Accepted, Linguistic Suggestion

#1787 Delete unnecessary brackets
  articles/cognitive-services/Speech-Service/speech-to-text.md
Labels: Accepted, Linguistic Suggestion

#1789 Delete unnecessary brackets
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion

#1790 Delete unnecessary brackets
  articles/cognitive-services/Speech-Service/overview.md
Labels: Accepted, Linguistic Suggestion

#1791 Delete unnecessary brackets
  articles/cognitive-services/Speech-Service/rest-apis.md
Labels: Accepted, Linguistic Suggestion

#1798 Fix type url (ja-jp)
  articles/media-services/latest/offline-plaready-streaming-for-windows-10.md
Labels: Accepted, Source Issue

#1801 Delete unnecessary brackets
  articles/cognitive-services/Speech/Home.md
Labels: Accepted, Linguistic Suggestion

#1802 Delete unnecessary brackets
  articles/cognitive-services/Translator/customization.md
Labels: Accepted, Linguistic Suggestion

#1809 Delete unnecessary brackets
  articles/connectors/connectors-create-api-crmonline.md
Labels: Accepted, Linguistic Suggestion

#1812 Delete unnecessary brackets
  articles/connectors/connectors-create-api-mailchimp.md
Labels: Accepted, Linguistic Suggestion

#1813 Delete unnecessary brackets
  articles/connectors/connectors-create-api-onedriveforbusiness.md
Labels: Accepted, Linguistic Suggestion
