Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-09, with the labels that each got.

#2770 Suggest to improve translations for 'primary and secondary color'
  articles/azure-maps/how-to-use-image-templates-web-sdk.md
Labels: Accepted, Linguistic Suggestion

#2771 fix FIDO2 Security Key features
  articles/active-directory/authentication/concept-authentication-passwordless.md
Labels: Accepted, Linguistic Suggestion

#2783 Fix mistranslation
  articles/security/fundamentals/ad-passwordless.md
Labels: Accepted

#2782 Fix mistranslation
  articles/active-directory/authentication/TOC.yml
Labels: Accepted

#2781 Fix mistranslation
  articles/active-directory/authentication/concept-authentication-passwordless.md
Labels: Accepted

#2780 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: Accepted

#2784 Fix mistranslation
  articles/security/fundamentals/identity-management-best-practices.md
Labels: Accepted

#2785 Suggest to fix 'GA'
  articles/marketplace/partner-center-portal/commercial-marketplace-co-sell-countries.md
Labels: Accepted, Linguistic Suggestion

#2790 Fix excessive translations
  articles/azure-app-configuration/quickstart-aspnet-core-app.md
Labels: Accepted

#2789 Fix excessive translation
  articles/azure-monitor/app/release-notes.md
Labels: Accepted

#2788 Fix excessive translations
  articles/azure-cache-for-redis/cache-dotnet-how-to-use-azure-redis-cache.md
Labels: Accepted, Linguistic Suggestion

#2787 Fix excessive translations
  articles/azure-cache-for-redis/cache-dotnet-core-quickstart.md
Labels: Accepted, Linguistic Suggestion

#2777 fix typo
  articles/azure-cache-for-redis/cache-how-to-redis-cli-tool.md
Labels: Accepted, Linguistic Suggestion

#2778 Fix unnatural translation
  articles/application-gateway/create-ssl-portal.md
Labels: Accepted, Linguistic Suggestion

#2791 Fix unnatural translation
  articles/active-directory/develop/scenario-protected-web-api-app-registration.md
Labels: Accepted, Linguistic Suggestion

#2793 Fix excessive translation
  articles/cognitive-services/Speech-Service/quickstart-csharp-dotnetcore-windows.md
Labels: Accepted, Linguistic Suggestion

#2792 Fix excessive translation
  articles/azure-app-configuration/quickstart-dotnet-core-app.md
Labels: Accepted, Linguistic Suggestion

#2803 Fix mistranslation
  articles/cognitive-services/Speech-Service/quickstart-translate-speech-dotnetcore-windows.md
Labels: Accepted

#2802 Fix mistranslation
  articles/cognitive-services/Speech-Service/quickstart-text-to-speech-dotnetcore.md
Labels: Accepted

#2801 Fix mistranslation
  articles/cognitive-services/Speech-Service/quickstart-dotnet-text-to-speech.md
Labels: Accepted

#2799 Fix mistranslation
  articles/cognitive-services/Bing-Web-Search/web-search-sdk-quickstart.md
Labels: Accepted

#2798 Fix mistranslation
  articles/azure-signalr/signalr-quickstart-rest-api.md
Labels: Accepted

#2797 Fix mistranslation
  articles/azure-signalr/signalr-concept-authenticate-oauth.md
Labels: Accepted

#2796 Fix mistranslation
  articles/azure-monitor/app/api-filtering-sampling.md
Labels: Accepted

#2795 Fix mistranslation
  articles/azure-monitor/app/api-custom-events-metrics.md
Labels: Accepted

#2805 Fix page title
  articles/terraform/terrafom-quickstart.md
Labels: Accepted, Linguistic Suggestion

#2810 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: Accepted, Linguistic Suggestion

#2811 Fix mistranslation
  articles/event-grid/subscription-creation-schema.md
Labels: Accepted, Linguistic Suggestion

#2812 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: Accepted, Linguistic Suggestion

#2813 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#2814 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: Accepted, Linguistic Suggestion

#2807 Fix misstranslation
  articles/virtual-machines/workloads/oracle/oracle-oci-applications.md
Labels: Accepted

#2806 Fix miss translations
  articles/bastion/bastion-overview.md
Labels: Linguistic Suggestion, Partially Accepted

#2808 過剰な翻訳
  articles/azure-functions/functions-create-function-app-portal.md
Labels: Accepted, Linguistic Suggestion

#2816 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: Accepted, Linguistic Suggestion

#2825 Fix mistranslation
  articles/storsimple/storsimple-update3-release-notes.md
Labels: Accepted

#2824 Fix mistranslation
  articles/storsimple/storsimple-update21-release-notes.md
Labels: Accepted

#2817 Translate 'Yes', 'No' and 'N/A'
  includes/security-controls-header.md
Labels: Accepted, Linguistic Suggestion

#2822 Update billing-prepay-app-service-isolated-stamp.md
  articles/billing/billing-prepay-app-service-isolated-stamp.md
Labels: Linguistic Suggestion, Partially Accepted

#2828 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: Accepted

#2819 Fix 'No.'
  articles/databox-online/data-box-gateway-release-notes.md
  articles/storsimple/storsimple-8000-troubleshoot-deployment.md
  articles/storsimple/storsimple-ova-update-01-release-notes.md
  articles/storsimple/storsimple-troubleshoot-operational-device.md
Labels: Accepted

#2823 Update security-overview.md
  articles/virtual-network/security-overview.md
Labels: Accepted, Linguistic Suggestion

#2826 Update monitor-accounts.md
  articles/cosmos-db/monitor-accounts.md
Labels: Accepted, Linguistic Suggestion

#2827 More appropriate translation
  articles/billing/billing-save-compute-costs-reservations.md
Labels: Accepted, Linguistic Suggestion

#2829 Update security-center-remediate-recommendations.md
  articles/security-center/security-center-remediate-recommendations.md
Labels: Accepted, Linguistic Suggestion

#2830 Update guest-configuration.md
  articles/governance/policy/concepts/guest-configuration.md
Labels: Accepted, Linguistic Suggestion

#2833 Update online-backup-and-restore.md
  articles/cosmos-db/online-backup-and-restore.md
Labels: Accepted, Linguistic Suggestion

#2835 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted

#2836 Fix 'requests'
  articles/active-directory/develop/quickstart-v2-python-webapp.md
Labels: Accepted
