Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2019-05, with the labels that each got.

#2514 Suggest to fix ServiceDefinition.csdef
  articles/cloud-services/cloud-services-startup-tasks-common.md
Labels: In Progress

#2510 Update continuous-monitoring.md
  articles/azure-monitor/continuous-monitoring.md
Labels: Accepted, Linguistic Suggestion

#2512 Suggest to fix 'hybrid connections'
  articles/azure-functions/functions-networking-options.md
Labels: Accepted, Linguistic Suggestion

#2523 Suggest to keep in alphabets
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted, Linguistic Suggestion

#2525 Japanese translation is confusing.
  articles/expressroute/expressroute-howto-coexist-resource-manager.md
Labels: Accepted, Linguistic Suggestion

#2522 Update logic-apps-scenario-function-sb-trigger.md
  articles/logic-apps/logic-apps-scenario-function-sb-trigger.md
Labels: Accepted, Linguistic Suggestion

#2519 Update monitor-web-app-availability.md
  articles/azure-monitor/app/monitor-web-app-availability.md
Labels: Accepted, Linguistic Suggestion

#2518 Fix KANJI character in translation.
  articles/cognitive-services/Custom-Vision-Service/index.yml
Labels: Accepted, Linguistic Suggestion

#2533 ExR回線 同一リージョン複数接続サポートについて
  articles/expressroute/expressroute-faqs.md
Labels: Accepted, Linguistic Suggestion

#2529 Japanese translation is confusing
  articles/expressroute/expressroute-circuit-peerings.md
Labels: Accepted, Linguistic Suggestion

#2541 Update concepts-server-logs.md
  articles/postgresql/concepts-server-logs.md
Labels: Accepted, Linguistic Suggestion

#2538 Suggest to fix typo
  includes/cognitive-services-speech-service-quickstart-cpp-create-proj.md
Labels: In Progress

#2540 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress

#2543 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#2542 Update howto-troubleshoot-common-connection-issues.md
  articles/postgresql/howto-troubleshoot-common-connection-issues.md
Labels: In Progress

#2545 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#2546 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#2544 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#2549 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#2553 Update traffic-manager-FAQs.md
  articles/traffic-manager/traffic-manager-FAQs.md
Labels: In Progress

#2550 Fix mistranslation
  articles/data-factory/v1/data-factory-odata-connector.md
Labels: Accepted, Linguistic Suggestion

#2551 Fix mistranslation
  articles/data-factory/v1/data-factory-odbc-connector.md
Labels: Accepted, Linguistic Suggestion

#2557 Update toc.yml
  articles/traffic-manager/toc.yml
Labels: Accepted, Linguistic Suggestion

#2558 Fix mistranslation
  articles/site-recovery/site-recovery-faq.md
Labels: Accepted, Linguistic Suggestion

#2559 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress
