Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2020-01, with the labels that each got.

#2999 Fix the command.
  articles/aks/ssh.md
Labels: Accepted

#3001 Fix typo
  articles/azure-monitor/platform/metrics-supported.md
Labels: Accepted

#3003 Update storage-files-faq.md
  articles/storage/files/storage-files-faq.md
Labels: Accepted, Linguistic Suggestion

#2998 modified content
  articles/iot-hub/iot-hub-devguide-security.md
Labels: Linguistic Suggestion, Partially Accepted

#3005 Fix mistranslation
  articles/app-service/app-service-web-restore-snapshots.md
Labels: Accepted, Linguistic Suggestion

#3009 Improve translation
  articles/azure-monitor/platform/metrics-supported.md
Labels: Accepted

#3008 Fix typo
  articles/azure-monitor/platform/metrics-supported.md
Labels: Accepted, Linguistic Suggestion

#3010 Improve translation
  articles/role-based-access-control/resource-provider-operations.md
Labels: Accepted, Linguistic Suggestion

#3012 Fix mistranslation
  articles/app-service/overview-hosting-plans.md
Labels: Accepted, Linguistic Suggestion

#3011 Fix mistranslation
  articles/app-service/overview-inbound-outbound-ips.md
Labels: Accepted, Linguistic Suggestion

#3013 Fix mistranslation
  articles/azure-functions/functions-networking-options.md
Labels: Accepted, Linguistic Suggestion

#3017 Correct terminology mistakes
  articles/active-directory/develop/msal-net-xamarin-ios-considerations.md
Labels: Accepted

#3016 Fix markdown
  articles/machine-learning/how-to-manage-workspace-cli.md
Labels: Accepted, Linguistic Suggestion

#3019 Fix Overtransration
  articles/azure-functions/create-function-app-linux-app-service-plan.md
Labels: Accepted, Linguistic Suggestion

#3021 Update event-hubs-auto-inflate.md
  articles/event-hubs/event-hubs-auto-inflate.md
Labels: Accepted, Linguistic Suggestion

#3022 Update event-hubs-scalability.md
  articles/event-hubs/event-hubs-scalability.md
Labels: Accepted, Linguistic Suggestion

#3025 Fix markdown
  articles/machine-learning/compare-azure-ml-to-studio-classic.md
  articles/machine-learning/concept-ml-pipelines.md
  articles/machine-learning/how-to-deploy-app-service.md
  articles/machine-learning/how-to-deploy-azure-kubernetes-service.md
  articles/machine-learning/how-to-deploy-local-container-notebook-vm.md
  articles/machine-learning/how-to-enable-virtual-network.md
  articles/machine-learning/tutorial-train-deploy-model-cli.md
Labels: Accepted, Technical Issue

#3026 Fix mistranslation
  articles/application-gateway/key-vault-certs.md
Labels: Accepted, Linguistic Suggestion

#3034 Fix mistranslation
  articles/key-vault/tutorial-net-linux-virtual-machine.md
Labels: Accepted

#3035 [LOC]Back-Translation "デバッグ"→"Debug"
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted

#3033 Fix incorrect information
  includes/functions-bindings-event-hubs.md
Labels: Accepted

#3037 [LOC]Back-Translation "電子メール"→"Email"
  articles/cognitive-services/LUIS/luis-reference-prebuilt-entities.md
Labels: Accepted

#3038 Improve translation
  articles/role-based-access-control/resource-provider-operations.md
Labels: Accepted, Linguistic Suggestion

#3036 [LOC]Back-Translation "シアトル"→"Seattle"
  articles/cognitive-services/LUIS/what-is-luis.md
Labels: Accepted, Linguistic Suggestion, Technical Issue
