Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2020-04, with the labels that each got.

#4323 Fix translations for "English"
  articles/cognitive-services/Bing-Spell-Check/language-support.md
  articles/cognitive-services/Ink-Recognizer/language-support.md
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion

#4325 Update reference-connect-adsyncconfig.md
  articles/active-directory/hybrid/reference-connect-adsyncconfig.md
Labels: Accepted, Linguistic Suggestion

#4328 [LOC]Back-Translation "整数"→"Integer"
  includes/cognitive-services-containers-configuration-shared-settings-fluentd.md
Labels: Accepted, Linguistic Suggestion

#4327 [LOC]Translation "| Name |"→"| 名前 |"
  includes/cognitive-services-containers-configuration-shared-settings-eula.md
Labels: Accepted, Linguistic Suggestion

#4326 [LOC]Translation "| Name |"→"| 名前 |"
  includes/cognitive-services-containers-configuration-shared-settings-application-insights.md
Labels: Accepted, Linguistic Suggestion

#4330 Fixed brackets "[[ディスク]]"→"[ディスク]"
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted, Linguistic Suggestion

#4329 [LOC]Fixed inappropriate japanese "Eula 設定"→"Eula の設定"
  articles/cognitive-services/form-recognizer/form-recognizer-container-configuration.md
Labels: Accepted, Linguistic Suggestion

#4310 Improve translation
  articles/service-fabric/service-fabric-service-model-schema-complex-types.md
Labels: In Progress

#4311 Improve translation
  articles/service-fabric/service-fabric-service-model-schema-elements.md
Labels: In Progress

#4331 Update sql-database-xevent-db-diff-from-svr.md
  articles/sql-database/sql-database-xevent-db-diff-from-svr.md
Labels: Accepted, Linguistic Suggestion

#4332 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-named-entity-recognition.md
Labels: Accepted, Linguistic Suggestion

#4333 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-concept-image-scenarios.md
Labels: Accepted, Linguistic Suggestion

#4334 Improve translation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: Accepted, Linguistic Suggestion

#4337 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-image-analysis.md
Labels: Accepted, Linguistic Suggestion

#4336 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-keyphrases.md
Labels: Accepted, Linguistic Suggestion

#4335 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-sentiment.md
Labels: Accepted, Linguistic Suggestion

#4342 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-api-migration.md
Labels: Accepted, Linguistic Suggestion

#4341 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-custom-skill-web-api.md
Labels: Accepted, Linguistic Suggestion

#4340 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-concept-troubleshooting.md
Labels: Accepted, Linguistic Suggestion

#4339 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-shaper.md
Labels: Accepted, Linguistic Suggestion

#4338 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/query-odata-filter-orderby-syntax.md
Labels: Accepted, Linguistic Suggestion

#4344 Fix translations
  articles/cognitive-services/Ink-Recognizer/language-support.md
Labels: Accepted, Linguistic Suggestion

#4343 Fix translations
  articles/cognitive-services/Bing-Spell-Check/language-support.md
Labels: Accepted, Linguistic Suggestion

#4345 Fix translations
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion

#4346 Fix translations
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion

#4347 Fix translations
  articles/cognitive-services/Bing-Autosuggest/language-support.md
Labels: Accepted, Linguistic Suggestion

#4348 Fix translations
  articles/cognitive-services/text-analytics/language-support.md
Labels: Accepted, Linguistic Suggestion

#4350 Fix translations
  articles/cognitive-services/QnAMaker/Overview/language-support.md
Labels: Accepted, Linguistic Suggestion

#4351 Fix translations
  articles/cognitive-services/Translator/language-support.md
Labels: Accepted, Linguistic Suggestion

#4352 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-howto-index-csv-blobs.md
Labels: Accepted, Linguistic Suggestion

#4358 Fix translations
  articles/active-directory-b2c/user-flow-language-customization.md
Labels: Accepted, Linguistic Suggestion

#4359 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-howto-large-index.md
Labels: Accepted, Linguistic Suggestion

#4360 Fix translations
  articles/azure-maps/supported-languages.md
Labels: Accepted, Linguistic Suggestion

#4361 Fix translations
  articles/cognitive-services/Content-Moderator/language-support.md
Labels: Accepted, Linguistic Suggestion

#4362 Fix translations
  articles/cognitive-services/Translator/language-support.md
Labels: Accepted, Linguistic Suggestion

#4363 Fix translations
  articles/search/index-add-language-analyzers.md
Labels: Accepted, Linguistic Suggestion

#4371 Fix translations
  articles/cognitive-services/LUIS/luis-reference-prebuilt-entities.md
Labels: Accepted, Linguistic Suggestion

#4373 Update configuration-overview.md
  articles/application-gateway/configuration-overview.md
Labels: Accepted, Linguistic Suggestion

#4374 Fix translations
  articles/azure-monitor/platform/gateway.md
Labels: Accepted, Linguistic Suggestion

#4366 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-concept-annotations-syntax.md
Labels: Accepted, Linguistic Suggestion

#4377 Fix translations
  articles/cognitive-services/LUIS/luis-language-support.md
Labels: Accepted, Linguistic Suggestion

#4379 Fix translations
  articles/cognitive-services/Computer-vision/language-support.md
Labels: Accepted, Linguistic Suggestion

#4378 Fix translations
  articles/cognitive-services/QnAMaker/How-To/language-knowledge-base.md
Labels: Accepted, Linguistic Suggestion

#4384 [LOC] Back-Translation "認知検索"→ "Cognitive Search"
  articles/search/search-indexer-troubleshooting.md
Labels: Accepted, Linguistic Suggestion

#4349 Fix translations
  articles/cognitive-services/bing-visual-search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4353 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-howto-large-index.md
Labels: Accepted, Linguistic Suggestion

#4355 [LOC] Back-Translation "認知検索"→ "Cognitive Search"
  articles/search/cognitive-search-skill-document-extraction.md
Labels: Accepted, Linguistic Suggestion

#4356 [LOC] Back-Translation "認知検索"→ "Cognitive Search"
  articles/search/search-indexer-troubleshooting.md
Labels: Accepted, Linguistic Suggestion

#4364 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-text-translation.md
Labels: Accepted, Linguistic Suggestion

#4365 [LOC]Back-Translation "| 詳細 |"→"| details |"
  articles/search/cognitive-search-skill-image-analysis.md
Labels: Accepted, Linguistic Suggestion

#4367 [LOC]Translation "Image Analysis"→"画像分析"
  articles/search/cognitive-search-skill-image-analysis.md
Labels: Accepted, Linguistic Suggestion

#4368 [LOC]Back-Translation "| スコア |"→"| score |"
  articles/search/cognitive-search-skill-language-detection.md
Labels: Accepted, Linguistic Suggestion

#4369 [LOC]Back-Translation "**検索価格レベル**"→"**Azure Search 価格レベル**"
  articles/cognitive-services/QnAMaker/How-To/set-up-qnamaker-service-azure.md
Labels: Accepted, Linguistic Suggestion

#4376 Fix translations
  articles/cognitive-services/Bing-News-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4388 Fix translations
  articles/cognitive-services/Bing-News-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4387 Fix translations
  articles/cognitive-services/Translator/language-support.md
Labels: Accepted, Linguistic Suggestion

#4390 [LOC]Back-Translation "|サブスクリプション名|"→"|Subscription name|"
  articles/cognitive-services/LUIS/includes/create-luis-resource.md
Labels: Accepted, Linguistic Suggestion

#4383 Fix translations
  articles/cognitive-services/LUIS/luis-container-limitations.md
Labels: Accepted, Linguistic Suggestion

#4382 Fix translations
  articles/cognitive-services/Bing-Custom-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4397 Update overview.md
  articles/cloud-shell/overview.md
Labels: Accepted

#4396 [LOC]Back-Translation "|Location|"→"|作成場所|"
  articles/cognitive-services/LUIS/includes/get-started-get-intent-rest-python.md
Labels: Accepted, Linguistic Suggestion

#4395 [LOC]Back-Translation "|Location|"→"|作成場所|"
  articles/cognitive-services/LUIS/includes/get-started-get-intent-rest-nodejs.md
Labels: Accepted, Linguistic Suggestion

#4394 [LOC]Back-Translation "|Location|"→"|作成場所|"
  articles/cognitive-services/LUIS/includes/get-started-get-intent-rest-java.md
Labels: Accepted, Linguistic Suggestion

#4393 [LOC]Back-Translation "|Location|"→"|作成場所|"
  articles/cognitive-services/LUIS/includes/get-started-get-intent-rest-go.md
Labels: Accepted, Linguistic Suggestion

#4392 [LOC]Back-Translation "|Location|"→"|作成場所|"
  articles/cognitive-services/LUIS/includes/get-started-get-intent-rest-csharp.md
Labels: Accepted, Linguistic Suggestion

#4381 Fix translations
  articles/cognitive-services/Bing-Image-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4400 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-text-translation.md
Labels: Accepted, Linguistic Suggestion

#4399 [LOC]Back-Translation "**決定**"→"**Decision**"
  articles/mobile-apps/cognitive-services.md
Labels: Accepted, Linguistic Suggestion

#4408 Fix translations
  articles/azure-maps/weather-coverage.md
Labels: Accepted, Linguistic Suggestion

#4407 Fix translations
  articles/azure-maps/traffic-coverage.md
Labels: Accepted, Linguistic Suggestion

#4406 Fix translations
  articles/azure-maps/routing-coverage.md
Labels: Accepted, Linguistic Suggestion

#4405 Fix translations
  articles/azure-maps/render-coverage.md
Labels: Accepted, Linguistic Suggestion

#4404 Fix translations
  articles/active-directory/saas-apps/mimecast-personal-portal-tutorial.md
Labels: Accepted, Linguistic Suggestion

#4403 Fix translations
  articles/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation.md
Labels: Accepted, Linguistic Suggestion

#4402 Fix translations
  articles/active-directory-b2c/basic-age-gating.md
Labels: Accepted, Linguistic Suggestion

#4380 Fix translations
  articles/cognitive-services/Bing-Web-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4389 [LOC]Back-Translation "|カルチャ|"→"|Culture|"
  articles/cognitive-services/LUIS/get-started-portal-build-app.md
Labels: Accepted, Linguistic Suggestion

#4398 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/mobile-apps/azure-search.md
Labels: Accepted, Linguistic Suggestion

#4409 [LOC]Back-Translation "検査"→"Inspect"
  articles/cognitive-services/QnAMaker/Quickstarts/create-publish-knowledge-base.md
Labels: Accepted

#4411 [LOC]Back-Translation "発行"→"Publish"
  articles/cognitive-services/QnAMaker/Quickstarts/create-publish-knowledge-base.md
Labels: Accepted, Linguistic Suggestion

#4412 [LOC]Back-Translation "発行"→"Publish"
  articles/cognitive-services/QnAMaker/Quickstarts/add-question-metadata-portal.md
Labels: Accepted

#4410 Update configure-custom-container.md
  articles/app-service/containers/configure-custom-container.md
Labels: Accepted, Linguistic Suggestion

#4413 [LOC]Back-Translation "|操作 ID|"→"|Operation Id|"
  articles/cognitive-services/QnAMaker/Quickstarts/quickstart-rest-curl.md
Labels: Accepted, Linguistic Suggestion

#4442 [LOC]Back-Translation "My Apps"→"マイ アプリ"
  articles/cognitive-services/LUIS/luis-how-to-start-new-app.md
Labels: Accepted, Linguistic Suggestion

#4443 [LOC]Back-Translation "次へ"→"Next"
  articles/cognitive-services/LUIS/includes/sign-in-process.md
Labels: Accepted

#4444 [LOC]Back-Translation "構成と価格"→"Configuration + pricing"
  articles/hdinsight/hdinsight-autoscale-clusters.md
Labels: Accepted

#4441 Fix translations
  articles/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation.md
Labels: Accepted, Linguistic Suggestion

#4440 Fix translations
  articles/web-application-firewall/ag/geomatch-custom-rules.md
Labels: Accepted, Linguistic Suggestion

#4439 Fix translations
  articles/web-application-firewall/afds/waf-front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion

#4438 Fix translations
  articles/storsimple/storsimple-regions.md
Labels: Accepted, Linguistic Suggestion

#4437 Fix translations
  articles/storage/files/storage-sync-files-planning.md
Labels: Accepted, Linguistic Suggestion

#4436 Fix translations
  articles/security-center/security-center-data-security.md
Labels: Accepted, Linguistic Suggestion

#4435 Fix translations
  articles/migrate/migrate-support-matrix.md
Labels: Accepted, Linguistic Suggestion

#4434 Fix translations
  articles/migrate/how-to-add-tool-first-time.md
Labels: Accepted, Linguistic Suggestion

#4433 Fix translations
  articles/marketplace/partner-center-portal/tax-details-paid-transactions.md
Labels: Accepted, Linguistic Suggestion

#4432 Fix translations
  articles/marketplace/partner-center-portal/payment-thresholds-methods-timeframes.md
Labels: Accepted, Linguistic Suggestion

#4431 Fix translations
  articles/marketplace/partner-center-portal/commercial-marketplace-co-sell-countries.md
Labels: Accepted, Linguistic Suggestion

#4430 Fix translations
  articles/marketplace/marketplace-geo-availability-currencies.md
Labels: Accepted, Linguistic Suggestion

#4429 Fix translations
  articles/marketplace/consulting-services.md
Labels: Accepted, Linguistic Suggestion

#4428 Fix translations
  articles/marketplace/cloud-partner-portal-orig/cloud-partner-portal-api-setting-price.md
Labels: Accepted, Linguistic Suggestion

#4427 Fix translations
  articles/hdinsight/hdinsight-service-tags.md
Labels: Accepted, Linguistic Suggestion

#4426 Fix translations
  articles/hdinsight/hdinsight-management-ip-addresses.md
Labels: Accepted, Linguistic Suggestion

#4425 Fix translations
  articles/frontdoor/front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion

#4424 Fix translations
  articles/expressroute/expressroute-global-reach.md
Labels: Accepted, Linguistic Suggestion

#4423 Fix translations
  articles/data-factory/v1/data-factory-data-movement-activities.md
Labels: Accepted, Linguistic Suggestion

#4422 Fix translations
  articles/data-factory/azure-integration-runtime-ip-addresses.md
Labels: Accepted, Linguistic Suggestion

#4421 Fix translations
  articles/cognitive-services/text-analytics/includes/entity-types/personal-information-entities.md
Labels: Accepted, Linguistic Suggestion

#4420 Fix translations
  articles/best-practices-availability-paired-regions.md
Labels: Accepted, Linguistic Suggestion

#4419 Fix translations
  articles/backup/backup-azure-backup-server-import-export-.md
Labels: Accepted, Linguistic Suggestion

#4418 Fix translations
  articles/azure-monitor/log-query/aggregations.md
Labels: Accepted, Linguistic Suggestion

#4417 Fix translations
  articles/azure-maps/render-coverage.md
Labels: Accepted, Linguistic Suggestion

#4416 Fix translations
  articles/azure-maps/mobility-coverage.md
Labels: Accepted, Linguistic Suggestion

#4415 Fix translations
  articles/azure-maps/geocoding-coverage.md
Labels: Accepted, Linguistic Suggestion

#4414 Fix translations
  articles/cognitive-services/Bing-Web-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4459 Fix translations
  includes/cognitive-services-speech-service-region-identifier.md
Labels: Accepted, Linguistic Suggestion

#4458 Fix translations
  includes/cognitive-services-speech-service-endpoints-text-to-speech.md
Labels: Accepted, Linguistic Suggestion

#4457 Fix translations
  articles/migrate/tutorial-migrate-vmware-agent.md
Labels: Accepted, Linguistic Suggestion

#4456 Fix translations
  articles/migrate/tutorial-migrate-physical-virtual-machines.md
Labels: Accepted, Linguistic Suggestion

#4455 Fix translations
  articles/marketplace/partner-center-portal/payment-thresholds-methods-timeframes.md
Labels: Accepted, Linguistic Suggestion

#4454 Fix translations
  articles/hdinsight/hdinsight-service-tags.md
Labels: Accepted, Linguistic Suggestion

#4453 Fix translations
  articles/hdinsight/hdinsight-management-ip-addresses.md
Labels: Accepted, Linguistic Suggestion

#4452 Fix translations
  articles/frontdoor/front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion

#4451 Fix translations
  articles/data-factory/azure-integration-runtime-ip-addresses.md
Labels: Accepted, Linguistic Suggestion

#4450 Fix translations
  articles/cognitive-services/bing-visual-search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4449 Fix translations
  articles/cognitive-services/Translator/reference/v3-0-reference.md
Labels: Accepted, Linguistic Suggestion

#4448 Fix translations
  articles/cognitive-services/LUIS/luis-user-privacy.md
Labels: Accepted, Linguistic Suggestion

#4447 Fix translations
  articles/cognitive-services/Bing-Web-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4446 Fix translations
  articles/cognitive-services/Bing-News-Search/language-support.md
Labels: Accepted, Linguistic Suggestion

#4481 Fix translations
  includes/virtual-machines-common-regions.md
Labels: Accepted, Linguistic Suggestion

#4480 Fix translations
  includes/managed-disks-ultra-disks-GA-scope-and-limitations.md
Labels: Accepted, Linguistic Suggestion

#4479 Fix translations
  includes/managed-disks-common-fault-domain-region-list.md
Labels: Accepted, Linguistic Suggestion

#4478 Fix translations
  includes/bastion-regions-include.md
Labels: Accepted, Linguistic Suggestion

#4477 Fix translations
  articles/virtual-machines/workloads/sap/hana-available-skus.md
Labels: Accepted, Linguistic Suggestion

#4476 Fix translations
  articles/stream-analytics/custom-deserializer-examples.md
Labels: Accepted, Linguistic Suggestion

#4475 Fix translations
  articles/storsimple/storsimple-data-manager-overview.md
Labels: Accepted, Linguistic Suggestion

#4474 Fix translations
  articles/storage/common/account-encryption-key-create.md
Labels: Accepted, Linguistic Suggestion

#4473 Fix translations
  articles/iot-hub/iot-hub-tls-support.md
Labels: Accepted, Linguistic Suggestion

#4472 Fix translations
  articles/hpc-cache/hpc-cache-overview.md
Labels: Accepted, Linguistic Suggestion

#4471 Fix translations
  articles/hdinsight/hdinsight-service-tags.md
Labels: Accepted, Linguistic Suggestion

#4470 Fix translations
  articles/hdinsight/hbase/apache-hbase-replication.md
Labels: Accepted, Linguistic Suggestion

#4469 Fix translations
  articles/dns/dns-alias-appservice.md
Labels: Accepted, Linguistic Suggestion

#4468 Fix translations
  articles/dedicated-hsm/deployment-architecture.md
Labels: Accepted, Linguistic Suggestion

#4467 Fix translations
  articles/cosmos-db/high-availability.md
Labels: Accepted, Linguistic Suggestion

#4466 Fix translations
  articles/cognitive-services/cognitive-services-custom-subdomains.md
Labels: Accepted, Linguistic Suggestion

#4465 Fix translations
  articles/cognitive-services/Speech-Service/regions.md
Labels: Accepted, Linguistic Suggestion

#4464 Fix translations
  articles/cognitive-services/LUIS/luis-reference-regions.md
Labels: Accepted, Linguistic Suggestion

#4463 Fix translations
  articles/azure-monitor/platform/om-agents.md
Labels: Accepted, Linguistic Suggestion

#4462 Fix translations
  articles/availability-zones/az-overview.md
Labels: Accepted, Linguistic Suggestion

#4461 Fix translations
  articles/asc-for-iot/service-prerequisites.md
Labels: Accepted, Linguistic Suggestion

#4460 Fix translations
  articles/analysis-services/analysis-services-overview.md
Labels: Accepted, Linguistic Suggestion
