Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2020-06, with the labels that each got.

#4665 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/api-management/api-management-configuration-repository-git.md
Labels: Accepted, Linguistic Suggestion, P1

#4648 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-concept-annotations-syntax.md
Labels: Accepted, Linguistic Suggestion, P1

#4649 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/logic-apps-diagnosing-failures.md
Labels: Accepted, Linguistic Suggestion, P1

#4651 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/create-monitoring-tracking-queries.md
Labels: Accepted, Linguistic Suggestion, P1

#4652 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/logic-apps-create-azure-resource-manager-templates.md
Labels: Accepted, Linguistic Suggestion, P1

#4671 [LOC]Back-Translation "ヘッダー"→"Header"
  articles/cognitive-services/LUIS/luis-how-to-azure-subscription.md
Labels: Accepted, Linguistic Suggestion, P1

#4673 [LOC]Back-Translation "[変換者]"→"Translator"
  articles/cognitive-services/cognitive-services-apis-create-account.md
Labels: Accepted, Linguistic Suggestion, P1

#4677 [LOC]Back-Translation "[変換者]"→"Translator"
  articles/cognitive-services/Translator/tutorial-wpf-translation-csharp.md
Labels: Accepted, Linguistic Suggestion, P1

#4679 [LOC]Back-Translation "[変換者]"→"Translator"
  articles/cognitive-services/Translator/tutorial-build-flask-app-translation-synthesis.md
Labels: Accepted, Linguistic Suggestion, P1

#4678 [LOC]Back-Translation "ソース"→"Translator"
  articles/cognitive-services/Translator/ctf-reporting.md
Labels: Accepted, Linguistic Suggestion, P1

#4655 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/index.yml
Labels: Accepted, Linguistic Suggestion, P1

#4656 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/toc.yml
Labels: Accepted, Linguistic Suggestion, P1

#4657 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/logic-apps-deploy-azure-resource-manager-templates.md
Labels: Accepted, Linguistic Suggestion, P1

#4658 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/api-management/TOC.yml
Labels: Accepted, Linguistic Suggestion, P1

#4650 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/marketplace/cloud-partner-portal/test-drive/logic-app-test-drive.md
Labels: Accepted, Linguistic Suggestion, P1

#4653 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/monitor-logic-apps-log-analytics.md
Labels: Accepted, Linguistic Suggestion, P1

#4659 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/api-management/import-logic-app-as-api.md
Labels: Accepted, Linguistic Suggestion, P1

#4660 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/logic-apps-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4661 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/move-logic-app-resources.md
Labels: Accepted, Linguistic Suggestion, P1

#4670 [LOC]Back-Translation "ワークスペース"→"Workspace"
  articles/azure-monitor/platform/template-workspace-configuration.md
Labels: Accepted, Linguistic Suggestion, P1

#4675 [LOC]Back-Translation "認証ヘッダー"→"Authentication header(s)"
  articles/cognitive-services/Translator/reference/v3-0-dictionary-lookup.md
Labels: Accepted, Linguistic Suggestion, P1

#4662 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/cloud-services/cloud-services-how-to-create-deploy-portal.md
Labels: Accepted, Linguistic Suggestion, P1

#4663 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/cognitive-services/QnAMaker/Overview/overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4664 [LOC]Fixed inappropriate japanese "既定"→"デフォルト"
  includes/app-service-web-deploy-zip-prepare.md
Labels: Accepted, Linguistic Suggestion, P1

#4689 Fix translation
  articles/api-management/api-management-issue-templates.md
Labels: Accepted, P1

#4688 Delete unnecessary brackets
  includes/virtual-machines-common-prepay-reserved-vm-instances.md
Labels: Accepted, P2

#4687 Delete unnecessary brackets
  articles/web-application-firewall/afds/waf-front-door-configure-ip-restriction.md
Labels: Accepted, P2

#4686 Delete unnecessary brackets
  articles/active-directory/reports-monitoring/reference-audit-activities.md
Labels: Accepted, Linguistic Suggestion, P2

#4685 Delete unnecessary brackets
  articles/active-directory/fundamentals/whats-new-archive.md
Labels: Accepted, P0

#4668 Update "Get the Analyze results" section
  articles/cognitive-services/form-recognizer/quickstarts/curl-train-extract.md
Labels: Accepted, Linguistic Suggestion, P1

#4672 拡張子を拡張機能に変更
  articles/postgresql/concepts-extensions.md
Labels: Accepted, Linguistic Suggestion, P1

#4666 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/machine-learning/concept-train-model-git-integration.md
Labels: Accepted, Linguistic Suggestion, P1

#4674 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/container-instances/container-instances-volume-gitrepo.md
Labels: Accepted, Linguistic Suggestion, P1

#4680 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/static-web-apps/add-api.md
Labels: Accepted, Linguistic Suggestion, P1

#4682 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/machine-learning/team-data-science-process/group-manager-tasks.md
Labels: Accepted, Linguistic Suggestion, P1

#4690 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/connectors/connectors-native-http.md
Labels: Accepted, Linguistic Suggestion, P1

#4647 [LOC]Back-Translation "スコア"→"score"
  articles/search/cognitive-search-skill-language-detection.md
Labels: Accepted, Linguistic Suggestion, P1

#4654 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/logic-apps/manage-logic-apps-with-azure-portal.md
Labels: Linguistic Suggestion, P1, Partially Accepted

#4676 [LOC]Back-Translation "承認"→"Authorization"
  articles/cognitive-services/Translator/reference/v3-0-reference.md
Labels: Accepted, Linguistic Suggestion, P1

#4698 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/connectors/apis-list.md
Labels: Accepted, Linguistic Suggestion, P1

#4699 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/connectors/connectors-google-data-security-privacy-policy.md
Labels: Accepted, Linguistic Suggestion, P1

#4691 Fix translation
  articles/service-fabric/service-fabric-get-started-mac.md
Labels: Accepted, Linguistic Suggestion, P1

#4692 Fix translation
  articles/virtual-machines/linux/disk-encryption-sample-scripts.md
Labels: Accepted, Linguistic Suggestion, P1

#4693 Fix translation
  articles/active-directory/develop/msal-authentication-flows.md
Labels: Accepted, Linguistic Suggestion, P1

#4694 Fix translation
  articles/active-directory/develop/msal-net-migration.md
Labels: Accepted, Linguistic Suggestion, P1

#4695 Fix translation
  articles/active-directory/develop/msal-net-token-cache-serialization.md
Labels: Accepted, Linguistic Suggestion, P1

#4696 Fix translation
  articles/cosmos-db/sql-api-sdk-node.md
Labels: Accepted, Linguistic Suggestion, P1

#4697 Fix translation
  articles/service-fabric/service-fabric-local-linux-cluster-windows.md
Labels: Accepted, Linguistic Suggestion, P1

#4683 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/connectors/connectors-create-api-sqlazure.md
Labels: Linguistic Suggestion, P1, Partially Accepted

#4634 Update index.yml
  articles/peering-service/index.yml
Labels: Accepted, Linguistic Suggestion, P1

#4723 [LOC]Back-Translation "ロジック アプリ"→"Logic Apps"
  articles/analysis-services/analysis-services-refresh-logic-app.md
Labels: Accepted, Linguistic Suggestion, P1

#4700 Delete unnecessary brackets
  articles/store-sendgrid-php-how-to-send-email.md
Labels: Accepted, Linguistic Suggestion, P2

#4712 Delete unnecessary brackets
  articles/cosmos-db/create-graph-php.md
Labels: Accepted, Linguistic Suggestion, P2

#4711 Fix translation
  articles/cognitive-services/text-analytics/includes/docker-pull-sentiment-analysis-container.md
Labels: Accepted, Linguistic Suggestion, P1

#4703 Fix translation
  articles/azure-monitor/platform/om-agents.md
Labels: Accepted, Linguistic Suggestion, P1

#4716 Fix translation
  articles/dedicated-hsm/deployment-architecture.md
Labels: Accepted, Linguistic Suggestion, P1

#4717 Fix translation
  articles/iot-hub/iot-hub-tls-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4719 Fix translation
  articles/storsimple/storsimple-data-manager-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4718 Fix translation
  articles/storage/common/account-encryption-key-create.md
Labels: Accepted, Linguistic Suggestion, P1

#4722 Fix translation
  includes/virtual-machines-common-regions.md
Labels: Accepted, Linguistic Suggestion, P1

#4721 Fix translation
  includes/cognitive-services-speech-service-region-identifier.md
Labels: Accepted, Linguistic Suggestion, P1

#4704 Fix translations
  articles/cognitive-services/Bing-Autosuggest/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4705 Fix translations
  articles/cognitive-services/Bing-Spell-Check/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4706 Fix translations
  articles/cognitive-services/Computer-vision/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4761 [LOC]Back-Translation "Azure Web ジョブ SDK"→"Azure WebJobs SDK"
  articles/app-service/webjobs-create.md
Labels: Accepted, Linguistic Suggestion, P1

#4756 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/virtual-machines/linux/tutorial-elasticsearch.md
Labels: Accepted, Linguistic Suggestion, P1

#4758 [LOC]Fixed inappropriate japanese "端末エミュレーター"→"ターミナルエミュレーター"
  articles/virtual-machines/workloads/mainframe-rehosting/microfocus/run-enterprise-server-container.md
Labels: Accepted, Linguistic Suggestion, P1

#4757 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/virtual-machines/workloads/mainframe-rehosting/microfocus/demo.md
Labels: Accepted, Linguistic Suggestion, P1

#4759 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/sentinel/notebooks.md
Labels: Accepted, Linguistic Suggestion, P1

#4760 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/container-registry/container-registry-tutorial-base-image-update.md
Labels: Accepted, Linguistic Suggestion, P1

#4708 Fix translations
  articles/cognitive-services/Speech-Service/regions.md
Labels: Accepted, Linguistic Suggestion, P1

#4709 Fix translations
  articles/cognitive-services/Speech-Service/sovereign-clouds.md
Labels: Accepted, Linguistic Suggestion, P1

#4710 Fix translations
  articles/cognitive-services/immersive-reader/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4713 Fix translations
  articles/virtual-machines/workloads/sap/hana-available-skus.md
Labels: Accepted, Linguistic Suggestion, P1

#4715 Fix translations
  articles/data-factory/v1/data-factory-data-movement-activities.md
Labels: Accepted, Linguistic Suggestion, P1

#4720 Fix translations
  includes/cognitive-services-speech-service-endpoints-text-to-speech.md
Labels: Accepted, Linguistic Suggestion, P1

#4702 Fix typo
  articles/active-directory/saas-apps/github-tutorial.md
Labels: Accepted, Linguistic Suggestion, P2

#4714 Fix typo
  articles/cosmos-db/gremlin-support.md
Labels: Accepted, Linguistic Suggestion, P2

#4765 [LOC]Back-Translation "Azure Web ジョブ SDK"→"Azure WebJobs SDK"
  articles/app-service/troubleshoot-dotnet-visual-studio.md
Labels: Accepted, Linguistic Suggestion, P1

#4764 [LOC]Back-Translation "Azure Web ジョブ"→"Azure WebJobs"
  articles/app-service/faq-availability-performance-application-issues.md
Labels: Accepted, Linguistic Suggestion, P1

#4771 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/search/cognitive-search-create-custom-skill-example.md
Labels: Accepted, Linguistic Suggestion, P0

#4733 Fix translation
  articles/cdn/cdn-pop-locations.md
Labels: Accepted, Linguistic Suggestion, P1

#4732 Fix translations
  articles/azure-monitor/log-query/aggregations.md
Labels: Accepted, Linguistic Suggestion, P1

#4731 Fix translations
  articles/azure-maps/weather-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4762 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/webjobs-dotnet-deploy-vs.md
Labels: Accepted, Linguistic Suggestion, P1, Technical Issue

#4730 Fix translations
  articles/azure-maps/traffic-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4729 Fix translations
  articles/azure-maps/routing-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4728 Fix translations
  articles/azure-maps/render-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4727 Fix translation
  articles/azure-maps/mobility-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4726 Fix translation
  articles/azure-maps/geocoding-coverage.md
Labels: Accepted, Linguistic Suggestion, P1

#4725 Fix translations
  articles/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation.md
Labels: Accepted, Linguistic Suggestion, P1

#4724 Fix translation
  articles/best-practices-availability-paired-regions.md
Labels: Accepted, Linguistic Suggestion, P1

#4755 Fix translations
  articles/web-application-firewall/ag/geomatch-custom-rules.md
Labels: Accepted, Linguistic Suggestion, P1

#4754 Fix translations
  articles/web-application-firewall/afds/waf-front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion, P1

#4753 Fix translations
  articles/storsimple/storsimple-regions.md
Labels: Accepted, Linguistic Suggestion, P1

#4752 Fix translations
  articles/storage/files/storage-sync-files-planning.md
Labels: Accepted, Linguistic Suggestion, P1

#4751 Fix translations
  articles/security-center/security-center-data-security.md
Labels: Accepted, Linguistic Suggestion, P1

#4749 Fix translation
  articles/marketplace/partner-center-portal/tax-details-paid-transactions.md
Labels: Accepted, Linguistic Suggestion, P1

#4748 Fix translations
  articles/marketplace/partner-center-portal/payment-thresholds-methods-timeframes.md
Labels: Accepted, Linguistic Suggestion, P1

#4747 Fix translations
  articles/marketplace/partner-center-portal/commercial-marketplace-co-sell-countries.md
Labels: Accepted, Linguistic Suggestion, P1

#4746 Fix translations
  articles/marketplace/cloud-partner-portal-orig/cloud-partner-portal-api-setting-price.md
Labels: Accepted, Linguistic Suggestion, P1

#4745 Fix translations
  articles/marketplace/marketplace-geo-availability-currencies.md
Labels: Accepted, Linguistic Suggestion, P1

#4744 Fix translations
  articles/hdinsight/hdinsight-service-tags.md
Labels: Accepted, Linguistic Suggestion, P1

#4743 Fix translations
  articles/hdinsight/hdinsight-management-ip-addresses.md
Labels: Accepted, Linguistic Suggestion, P1

#4742 Fix translations
  articles/frontdoor/front-door-geo-filtering.md
Labels: Accepted, Linguistic Suggestion, P1

#4741 Fix translations
  articles/expressroute/expressroute-global-reach.md
Labels: Accepted, Linguistic Suggestion, P1

#4739 Fix translations
  articles/data-factory/azure-integration-runtime-ip-addresses.md
Labels: Accepted, Linguistic Suggestion, P1

#4738 Fix translation
  articles/cognitive-services/text-analytics/includes/entity-types/personal-information-entities.md
Labels: Accepted, Linguistic Suggestion, P1

#4763 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/webjobs-create.md
Labels: Accepted, Linguistic Suggestion, P1, Technical Issue

#4775 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  includes/app-service-deployment-slots-settings.md
Labels: Accepted, Linguistic Suggestion, P1

#4767 [LOC]Back-Translation "関数"→"Functions"
  articles/azure-functions/functions-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4773 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/iot-edge/how-to-create-test-certificates.md
Labels: Accepted, Linguistic Suggestion, P1

#4774 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/lab-services/devtest-lab-store-secrets-in-key-vault.md
Labels: Accepted, Linguistic Suggestion, P1

#4770 Update azure-docs.ja-jp/articles/azure-functions/index.yml
  articles/azure-functions/index.yml
Labels: Accepted, Linguistic Suggestion, P1

#4734 Fix translations
  articles/cognitive-services/Bing-Custom-Search/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4735 Fix translations
  articles/cognitive-services/Bing-Image-Search/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4768 Update profiler-overview.md
  articles/azure-monitor/app/profiler-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4766 Update azure-docs.ja-jp/articles/azure-functions/TOC.yml
  articles/azure-functions/TOC.yml
Labels: Accepted, Linguistic Suggestion, P1

#4737 Fix translations
  articles/cognitive-services/Bing-Web-Search/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4776 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-monitor/app/availability-azure-functions.md
Labels: Accepted, Linguistic Suggestion, P1

#4777 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, Linguistic Suggestion, P1

#4736 Fix translations
  articles/cognitive-services/Bing-News-Search/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4769 [LOC]Back-Translation "関数"→"Functions"
  articles/azure-functions/functions-how-to-use-azure-function-app-settings.md
Labels: Accepted, Linguistic Suggestion, P1

#4785 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-functions/functions-infrastructure-as-code.md
Labels: Accepted, Linguistic Suggestion, P1

#4786 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-functions/durable/quickstart-js-vscode.md
Labels: Accepted, Linguistic Suggestion, P1

#4787 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-functions/durable/durable-functions-types-features-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4788 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/webjobs-sdk-how-to.md
Labels: Accepted, Linguistic Suggestion, P1

#4790 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/configure-common.md
Labels: Accepted, Linguistic Suggestion, P1

#4789 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/webjobs-sdk-get-started.md
Labels: Accepted, Linguistic Suggestion, P1

#4707 Fix translations
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4795 [LOC]Back-Translation "[新しいブランチ]"→"[New branch]"
  articles/machine-learning/team-data-science-process/collaborative-coding-with-git.md
Labels: Accepted, P1

#4792 [LOC]Back-Translation "Azure Web ジョブ"→"Azure WebJobs"
  articles/cloud-services/cloud-services-dotnet-get-started.md
Labels: Accepted, Linguistic Suggestion, P1

#4793 [LOC]Back-Translation "Azure 関数"→"Azure Functions"
  articles/azure-functions/functions-bindings-return-value.md
Labels: Accepted, Linguistic Suggestion, P1

#4798 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  articles/app-service/faq-configuration-and-management.md
Labels: Accepted, Linguistic Suggestion, P1

#4797 [LOC]Back-Translation "プル要求"→"Pull request"
  articles/dev-spaces/how-to/github-actions.md
Labels: Accepted, Linguistic Suggestion, P1

#4794 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/web-application-firewall/afds/afds-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4701 Fix translation
  articles/active-directory/cloud-provisioning/reference-expressions.md
Labels: Accepted, Linguistic Suggestion, P1

#4796 Typo "pull request"→"Pull request"
  articles/static-web-apps/review-publish-pull-requests.md
Labels: Accepted, Linguistic Suggestion, P2

#4802 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/app-service/containers/quickstart-multi-container.md
Labels: Accepted, Linguistic Suggestion, P1

#4804 [LOC]Back-Translation "Web ジョブ ツール"→"WebJobs ツール"
  articles/azure-functions/functions-develop-vs.md
Labels: Accepted, Linguistic Suggestion, P1

#4800 [LOC]Back-Translation "Web ジョブ"→"WebJobs"
  includes/azure-websites-limits.md
Labels: Accepted, Linguistic Suggestion, P1

#4801 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/virtual-network/template-samples.md
Labels: Accepted, Linguistic Suggestion, P1

#4807 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  includes/aml-your-server.md
Labels: Accepted, Linguistic Suggestion, P1

#4806 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/machine-learning/samples-notebooks.md
Labels: Accepted, Linguistic Suggestion, P1

#4808 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/iot-accelerators/iot-accelerators-device-simulation-create-custom-device.md
Labels: Accepted, Linguistic Suggestion, P1

#4809 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cosmos-db/create-sql-api-nodejs.md
Labels: Accepted, Linguistic Suggestion, P1

#4810 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cosmos-db/create-cassandra-nodejs.md
Labels: Accepted, Linguistic Suggestion, P1

#4811 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/app-service/app-service-web-get-started-nodejs.md
Labels: Accepted, Linguistic Suggestion, P1

#4813 [LOC]Back-Translation "セキュリティ センター"→"Security Center"
  articles/security-center/security-center-enable-data-collection.md
Labels: Accepted, Linguistic Suggestion, P1

#4814 [LOC]Back-Translation "セキュリティ センター"→"Security Center"
  articles/security-center/security-center-recommendations.md
Labels: Accepted, Linguistic Suggestion, P1
