Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2020-03, with the labels that each got.

#4100 [LOC] Back-Translation "| **[開始]** |"→"| **Start** |"
  articles/azure-functions/functions-develop-vs-code.md
Labels: Accepted, Linguistic Suggestion

#4099 [LOC] Back-Translation "[セキュリティ]"→"[Security]"
  articles/azure-functions/functions-api-definition.md
Labels: Accepted, Linguistic Suggestion

#4101 [LOC] Translation "| **Name** |"→"| **名前** |"
  includes/functions-vstools-publish.md
Labels: Accepted, Linguistic Suggestion

#4102 [LOC]Fixed inappropriate japanese "|**公開**|"→"|**発行**|"
  includes/functions-create-function-app-portal.md
Labels: Accepted, Linguistic Suggestion

#4104 Leave elements in English
  articles/azure-monitor/platform/diagnostics-extension-schema-windows.md
Labels: Accepted, Linguistic Suggestion

#4105 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/query-odata-filter-orderby-syntax.md
Labels: Accepted, Linguistic Suggestion

#4108 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-howto-index-csv-blobs.md
Labels: Accepted, Linguistic Suggestion

#4107 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-concept-troubleshooting.md
Labels: Accepted, Linguistic Suggestion

#4106 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/query-odata-filter-orderby-syntax.md
Labels: Accepted, Linguistic Suggestion

#4179 Delete unnecessary brackets
  articles/lab-services/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4178 Delete unnecessary brackets
  articles/web-application-firewall/toc.yml
Labels: Accepted, Linguistic Suggestion

#4177 Delete unnecessary brackets
  articles/vpn-gateway/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4176 Delete unnecessary brackets
  articles/virtual-machines/windows/toc.yml
Labels: Accepted, Linguistic Suggestion

#4175 Delete unnecessary brackets
  articles/virtual-machines/troubleshooting/toc.yml
Labels: Accepted, Linguistic Suggestion

#4174 Delete unnecessary brackets
  articles/virtual-machines/linux/toc.yml
Labels: Accepted, Linguistic Suggestion

#4173 Delete unnecessary brackets
  articles/virtual-machines/index.yml
Labels: Accepted, Linguistic Suggestion

#4172 Delete unnecessary brackets
  articles/virtual-machines/extensions/toc.yml
Labels: Accepted, Linguistic Suggestion

#4171 Delete unnecessary brackets
  articles/virtual-desktop/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4170 Delete unnecessary brackets
  articles/traffic-manager/toc.yml
Labels: Accepted, Linguistic Suggestion

#4169 Delete unnecessary brackets
  articles/traffic-manager/index.yml
Labels: Accepted, Linguistic Suggestion

#4168 Delete unnecessary brackets
  articles/stream-analytics/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4167 Delete unnecessary brackets
  articles/storage/tables/TOC.yml
Labels: Accepted

#4166 Delete unnecessary brackets
  articles/storage/queues/TOC.yml
Labels: Accepted

#4165 Delete unnecessary brackets
  articles/storage/files/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4164 Delete unnecessary brackets
  articles/storage/blobs/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4163 Delete unnecessary brackets
  articles/sql-database/toc.yml
Labels: Accepted, Linguistic Suggestion

#4162 Delete unnecessary brackets
  articles/sql-database/sql-database-features-index.yml
Labels: Accepted, Linguistic Suggestion

#4161 Delete unnecessary brackets
  articles/sql-data-warehouse/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4160 Delete unnecessary brackets
  articles/site-recovery/toc.yml
Labels: Accepted, Linguistic Suggestion

#4159 Delete unnecessary brackets
  articles/service-bus-messaging/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4158 Delete unnecessary brackets
  articles/security/benchmarks/index.yml
Labels: Accepted, Linguistic Suggestion

#4157 Delete unnecessary brackets
  articles/security/benchmarks/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4156 Delete unnecessary brackets
  articles/search/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4155 Delete unnecessary brackets
  articles/role-based-access-control/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4154 Delete unnecessary brackets
  articles/private-link/toc.yml
Labels: Accepted, Linguistic Suggestion

#4153 Delete unnecessary brackets
  articles/postgresql/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4152 Delete unnecessary brackets
  articles/network-watcher/toc.yml
Labels: Accepted, Linguistic Suggestion

#4151 Delete unnecessary brackets
  articles/mysql/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4150 Delete unnecessary brackets
  articles/migrate/toc.yml
Labels: Accepted, Linguistic Suggestion

#4149 Delete unnecessary brackets
  articles/media-services/previous/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4148 Delete unnecessary brackets
  articles/mariadb/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4147 Delete unnecessary brackets
  articles/load-balancer/index.yml
Labels: Accepted, Linguistic Suggestion

#4146 Delete unnecessary brackets
  articles/load-balancer/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4145 Delete unnecessary brackets
  articles/iot-edge/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4144 Delete unnecessary brackets
  articles/industry/agriculture/toc.yml
Labels: Accepted, Linguistic Suggestion

#4143 Delete unnecessary brackets
  articles/hpc-cache/index.yml
Labels: Accepted, Linguistic Suggestion

#4142 Delete unnecessary brackets
  articles/hdinsight/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4141 Delete unnecessary brackets
  articles/governance/resource-graph/toc.yml
Labels: Accepted, Linguistic Suggestion

#4140 Delete unnecessary brackets
  articles/governance/blueprints/toc.yml
Labels: Accepted, Linguistic Suggestion

#4139 Delete unnecessary brackets
  articles/expressroute/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4138 Delete unnecessary brackets
  articles/event-hubs/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4137 Delete unnecessary brackets
  articles/event-grid/edge/toc.yml
Labels: Accepted, Linguistic Suggestion

#4136 Delete unnecessary brackets
  articles/dns/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4135 Delete unnecessary brackets
  articles/data-share/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4134 Delete unnecessary brackets
  articles/data-explorer/toc.yml
Labels: Accepted, Linguistic Suggestion

#4133 Delete unnecessary brackets
  articles/cost-management-billing/manage/toc.yml
Labels: Accepted, Linguistic Suggestion

#4132 Delete unnecessary brackets
  articles/cosmos-db/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4131 Delete unnecessary brackets
  articles/container-registry/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4130 Delete unnecessary brackets
  articles/container-instances/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4129 Delete unnecessary brackets
  articles/cognitive-services/QnAMaker/toc.yml
Labels: Accepted, Linguistic Suggestion

#4128 Delete unnecessary brackets
  articles/cognitive-services/LUIS/toc.yml
Labels: Accepted, Linguistic Suggestion

#4127 Delete unnecessary brackets
  articles/cognitive-services/LUIS/index.yml
Labels: Accepted, Linguistic Suggestion

#4126 Delete unnecessary brackets
  articles/cloud-services/toc.yml
Labels: Accepted, Linguistic Suggestion

#4125 Delete unnecessary brackets
  articles/cdn/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4124 Delete unnecessary brackets
  articles/backup/toc.yml
Labels: Accepted, Linguistic Suggestion

#4123 Delete unnecessary brackets
  articles/azure-functions/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4122 Delete unnecessary brackets
  articles/azure-cache-for-redis/index.yml
Labels: Accepted, Linguistic Suggestion

#4120 Delete unnecessary brackets
  articles/application-gateway/toc.yml
Labels: Accepted, Linguistic Suggestion

#4119 Delete unnecessary brackets
  articles/app-service-mobile/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4118 Delete unnecessary brackets
  articles/api-management/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4117 Delete unnecessary brackets
  articles/ansible/toc.yml
Labels: Accepted, Linguistic Suggestion

#4116 Delete unnecessary brackets
  articles/aks/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4115 Delete unnecessary brackets
  articles/active-directory/users-groups-roles/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4114 Delete unnecessary brackets
  articles/active-directory/saas-apps/toc.yml
Labels: Accepted, Linguistic Suggestion

#4113 Delete unnecessary brackets
  articles/active-directory/manage-apps/toc.yml
Labels: Accepted, Linguistic Suggestion

#4112 Delete unnecessary brackets
  articles/active-directory/governance/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4111 Delete unnecessary brackets
  articles/active-directory/cloud-provisioning/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4110 Delete unnecessary brackets
  articles/active-directory/authentication/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4109 Delete unnecessary brackets
  articles/active-directory-domain-services/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4121 Delete unnecessary brackets
  articles/automation/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4095 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-defining-skillset.md
Labels: Accepted, Linguistic Suggestion

#4096 [LOC]Back-Translation "| スコア |"→"| score |"
  articles/search/cognitive-search-skill-sentiment.md
Labels: Accepted, Linguistic Suggestion

#4103 Leave properties in English
  articles/azure-resource-manager/templates/common-deployment-errors.md
  articles/azure-resource-manager/templates/copy-properties.md
  articles/azure-resource-manager/templates/copy-resources.md
  articles/azure-resource-manager/templates/cross-resource-group-deployment.md
  articles/azure-resource-manager/templates/deployment-script-template.md
  articles/azure-resource-manager/templates/linked-templates.md
  articles/azure-resource-manager/templates/template-best-practices.md
  articles/azure-resource-manager/templates/template-syntax.md
  articles/azure-resource-manager/templates/toc.yml
Labels: Accepted, Linguistic Suggestion

#4181 Improve translations for 'output'
  articles/azure-functions/TOC.yml
Labels: Accepted, Linguistic Suggestion

#4184 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-analyzers.md
Labels: Accepted, Linguistic Suggestion

#4183 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/query-odata-filter-orderby-syntax.md
Labels: Accepted, Linguistic Suggestion

#4195 Delete unnecessary brackets
  articles/azure-resource-manager/managed-applications/toc.yml
Labels: Accepted

#4194 Delete unnecessary brackets
  articles/azure-monitor/toc.yml
Labels: Accepted

#4191 Improve translations コグニティブ検索->Cognitive Search
  articles/search/index-add-custom-analyzers.md
Labels: Accepted, Linguistic Suggestion

#4190 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-tutorial-blob.md
Labels: Accepted, Linguistic Suggestion

#4189 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-skill-textmerger.md
Labels: Accepted, Linguistic Suggestion

#4188 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-skill-shaper.md
Labels: Accepted, Linguistic Suggestion

#4187 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-skill-named-entity-recognition.md
Labels: Accepted, Linguistic Suggestion

#4186 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-create-custom-skill-example.md
Labels: Accepted, Linguistic Suggestion

#4185 Improve translations コグニティブ検索->Cognitive Search
  articles/search/cognitive-search-attach-cognitive-services.md
Labels: Accepted, Linguistic Suggestion

#4197 Improve translations ボット エミュレーター->Bot emulator
  articles/cognitive-services/LUIS/luis-csharp-tutorial-bf-v4.md
Labels: Accepted, Linguistic Suggestion

#4196 Improve translations ボット エミュレーター->Bot Framework Emulator
  articles/cognitive-services/LUIS/choose-natural-language-processing-service.md
Labels: Accepted, Linguistic Suggestion

#4199 Improve translations ボット エミュレーター->Bot Framework Emulator
  articles/cognitive-services/Labs/Conversation-Learner/tutorials/16-hybrid-bots.md
Labels: Accepted, Linguistic Suggestion

#4198 Improve translations ボット エミュレーター->Bot emulator
  articles/cognitive-services/LUIS/luis-nodejs-tutorial-bf-v4.md
Labels: Accepted, Linguistic Suggestion

#4180 Fix 'n/a'
  articles/azure-functions/functions-bindings-cosmosdb-v2-input.md
  articles/azure-functions/functions-bindings-cosmosdb-v2-output.md
  articles/azure-functions/functions-bindings-cosmosdb-v2-trigger.md
  articles/azure-functions/functions-bindings-event-grid-output.md
  articles/azure-functions/functions-bindings-http-webhook-trigger.md
  articles/azure-functions/functions-bindings-service-bus-output.md
  articles/azure-functions/functions-bindings-service-bus-trigger.md
  articles/azure-functions/functions-bindings-storage-blob-input.md
  articles/azure-functions/functions-bindings-storage-blob-output.md
  articles/azure-functions/functions-bindings-storage-blob-trigger.md
  articles/azure-functions/functions-bindings-storage-queue-output.md
  articles/azure-functions/functions-bindings-storage-queue-trigger.md
  articles/azure-functions/functions-bindings-storage-table.md
  articles/azure-functions/functions-bindings-timer.md
  articles/azure-functions/functions-bindings-warmup.md
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Linguistic Suggestion

#4200 Fix 'n/a'
  articles/azure-functions/functions-bindings-signalr-service-output.md
  includes/functions-bindings-event-hubs-output.md
  includes/functions-bindings-event-hubs-trigger.md
Labels: Accepted, Linguistic Suggestion

#4202 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/query-odata-filter-orderby-syntax.md
Labels: Accepted, Linguistic Suggestion

#4203 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-analyzers.md
Labels: Accepted

#4204 Fix typo
  articles/cognitive-services/QnAMaker/How-To/edit-knowledge-base.md
Labels: Accepted, Linguistic Suggestion

#4201 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/index-add-custom-analyzers.md
Labels: Accepted, Linguistic Suggestion

#4206 [LOC]Translation "**[Send]\(送信\)**"→"**[送信]**"
  articles/search/search-get-started-postman.md
Labels: Accepted, Linguistic Suggestion

#4208 [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Services"
  articles/cognitive-services/QnAMaker/whats-new.md
Labels: Accepted, Linguistic Suggestion

#4210 Delete unnecessary brackets
  articles/active-directory/app-provisioning/functions-for-customizing-application-data.md
Labels: Accepted

#4220 Delete unnecessary brackets
  articles/azure-functions/functions-bindings-service-bus-output.md
Labels: Accepted

#4219 Delete unnecessary brackets
  articles/azure-functions/functions-bindings-mobile-apps.md
Labels: Accepted

#4218 Delete unnecessary brackets
  articles/azure-functions/functions-bindings-microsoft-graph.md
Labels: Accepted

#4217 Delete unnecessary brackets
  articles/app-service/app-service-web-tutorial-windows-containers-custom-fonts.md
Labels: Accepted, Linguistic Suggestion

#4216 Delete unnecessary brackets
  articles/api-management/import-api-from-oas.md
Labels: Accepted, Linguistic Suggestion

#4215 Delete unnecessary brackets
  articles/api-management/add-api-manually.md
Labels: Accepted, Linguistic Suggestion

#4214 Delete unnecessary brackets
  articles/analysis-services/analysis-services-database-users.md
Labels: Accepted, Linguistic Suggestion

#4213 Delete unnecessary brackets
  articles/active-directory/develop/tutorial-v2-asp-webapp.md
Labels: Accepted, Linguistic Suggestion

#4212 Delete unnecessary brackets
  articles/active-directory/cloud-provisioning/reference-expressions.md
Labels: Accepted, Linguistic Suggestion

#4211 Delete unnecessary brackets
  articles/active-directory/authentication/howto-mfa-mfasettings.md
Labels: Accepted, Linguistic Suggestion

#4240 Delete unnecessary brackets
  includes/cosmos-db-create-collection.md
Labels: Accepted

#4239 Delete unnecessary brackets
  includes/cosmos-db-create-collection-preview.md
Labels: Accepted

#4238 Delete unnecessary brackets
  articles/traffic-manager/traffic-manager-diagnostic-logs.md
Labels: Accepted, Linguistic Suggestion

#4237 Delete unnecessary brackets
  articles/stream-analytics/stream-analytics-real-time-fraud-detection.md
Labels: Accepted, Linguistic Suggestion

#4236 Delete unnecessary brackets
  articles/stream-analytics/stream-analytics-manage-job.md
Labels: Accepted, Linguistic Suggestion

#4235 Delete unnecessary brackets
  articles/stream-analytics/stream-analytics-machine-learning-integration-tutorial.md
Labels: Accepted, Linguistic Suggestion

#4234 Delete unnecessary brackets
  articles/network-watcher/network-watcher-packet-capture-overview.md
Labels: Accepted, Linguistic Suggestion

#4233 Delete unnecessary brackets
  articles/lighthouse/how-to/publish-managed-services-offers.md
Labels: Accepted, Linguistic Suggestion

#4232 Delete unnecessary brackets
  articles/key-vault/about-keys-secrets-and-certificates.md
Labels: Accepted, Linguistic Suggestion

#4231 Delete unnecessary brackets
  articles/governance/blueprints/samples/iso27001-shared/deploy.md
Labels: Accepted, Linguistic Suggestion

#4230 Delete unnecessary brackets
  articles/governance/blueprints/samples/iso27001-ase-sql-workload/deploy.md
Labels: Accepted, Linguistic Suggestion

#4229 Delete unnecessary brackets
  articles/dns/dns-delegate-domain-azure-dns.md
Labels: Accepted, Linguistic Suggestion

#4228 Delete unnecessary brackets
  articles/data-explorer/devops.md
Labels: Accepted, Linguistic Suggestion

#4227 Delete unnecessary brackets
  articles/cosmos-db/understand-your-bill.md
Labels: Accepted, Linguistic Suggestion

#4226 Delete unnecessary brackets
  articles/cosmos-db/create-sql-api-python.md
Labels: Accepted, Linguistic Suggestion

#4225 Delete unnecessary brackets
  articles/cosmos-db/create-cosmosdb-resources-portal.md
Labels: Accepted, Linguistic Suggestion

#4224 Delete unnecessary brackets
  articles/cognitive-services/LUIS/get-started-portal-deploy-app.md
Labels: Accepted, Linguistic Suggestion

#4223 Delete unnecessary brackets
  articles/azure-resource-manager/templates/quickstart-create-templates-use-the-portal.md
Labels: Accepted, Linguistic Suggestion

#4222 Delete unnecessary brackets
  articles/azure-monitor/insights/container-insights-analyze.md
Labels: Accepted, Linguistic Suggestion

#4221 Delete unnecessary brackets
  articles/azure-functions/functions-bindings-storage-table.md
Labels: Accepted, Linguistic Suggestion

#4241 Delete unnecessary brackets
  includes/functions-premium-create.md
Labels: Accepted, Linguistic Suggestion

#4245 [LOC]Back-Translation "**決定**"→"**Decision**"
  articles/mobile-apps/cognitive-services.md
Labels: Accepted, Linguistic Suggestion

#4244 [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Services"
  articles/cognitive-services/LUIS/luis-reference-prebuilt-url.md
Labels: Accepted, Linguistic Suggestion

#4243 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/index-add-language-analyzers.md
Labels: Accepted, Linguistic Suggestion

#4246 過剰な翻訳を修正
  articles/cognitive-services/LUIS/luis-concept-keys.md
Labels: Accepted, Linguistic Suggestion

#4247 自然な日本語に修正
  articles/cognitive-services/LUIS/luis-concept-enterprise.md
Labels: Accepted, Linguistic Suggestion

#4249 [LOC]Back-Translation "名前"→"Name"
  articles/search/search-howto-index-cosmosdb.md
Labels: Accepted, Linguistic Suggestion

#4250 [LOC]Back-Translation "| 地理 |"→"| geography |"
  articles/search/search-howto-connecting-azure-sql-database-to-azure-search-using-indexers.md
Labels: Accepted, Linguistic Suggestion

#4251 Update resource-classes-for-workload-management.md
  articles/sql-data-warehouse/resource-classes-for-workload-management.md
Labels: Accepted, Linguistic Suggestion

#4252 [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Services"
  articles/cognitive-services/Custom-Vision-Service/home.md
Labels: Accepted, Linguistic Suggestion

#4253 Typo "Api"→"API"
  articles/search/cognitive-search-tutorial-blob.md
Labels: Accepted, Linguistic Suggestion

#4248 [LOC]Back-Translation "|種類|"→"|Type|"
  articles/search/index-add-custom-analyzers.md
Labels: Accepted, Linguistic Suggestion, Technical Issue
