Repository MicrosoftDocs/azure-docs.ja-jp, pull requests merged in 2020-05, with the labels that each got.

#4514 Fixed brackets "[[ディスク]]"→"[ディスク]"
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted, Linguistic Suggestion

#4516 Search in English
  articles/azure-maps/quick-demo-map-app.md
Labels: Accepted, Linguistic Suggestion

#4513 Update sql-database-service-tier-hyperscale.md
  articles/sql-database/sql-database-service-tier-hyperscale.md
Labels: Accepted, Linguistic Suggestion

#4517 [LOC]Back-Translation "整数"→"Integer"
  includes/cognitive-services-containers-configuration-shared-settings-fluentd.md
Labels: Accepted, Linguistic Suggestion

#4520 [LOC]Back-Translation "コンソール"→"Console"
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted, Linguistic Suggestion

#4519 [LOC]Translation "| Name |"→"| 名前 |"
  includes/cognitive-services-containers-configuration-shared-settings-eula.md
Labels: Accepted, Linguistic Suggestion

#4518 Fix "en-US" and "is"
  articles/cognitive-services/immersive-reader/language-support.md
  articles/media-services/azure-media-player/azure-media-player-localization.md
Labels: Accepted, Linguistic Suggestion, P1

#4521 Fix translations
  articles/cognitive-services/Ink-Recognizer/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4522 Fix translations
  articles/azure-maps/supported-languages.md
Labels: Accepted, Linguistic Suggestion, P1

#4506 Typo "**特殊フォルダー***outputs*"→"**特殊フォルダー** *outputs*"
  articles/machine-learning/how-to-train-ml-models.md
Labels: Accepted, Technical Issue

#4523 Fix translations
  articles/cognitive-services/bing-visual-search/language-support.md
Labels: Accepted, Linguistic Suggestion, P1

#4524 [LOC]Back-Translation "[決定]"→"[Decision]"
  articles/cognitive-services/cognitive-services-and-machine-learning.md
Labels: Accepted, Linguistic Suggestion, P1

#4525 [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Services"
  articles/cognitive-services/cognitive-services-apis-create-account.md
Labels: Accepted, Linguistic Suggestion, P1

#4526 [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Service"
  articles/cognitive-services/Content-Moderator/index.yml
Labels: Accepted, Linguistic Suggestion, P1

#4530 fix typo
  articles/azure-monitor/app/javascript.md
Labels: Accepted, Linguistic Suggestion, P1

#4537 [LOC]Back-Translation "[意図]"→"[Intents]"
  articles/cognitive-services/LUIS/luis-how-to-add-intents.md
Labels: Accepted, Linguistic Suggestion, P1

#4532 [LOC]Fixed inappropriate japanese "Is リージョン"→"リージョン"
  articles/cognitive-services/cognitive-services-custom-subdomains.md
Labels: Accepted, Linguistic Suggestion, P1

#4536 [LOC]Back-Translation "[ビルド]"→"[Build]"
  articles/cognitive-services/LUIS/howto-add-prebuilt-models.md
Labels: Accepted, Linguistic Suggestion, P1

#4535 [LOC]Back-Translation "[記述子]"→"[Descriptors]"
  articles/cognitive-services/LUIS/luis-how-to-add-features.md
Labels: Accepted, Linguistic Suggestion, P1, Technical Issue

#4538 Fix doc
  articles/sql-database/replication-to-sql-database.md
Labels: Accepted, Linguistic Suggestion, P1

#4534 [LOC]Fixed inappropriate japanese "FluentdFluentd サーバーに対するコンテナー"
  includes/cognitive-services-containers-configuration-shared-settings-fluentd.md
Labels: Accepted, Linguistic Suggestion, P1

#4539 Update expressroute-faqs.md
  articles/expressroute/expressroute-faqs.md
Labels: Accepted, Linguistic Suggestion, P1

#4541 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/Speech-Service/how-to-recognize-intents-from-speech-csharp.md
Labels: Accepted, P1

#4540 Fix doc
  articles/search/search-query-odata-search-score-function.md
Labels: Accepted, Linguistic Suggestion, P1

#4542 [LOC]Back-Translation "| スターター |"→"| Starter |"
  articles/cognitive-services/Speech-Service/how-to-recognize-intents-from-speech-csharp.md
Labels: Accepted, Linguistic Suggestion, P1

#4543 [LOC]Back-Translation "[検査]"→"[Inspect]"
  articles/cognitive-services/LUIS/luis-interactive-test.md
Labels: Accepted, P1

#4544 Broken link "LUISWeb サイトの[Keys and endpoints](キーとエンドポイント)"
  articles/cognitive-services/LUIS/luis-glossary.md
Labels: Accepted, P1

#4545 [LOC]Translation "Build a LUIS app programmatically using Node.js"
  articles/cognitive-services/LUIS/troubleshooting.md
Labels: Accepted, Linguistic Suggestion, P1

#4548 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/luis-container-howto.md
Labels: Accepted, P1

#4547 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/luis-tutorial-node-import-utterances-csv.md
Labels: Accepted, P1

#4546 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/troubleshooting.md
Labels: Accepted, Linguistic Suggestion, P1

#4552 Update: typo
  articles/application-gateway/tutorial-url-route-cli.md
Labels: Accepted, Linguistic Suggestion, P1

#4549 Update functions-create-first-function-vs-code.md
  articles/azure-functions/functions-create-first-function-vs-code.md
Labels: Accepted, Linguistic Suggestion, P1

#4554 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/includes/sign-in-process.md
Labels: Accepted, P1

#4555 [LOC]Back-Translation " [意図]"→"[Intents]"
  articles/cognitive-services/LUIS/get-started-portal-build-app.md
Labels: Accepted, Linguistic Suggestion, P1

#4556 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/luis-how-to-manage-versions.md
Labels: Accepted, Linguistic Suggestion, P1

#4553 Update "トリミング" to "クロッピング"
  articles/media-services/latest/media-services-v2-vs-v3.md
Labels: Accepted, Linguistic Suggestion, P1

#4566 [LOC]Back-Translation " [マイ アプリ]"→" [My apps]"
  articles/cognitive-services/LUIS/includes/import-app-steps.md
Labels: Accepted, P1

#4557 Update functions-overview.md
  articles/azure-functions/functions-overview.md
Labels: Accepted, Linguistic Suggestion, P1

#4560 [LOC]Fixed inappropriate japanese "[ビュー]"→"[表示]"
  articles/governance/policy/how-to/extension-for-vscode.md
Labels: Accepted, Linguistic Suggestion, P1

#4559 [LOC]Fixed inappropriate japanese "[ビュー]"→"[表示]"
  articles/iot-edge/how-to-vs-code-develop-module.md
Labels: Accepted, Linguistic Suggestion, P1

#4569 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/service-fabric/service-fabric-create-your-first-linux-application-with-java.md
Labels: Accepted, Linguistic Suggestion, P1

#4568 [LOC]Fixed inappropriate japanese "[端末]"→"[ターミナル]"
  articles/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert.md
Labels: Accepted, Linguistic Suggestion, P1

#4567 [LOC]Fixed inappropriate japanese "[端末]"→"[ターミナル]"
  articles/vpn-gateway/point-to-site-vpn-client-configuration-radius.md
Labels: Accepted, Linguistic Suggestion, P1

#4570 Fix typo
  articles/service-bus-messaging/message-sessions.md
Labels: Accepted, Linguistic Suggestion, P1

#4571 Update sql-database-manage-logins.md
  articles/sql-database/sql-database-manage-logins.md
Labels: Accepted, Linguistic Suggestion, P1

#4572 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/cloud-shell/using-the-shell-window.md
Labels: Accepted, Linguistic Suggestion, P1

#4573 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/service-fabric/service-fabric-java-rest-api-usage.md
Labels: Accepted, Linguistic Suggestion, P1

#4562 [LOC]Back-Translation "[実験]"→"[Experiment]"
  articles/machine-learning/tutorial-train-deploy-image-classification-model-vscode.md
Labels: Accepted, Linguistic Suggestion, P1

#4563 [LOC]Fixed inappropriate japanese "[ビュー]"→"[表示]"
  articles/iot-edge/how-to-deploy-blob.md
Labels: Accepted, Linguistic Suggestion, P1

#4565 Fix translation of "updates"
  articles/storage/blobs/storage-manage-find-blobs.md
Labels: Accepted, Linguistic Suggestion, P1

#4564 [LOC]Fixed inappropriate japanese "[ビュー]"→"[表示]"
  articles/cosmos-db/create-sql-api-python.md
Labels: Accepted, Linguistic Suggestion, P1

#4577 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/azure-functions/functions-run-local.md
Labels: Accepted, Linguistic Suggestion, P1

#4576 [LOC]Back-Translation "[リソースの作成]"→"[Create a resource]"
  articles/cognitive-services/LUIS/luis-tutorial-bing-spellcheck.md
Labels: Accepted, Linguistic Suggestion, P1

#4578 [LOC]Fixed inappropriate japanese "展開"→"デプロイ"
  articles/logic-apps/manage-logic-apps-with-visual-studio.md
Labels: Accepted, Linguistic Suggestion, P1

#4575 Fix typo
  articles/role-based-access-control/troubleshooting.md
Labels: Accepted, Linguistic Suggestion, P1

#4582 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/container-registry/container-registry-tutorial-multistep-task.md
Labels: Accepted, Linguistic Suggestion, P1

#4581 Table Storage showed twice
  articles/search/cognitive-search-concept-intro.md
Labels: Accepted, Linguistic Suggestion, P1

#4585 [LOC]Back-Translation "[複製またはダウンロード]"→"[Clone or download]"
  articles/sql-database/saas-tenancy-wingtip-app-guidance-tips.md
Labels: Accepted, P1

#4583 Update template-syntax.md
  articles/azure-resource-manager/templates/template-syntax.md
Labels: Accepted, Linguistic Suggestion, P1

#4584 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  includes/durable-functions-prerequisites.md
Labels: Accepted, Linguistic Suggestion, P1

#4579 Keep Cognitive Services Translator in English
  articles/cognitive-services/Translator/index.yml
  articles/cognitive-services/Translator/toc.yml
  articles/cognitive-services/cognitive-services-support-options.md
  articles/cognitive-services/index.yml
  bread/toc.yml
Labels: In Progress, Linguistic Suggestion, P1

#4586 [LOC]Back-Translation "[複製またはダウンロード]"→"[Clone or download]"
  articles/lab-services/devtest-lab-add-artifact-repo.md
Labels: Accepted, Linguistic Suggestion, P1

#4591 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/lab-services/add-artifact-repository.md
Labels: Accepted, P1

#4588 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/includes/quickstarts/csharp-tutorial.md
Labels: Accepted, P1

#4587 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/includes/quickstarts/csharp-tutorial-od.md
Labels: Accepted, P1

#4592 [LOC]Back-Translation "[複製またはダウンロード]"→"[Clone or download]"
  articles/sql-database/saas-multitenantdb-get-started-deploy.md
Labels: Accepted, P1

#4598 [LOC]Back-Translation "[複製またはダウンロード]"→"[Clone or download]"
  articles/sql-database/saas-dbpertenant-get-started-deploy.md
Labels: Accepted, P1

#4610 [LOC]Fixed inappropriate japanese "[使ってみる]"→"[テスト]"
  includes/cloud-shell-try-it.md
Labels: Accepted, Linguistic Suggestion, P1

#4611 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  includes/app-service-web-deploy-zip-prepare.md
Labels: Accepted, Linguistic Suggestion, P1

#4593 [LOC]Fixed inappropriate japanese "複製"→"クローン
  articles/cognitive-services/Custom-Vision-Service/includes/python-get-images.md
Labels: Accepted, Linguistic Suggestion, P1

#4595 [LOC]Fixed inappropriate japanese "複製"→"クローン
  articles/iot-hub/quickstart-send-telemetry-android.md
Labels: Accepted, Linguistic Suggestion, P1

#4589 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/includes/quickstarts/java-tutorial.md
Labels: Accepted, Linguistic Suggestion, P1

#4590 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/iot-hub/quickstart-control-device-android.md
Labels: Accepted, Linguistic Suggestion, P1

#4596 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/iot-accelerators/iot-accelerators-connecting-pi-c.md
Labels: Accepted, Linguistic Suggestion, P1

#4594 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/iot-visual-alerts-tutorial.md
Labels: Accepted, Linguistic Suggestion, P1

#4599 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/analysis-services/analysis-services-async-refresh.md
Labels: Accepted, Linguistic Suggestion, P1

#4600 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/logo-detector-mobile.md
Labels: Accepted, Linguistic Suggestion, P1

#4601 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/iot-accelerators/iot-accelerators-connecting-devices-linux.md
Labels: Accepted, Linguistic Suggestion, P1

#4602 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/storage/common/storage-auth-aad-app.md
Labels: Accepted, Linguistic Suggestion, P1

#4603 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/dev-spaces/get-started-netcore.md
Labels: Accepted, Linguistic Suggestion, P1

#4605 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/sentinel/notebooks.md
Labels: Accepted, Linguistic Suggestion, P1

#4606 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/dev-spaces/how-to/setup-cicd.md
Labels: Accepted, Linguistic Suggestion, P1

#4607 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cosmos-db/create-mongodb-flask.md
Labels: Accepted, Linguistic Suggestion, P1

#4609 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/container-registry/container-registry-tutorial-private-base-image-update.md
Labels: Accepted, Linguistic Suggestion, P1

#4597 Fix typo
  articles/hdinsight/disk-encryption.md
Labels: Accepted, Linguistic Suggestion, P1

#4608 Fixed typo
  articles/app-service/overview-inbound-outbound-ips.md
Labels: Accepted, Linguistic Suggestion, P1

#4616 [LOC] Translation "**Location**"→"**場所**"
  includes/azure-app-configuration-create.md
Labels: Accepted, Linguistic Suggestion, P1

#4615 [LOC]Fixed inappropriate japanese "[テスト]"→"[使ってみる]"
  includes/cloud-shell-try-it.md
Labels: Accepted, Linguistic Suggestion, P1

#4614 [LOC]Fixed inappropriate japanese "[試してみる]"→"[使ってみる]"
  articles/virtual-machines/linux/tutorial-availability-sets.md
Labels: Accepted, Linguistic Suggestion, P1

#4617 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/app-service/containers/tutorial-python-postgresql-app.md
Labels: Accepted, Linguistic Suggestion, P1

#4604 Typo "/(ZIP をダウンロード/)"→"\(ZIP をダウンロード\)"
  articles/sql-database/saas-dbpertenant-get-started-deploy.md
Labels: Accepted, Linguistic Suggestion, P2

#4619 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/cognitive-services/Custom-Vision-Service/includes/node-get-images.md
Labels: Accepted, Linguistic Suggestion, P1

#4621 [LOC]Back-Translation "付与タイプ"→"Grant Type"
  articles/digital-twins/how-to-configure-postman.md
Labels: Accepted, Linguistic Suggestion, P1

#4612 Fix japanese language translation
  articles/backup/backup-azure-monitoring-built-in-monitor.md
Labels: Accepted, Linguistic Suggestion, P1

#4623 Update sql-data-warehouse-how-to-convert-resource-classes-workload-gr…
  articles/synapse-analytics/sql-data-warehouse/sql-data-warehouse-how-to-convert-resource-classes-workload-groups.md
Labels: Accepted, Linguistic Suggestion, P1

#4624 Fix doc
  articles/azure-resource-manager/templates/copy-outputs.md
Labels: Accepted, Linguistic Suggestion, P1

#4625 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/container-registry/container-registry-tutorial-quick-task.md
Labels: Accepted, Linguistic Suggestion, P1

#4626 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/service-fabric/service-fabric-java-rest-api-usage.md
Labels: Accepted, Linguistic Suggestion, P1

#4631 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/site-recovery/azure-to-azure-replicate-after-migration.md
Labels: Accepted, Linguistic Suggestion, P1

#4632 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/virtual-network/virtual-networks-viewing-and-modifying-hostnames.md
Labels: Accepted, Linguistic Suggestion, P1

#4628 LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/storage/common/storage-use-azcopy-migrate-on-premises-data.md
Labels: Accepted, Linguistic Suggestion, P1

#4629 LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/hdinsight/hdinsight-hadoop-linux-use-ssh-unix.md
Labels: Accepted, Linguistic Suggestion, P1

#4639 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/remote-rendering/quickstarts/render-model.md
Labels: Accepted, Linguistic Suggestion, P1

#4638 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  articles/vpn-gateway/vpn-gateway-vnet-vnet-rm-ps.md
Labels: Accepted, Linguistic Suggestion, P1

#4642 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-text-translation.md
Labels: Accepted, Linguistic Suggestion, P1

#4643 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/search-howto-index-csv-blobs.md
Labels: Accepted, Linguistic Suggestion, P1

#4644 [LOC]Back-Translation "コグニティブ検索"→"Cognitive Search"
  articles/search/cognitive-search-skill-named-entity-recognition.md
Labels: Accepted, Linguistic Suggestion, P1

#4645 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/event-hubs/event-hubs-kafka-mirror-maker-tutorial.md
Labels: Accepted, Linguistic Suggestion, P1

#4646 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  articles/event-hubs/event-hubs-kafka-spark-tutorial.md
Labels: Accepted, Linguistic Suggestion, P1
